import type { ExpoConfig } from 'expo/config';

import { resolveApiBaseUrl } from './src/config/apiBaseUrl.ts';

/**
 * Managed workflow, no bare eject: `ios/` is generated by `expo prebuild` and never edited.
 *
 * One extension is in scope (brief.md D6, which overrode "out of scope for v1"): the widget
 * target in `targets/widget/`, added by `@bacons/apple-targets` (pinned to 4.0.7 for SDK 53).
 * It holds the Home Screen widget and the Live Activity (Lock Screen and Dynamic Island), and
 * the app starts, updates and ends activities through the local module in
 * `modules/builder-live`. What this costs in config is below: one App Group, shared by the app
 * and the extension for the widget's snapshot, and `NSSupportsLiveActivities` on the APP's
 * Info.plist, since the app is what calls `Activity.request`. A notification service extension
 * stays out of scope. After touching `targets/` or this file, prebuild with `--clean`
 * (apple-targets issue 201).
 */
// The rule and its message live in src/config/apiBaseUrl.ts so `bun test` can run
// them; a guard nobody has ever executed is a guard nobody should trust.
const apiBaseUrl = resolveApiBaseUrl(process.env);

const config: ExpoConfig = {
  name: 'Builder',
  slug: 'builder',
  scheme: 'builder',
  version: '0.1.0',
  orientation: 'portrait',
  userInterfaceStyle: 'dark',
  newArchEnabled: true,

  // Bit's resting pose, rendered from the same sixteen strings the app animates and the
  // same `design/tokens.json` amber. `make icons` re-renders all four from
  // `scripts/gen_app_icons.py`, so the store icon cannot drift from the mascot on screen.
  icon: './assets/icon.png',
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#141210',
  },

  ios: {
    // Grouped under the primary App ID in the Sign in with Apple pane, or Apple scopes
    // the `sub` claim per App ID and the same person gets two accounts.
    bundleIdentifier: 'com.vedantlbhatt.Builder',
    supportsTablet: false,
    // Shared with the widget extension (targets/widget/expo-target.config.js reads it from
    // here): the app writes the widget's snapshot into it. A device build needs both bundle
    // ids, this one and `.widgets`, registered with this same group.
    entitlements: {
      'com.apple.security.application-groups': ['group.com.vedantlbhatt.Builder'],
    },
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
      NSCameraUsageDescription:
        'Builder uses the camera only to scan the pairing code shown by the Mac agent.',
      NSSupportsLiveActivities: true,
    },
  },

  android: {
    package: 'com.vedantlbhatt.Builder',
    adaptiveIcon: {
      // Transparent foreground on the app's own background. Android masks this to the
      // launcher's shape inside the middle 66% of the canvas, which is why the generator
      // draws the character smaller here than in the iOS icon.
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#141210',
    },
  },

  web: {
    favicon: './assets/favicon.png',
  },

  plugins: [
    'expo-router',
    'expo-secure-store',
    'expo-apple-authentication',
    ['expo-camera', { cameraPermission: 'Scan the pairing code shown by your Mac.' }],
    ['expo-notifications', { color: '#FFB300' }],
    'expo-sqlite',
    // Post media. The picker plugin would also stamp a generic microphone string; expo-av
    // runs after it and its explicit string wins (an explicit value beats an existing one
    // in `IOSConfig.Permissions.applyPermissions`).
    [
      'expo-image-picker',
      { photosPermission: 'Builder attaches the photos you choose to the sessions you share.' },
    ],
    ['expo-av', { microphonePermission: 'Builder records the voice note you add to a shared session.' }],
    // The widget extension from targets/widget (Home Screen widget + Live Activity). Ahead of
    // the fmt patch, the order the SDK 53 + Xcode 26.5 lab build ran them in.
    '@bacons/apple-targets',
    // Local plugin. Survives `expo prebuild`, which regenerates ios/Podfile.
    './plugins/withFmtConstevalPatch',
  ],

  extra: {
    apiBaseUrl,
    // Google sign-in runs the browser-based id_token flow with no native SDK. Empty means
    // "not configured": the button renders disabled and says so rather than opening a
    // consent page that would 400.
    googleClientId: process.env.GOOGLE_CLIENT_ID ?? '',
    googleRedirectUri: process.env.GOOGLE_REDIRECT_URI ?? 'builder://auth/google',
    eas: { projectId: process.env.EAS_PROJECT_ID ?? '' },
  },

  experiments: { typedRoutes: true },
};

export default config;
