# GENERATED by scripts/gen_shipkit.py from spec/shipkit.v1.json — DO NOT EDIT.
"""The ship kit's enums, caps and refusal sentences, for the Mac (docs/ship-kit.md).

Nothing imported: capture is standard library only. The server builds its door from the same
spec (server/builder/shipkit_spec.py) and the phone its types (mobile/src/generated/shipkit.ts).
"""

from __future__ import annotations

SHIPKIT_VERSION = 1
THREAD_MAX = 5

#: Legal values for every enum, in spec order.
ENUMS: dict[str, list[str]] = {
    "platform": ["x", "linkedin", "threads", "instagram", "tiktok", "bluesky"],
    "kit_format": ["vertical", "feed", "landscape", "square"],
    "kit_slot": ["video_vertical", "video_feed", "video_landscape", "video_square", "loop", "still", "framed_still", "before_after", "app_store_iphone", "app_store_ipad"],
    "kit_content_type": ["image/png", "image/jpeg", "image/gif", "video/mp4"],
    "caption_source": ["model", "template"],
    "request_status": ["queued", "claimed", "done", "failed", "cancelled"],
    "request_refusal": ["not_runnable", "capture_failed", "privacy_refused", "kit_failed", "no_checkout", "excluded", "cancelled_on_mac"],
    "kit_refusal": ["device_aspect_mismatch", "blank_segment", "render_failed", "invented_number", "names_a_repository", "over_limit", "no_model", "loop_too_large", "aspect_too_far", "no_ipad_capture", "not_an_ios_app", "no_previous_demo", "no_video", "privacy_not_checked"],
    "queue_skip": ["not_a_repository", "excluded", "nothing_shipped", "not_demoable", "already_filmed", "already_queued"],
    "hue": ["tide", "ember", "iris", "brass", "orchid", "cobalt", "coral", "heather", "amber"],
}

#: Character caps by size class.
MAX_LENGTHS: dict[str, int] = {
    "tweet": 280,
    "post": 3000,
    "subject": 120,
    "label": 80,
    "name": 60,
    "why": 300,
}

#: Characters a caption may run to, per platform (the spec says where each number is from).
PLATFORM_LIMITS: dict[str, int] = {
    "x": 280,
    "bluesky": 300,
    "threads": 500,
    "linkedin": 3000,
    "instagram": 2200,
    "tiktok": 2200,
}

#: The format each platform's post shows best.
PLATFORM_FORMAT: dict[str, str] = {
    "x": "landscape",
    "bluesky": "landscape",
    "threads": "feed",
    "linkedin": "feed",
    "instagram": "feed",
    "tiktok": "vertical",
}

#: What one published kit may hold.
CAPS: dict[str, int] = {
    "videos": 4,
    "loops": 1,
    "stills": 8,
    "framed_stills": 8,
    "before_after": 4,
    "app_store_each": 8,
    "video_bytes": 41943040,
    "image_bytes": 6291456,
    "gif_bytes": 8388608,
    "video_ms": 31000,
    "pixels": 8192,
}

#: Every refusal code's sentence: the words the Mac, the server and the phone all say.
REFUSALS: dict[str, str] = {
    "device_aspect_mismatch": "the device came out a different shape in this format than it is, so the format was not kept",
    "blank_segment": "part of the video shows a blank screen, so it was not kept",
    "render_failed": "this format could not be rendered",
    "invented_number": "the caption carried a number the session never gave, so it was dropped",
    "names_a_repository": "the caption named a repository, so it was dropped",
    "over_limit": "the caption ran past what the platform takes, so it was dropped",
    "no_model": "no caption could be written: claude is not on this Mac",
    "loop_too_large": "the GIF came out too large to paste anywhere, so there is none",
    "aspect_too_far": "the screenshots are not the shape the App Store asks for",
    "no_ipad_capture": "an iPad screenshot has to be filmed on an iPad: python -m capture demo --device ipad-pro-13 --no-video",
    "not_an_ios_app": "App Store screenshots are for an iOS app",
    "no_previous_demo": "there is no earlier demo to compare with yet",
    "no_video": "the demo has no video, so the kit has stills only",
    "privacy_not_checked": "the demo's privacy check did not pass, so no kit is made from it",
    "not_runnable": "this project could not be run on the Mac",
    "capture_failed": "the Mac could not film it",
    "privacy_refused": "the Mac found a name or a key on screen and kept the demo to itself",
    "kit_failed": "the demo was made, and the kit around it was not",
    "no_checkout": "the Mac has no checkout of this project",
    "excluded": "this repository is excluded",
    "cancelled_on_mac": "it was cancelled on the Mac",
    "not_a_repository": "the session did not run in a repository",
    "nothing_shipped": "the session committed nothing the app shows",
    "not_demoable": "the project is not something the Mac can run and film",
    "already_filmed": "the newest commit is already filmed",
    "already_queued": "a demo of it is already waiting",
}
