# GENERATED by scripts/gen_drops.py from spec/drops.v1.json — DO NOT EDIT.
"""A drop's resolution, server side.

`extra="forbid"` and the bounds are the enforcement half of drops/schema.json: the
constrained decoder that wrote the plan honours the enums and the required fields, but
string lengths, the stamped block and the refusal rule are checked HERE, on the way into
Postgres, or nowhere.

Datetimes are `AwareDatetime` for the reason scripts/gen_contract.py gives: the plain type
accepts an offsetless stamp, and the first `now(UTC) - naive` downstream is a TypeError that
turns one bad upload into a 500 for the whole batch.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator, model_validator

DROPS_VERSION = 1

#: Character caps by size class; the spec's `max` on a string field names one of these.
DROPS_MAX_LENGTHS: dict[str, int] = {
    "name": 80,
    "line": 200,
    "quote": 300,
    "ref": 140,
    "url": 500,
    "tag": 24,
    "step": 240,
    "qty": 40,
    "ingredient": 80,
}

#: Legal values for every enum, in spec order. The routes import `DROP_STATUS` and
#: `MOVE_STATUS` from here rather than restating the row states beside the wire's.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "drop_kind": ["skill", "technique", "project", "tool", "recipe", "unknown"],
    "move_kind": ["install", "apply", "scaffold", "evaluate", "card", "keep"],
    "move_target": ["new_project", "existing_repo", "this_machine", "none"],
    "source_kind": ["github", "npm", "pypi", "cargo", "homebrew", "mcp", "plugin_marketplace", "docs_url"],
    "effort": ["minutes", "an_hour", "a_session"],
    "platform": ["instagram", "tiktok", "youtube", "x", "reddit", "threads", "web"],
    "resolver": ["oembed", "yt_dlp", "opengraph", "shared_text"],
    "verify_state": ["verified", "unverified", "unchecked"],
    "found_by": ["caption", "search"],
    "drop_refusal": ["url_unsupported", "no_text", "private_or_gone", "not_about_building", "planner_unavailable", "planner_refused"],
    "move_refusal": ["source_unverified", "evidence_not_found", "no_repo_match"],
    "drop_status": ["waiting", "resolving", "planned", "refused", "archived"],
    "move_status": ["offered", "queued", "running", "done", "failed", "declined"],
}

#: model name -> field name -> enum name, for the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "MoveSource": {"source_kind": "source_kind"},
    "MoveVerification": {"state": "verify_state", "found_by": "found_by", "refusal": "move_refusal"},
    "RecipeIngredient": {},
    "RecipeStep": {},
    "Recipe": {},
    "Move": {"move_kind": "move_kind", "target": "move_target", "effort": "effort"},
    "DropPlan": {"kind": "drop_kind", "refusal": "drop_refusal"},
    "DropSource": {"platform": "platform", "resolver": "resolver"},
    "DropResolution": {"refusal": "drop_refusal"},
}

DROP_STATUS: list[str] = ANALYSIS_ENUM_VALUES["drop_status"]
MOVE_STATUS: list[str] = ANALYSIS_ENUM_VALUES["move_status"]


class MoveSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source_kind: str
    ref: str = Field(max_length=140)
    url: str = Field(max_length=500)

    @field_validator("source_kind")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class MoveVerification(BaseModel):
    model_config = ConfigDict(extra="forbid")

    state: str
    found_by: str | None = None
    http_status: int | None = None
    checked_at: AwareDatetime | None = None
    refusal: str | None = None

    @field_validator("state", "found_by", "refusal")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class RecipeIngredient(BaseModel):
    model_config = ConfigDict(extra="forbid")

    item: str = Field(max_length=80)
    quantity: str | None = Field(default=None, max_length=40)
    note: str | None = Field(default=None, max_length=40)


class RecipeStep(BaseModel):
    model_config = ConfigDict(extra="forbid")

    text: str = Field(max_length=240)
    minutes: int | None = None


class Recipe(BaseModel):
    model_config = ConfigDict(extra="forbid")

    serves: str | None = Field(default=None, max_length=40)
    total_minutes: int | None = None
    ingredients: list[RecipeIngredient] = Field(max_length=40)
    steps: list[RecipeStep] = Field(max_length=30)
    equipment: list[Annotated[str, Field(max_length=80)]] = Field(max_length=8)
    found_url: str | None = Field(default=None, max_length=500)


class Move(BaseModel):
    model_config = ConfigDict(extra="forbid")

    move_kind: str
    title: str = Field(max_length=80)
    intent: str = Field(max_length=200)
    evidence: str = Field(max_length=300)
    target: str
    effort: str
    source: MoveSource | None = None
    verification: MoveVerification | None = None

    @field_validator("move_kind", "target", "effort")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DropPlan(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: str
    title: str = Field(max_length=80)
    summary: str = Field(max_length=200)
    confidence: int = Field(ge=0, le=100)
    refusal: str | None = None
    moves: list[Move] = Field(max_length=5)
    recipe: Recipe | None = None
    tags: list[Annotated[str, Field(max_length=24)]] = Field(max_length=6)

    @field_validator("kind", "refusal")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DropSource(BaseModel):
    model_config = ConfigDict(extra="forbid")

    platform: str
    url: str = Field(max_length=500)
    author: str | None = Field(default=None, max_length=80)
    title: str | None = Field(default=None, max_length=200)
    thumbnail_url: str | None = Field(default=None, max_length=500)
    duration_s: int | None = None
    caption_chars: int
    transcript_chars: int
    resolver: str
    resolved_at: AwareDatetime

    @field_validator("platform", "resolver")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DropResolution(BaseModel):
    model_config = ConfigDict(extra="forbid")

    drops_version: int
    source: DropSource
    plan: DropPlan | None = None
    refusal: str | None = None
    planner_model: str | None = Field(default=None, max_length=80)
    planned_at: AwareDatetime | None = None

    @field_validator("refusal")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


    @model_validator(mode="after")
    def _plan_or_refusal(self):
        """One of the two, never neither and never both.

        Neither is a resolution that says nothing happened and does not say why, which is
        the shape a card cannot render and a person cannot act on. Both is a plan the phone
        would draw under a refusal, and there is no rule for which of them wins.
        """
        if (self.plan is None) == (self.refusal is None):
            raise ValueError(
                "a resolution carries a plan or a refusal: "
                f"plan={'set' if self.plan is not None else 'null'}, "
                f"refusal={self.refusal!r}"
            )
        if self.plan is not None and self.planned_at is None:
            raise ValueError("a plan without planned_at cannot be told from the next one")
        return self
