# GENERATED by scripts/gen_live.py from spec/live.v1.json — DO NOT EDIT.
"""A running session's live state, server side.

`extra="forbid"` at every level and the patterns below are the whole of the enforcement:
the document is computed by `analysis/live.py` (on the server for the hook channel, on the
machine for `capture sync --live`), and a key it grows without the spec growing it is a
422 here rather than a field nobody declared sitting in `session_live.body`.

`Hex16` is why a path cannot pass as a file id, and `LiveName.name` is the only free string
in the document (a basename, capped at 120, sent only with File names on).
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

LIVE_VERSION = 1

Hex16 = Annotated[str, Field(pattern=r"^[0-9a-f]{16}$")]

#: Character caps by size class; the spec's `max` on a string field names one of these.
LIVE_MAX_LENGTHS: dict[str, int] = {
    "name": 120,
}

#: Legal values for every enum, in spec order. Named for the emitter in
#: scripts/gen_analysis.py, whose validators read these two tables by name.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "activity_kind": ["reading", "editing", "testing", "running", "searching", "delegating", "waiting_on_you", "thinking", "idle"],
    "plain_role": ["test", "source", "config", "docs", "migration", "style", "build", "dependency", "unknown"],
    "verdict_state": ["starting", "converging", "circling", "lost", "waiting", "done"],
    "verdict_basis": ["turn_ended", "turn_ended_background_out", "segment_tool_calls", "causes:repeated_call", "causes:file_churn_with_failures", "consecutive_failures", "edits_to_unread_files", "error_rate_down_and_new_files"],
    "verdict_refusal": ["no_events", "no_rule_fired"],
    "eta_basis": ["finished_sessions_same_repo_that_ran_at_least_this_long"],
    "eta_refusal": ["no_active_time", "repo_unresolved", "no_history", "too_few_sessions", "too_few_survivors"],
    "decision_kind": ["force_pushed", "deleted_test", "weakened_test", "skipped_hook", "reverted_changes", "abandoned_plan", "changed_schema", "removed_dependency", "added_dependency", "switched_approach"],
    "needs_you_reason": ["waiting_for_input", "circling", "lost", "error_loop", "idle", "finished_unreviewed", "waiting_on_background", "running_fine"],
    "frame_kind": ["read", "edit", "fail"],
    "phase": ["working", "needsYou", "done", "stalled"],
    "trajectory": ["converging", "circling", "lost", "none"],
    "creature": ["crab", "octopus", "dog", "cat", "owl", "fox", "whale", "bee", "bit"],
}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "LiveActivity": {"kind": "activity_kind", "role": "plain_role"},
    "LiveEvidence": {},
    "LiveVerdict": {"state": "verdict_state", "basis": "verdict_basis", "reason": "verdict_refusal"},
    "LiveEta": {"basis": "eta_basis", "reason": "eta_refusal"},
    "LiveDecision": {"kind": "decision_kind"},
    "LiveNeedsYou": {"reason": "needs_you_reason"},
    "LiveFile": {"role": "plain_role"},
    "LiveMap": {},
    "LiveFrame": {"kind": "frame_kind"},
    "LiveSample": {},
    "LiveName": {},
    "LiveNames": {},
    "LiveState": {},
}


class LiveActivity(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: str
    role: str
    attempt: int
    since_s: int
    files: int
    calls: int
    file_id: Hex16 | None = None

    @field_validator("kind", "role")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveEvidence(BaseModel):
    model_config = ConfigDict(extra="forbid")

    window_calls: int
    errors_now: int
    errors_before: int
    new_files: int
    checkpoints: int
    repeats: int
    churn_writes: int
    fail_run: int
    blind_edits: int
    stuck_s: int
    files_changed: int
    commits: int
    background: int


class LiveVerdict(BaseModel):
    model_config = ConfigDict(extra="forbid")

    state: str | None = None
    basis: str | None = None
    reason: str | None = None
    file_id: Hex16 | None = None
    evidence: LiveEvidence

    @field_validator("state", "basis", "reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveEta(BaseModel):
    model_config = ConfigDict(extra="forbid")

    elapsed_s: int | None = None
    typical_s: int | None = None
    p25_s: int | None = None
    p75_s: int | None = None
    remaining_s: int | None = None
    n: int | None = None
    needed: int
    unattended: bool
    basis: str
    reason: str | None = None

    @field_validator("basis", "reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: str
    ts: float
    event_n: int
    count: int

    @field_validator("kind")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveNeedsYou(BaseModel):
    model_config = ConfigDict(extra="forbid")

    score: int = Field(ge=0, le=100)
    reason: str

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveFile(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: Hex16
    dir_id: Hex16 | None = None
    role: str
    depth: int | None = None
    reads: int
    edits: int
    last_read_ts: float | None = None
    last_edit_ts: float | None = None

    @field_validator("role")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveMap(BaseModel):
    model_config = ConfigDict(extra="forbid")

    files: list[LiveFile] = Field(max_length=400)
    files_total: int


class LiveFrame(BaseModel):
    model_config = ConfigDict(extra="forbid")

    t: int
    file_id: Hex16
    kind: str

    @field_validator("kind")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class LiveSample(BaseModel):
    model_config = ConfigDict(extra="forbid")

    events: int
    tool_calls: int
    segments: int
    tokens: int | None = None


class LiveName(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: Hex16
    name: str = Field(max_length=120)


class LiveNames(BaseModel):
    model_config = ConfigDict(extra="forbid")

    files: list[LiveName] = Field(max_length=400)


class LiveState(BaseModel):
    model_config = ConfigDict(extra="forbid")

    live_version: int
    computed_at: AwareDatetime
    activity: LiveActivity | None = None
    verdict: LiveVerdict
    eta: LiveEta
    decisions: list[LiveDecision] = Field(max_length=4)
    needs_you: LiveNeedsYou
    map: LiveMap | None = None
    timelapse: list[LiveFrame] | None = Field(default=None, max_length=600)
    sample: LiveSample
