# GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT.
"""A project demo's presign request, server side (`POST /v1/projects/{key}/media:presign`, default off).

PROJECT DEMOS (docs/demos.md). The stills and the one short video of a project, made on the Mac by `python -m capture demo`.
Nothing leaves by default. Opt in per project and per publish: `python -m capture demo --publish` prints how many files and how many
bytes it will send and waits for a yes. Owner only, whatever the session sharing settings; never in a post, feed, share, push or
activity. The phone reads them through short lived links or the API's own bearer check, never a public URL. Deleting a demo deletes
its objects and rows in one request, and deleting the account or excluding the repository deletes them too.

`extra="forbid"` at every level, the enums and the numeric bounds are this door's half. The
other half is `server/builder/project_media.py presign_refusal`, which holds the content type
to its kind and its size cap, a video to its length and an image to none, and the label to
MEDIA_LABEL_PATTERN and the word length, before anything is stored or signed.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

Hex16 = Annotated[str, Field(pattern=r"^[0-9a-f]{16}$")]

MEDIA_ROUTE = "POST /v1/projects/{key}/media:presign"

#: Every content type a presign may name: its kind, and the most bytes one file of it may be.
MEDIA_CONTENT_TYPES: dict[str, dict] = {
    "image/png": {"kind": "image", "max_bytes": 6291456},
    "image/jpeg": {"kind": "image", "max_bytes": 6291456},
    "video/mp4": {"kind": "video", "max_bytes": 41943040},
}

#: Counts per publish, the longest video in ms, the largest side in pixels, the longest word
#: of a label in characters.
MEDIA_CAPS: dict[str, int] = {
    "images": 8,
    "videos": 1,
    "video_ms": 31000,
    "pixels": 8192,
    "label_word": 24,
}

#: Character caps by size class; the document's `max` on a string field names one of these.
MEDIA_MAX_LENGTHS: dict[str, int] = {
    "label": 80,
}

#: The characters a label may carry, whole: letters A to Z and a to z, digits, the space and , . ' ( ) : ? ! & only, at least one letter, no word over 24 characters, no dash of any kind and no hyphen.
MEDIA_LABEL_PATTERN = "^[A-Za-z0-9 ,.'():?!&]+$"
MEDIA_LABEL_RULE = "letters A to Z and a to z, digits, the space and , . ' ( ) : ? ! & only, at least one letter, no word over 24 characters, no dash of any kind and no hyphen"

#: Legal values for every enum, in contract order. Named for this module; the validators
#: below read these two tables by name.
MEDIA_ENUM_VALUES: dict[str, list[str]] = {
    "media_kind": ["image", "video"],
    "media_content_type": ["image/png", "image/jpeg", "video/mp4"],
    "media_source": ["capture", "checkout", "transcript", "previous"],
    "poster_content_type": ["image/jpeg", "image/png"],
}

#: Which fields of which model carry which enum, read by the validators below.
MEDIA_ENUM_FIELDS: dict[str, dict[str, str]] = {
    "MediaPoster": {"content_type": "poster_content_type"},
    "ProjectMediaPresign": {"kind": "media_kind", "content_type": "media_content_type", "source": "media_source"},
}


class MediaPoster(BaseModel):
    model_config = ConfigDict(extra="forbid")

    content_type: str
    bytes: int = Field(ge=1, le=6291456)

    @field_validator("content_type")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = MEDIA_ENUM_VALUES[MEDIA_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ProjectMediaPresign(BaseModel):
    model_config = ConfigDict(extra="forbid")

    publish_id: Hex16
    kind: str
    content_type: str
    bytes: int = Field(ge=1, le=41943040)
    width: int = Field(ge=1, le=8192)
    height: int = Field(ge=1, le=8192)
    duration_ms: int | None = Field(default=None, ge=1, le=31000)
    position: int = Field(ge=0, le=63)
    label: str = Field(max_length=80)
    source: str
    poster: MediaPoster | None = None

    @field_validator("kind", "content_type", "source")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = MEDIA_ENUM_VALUES[MEDIA_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v
