"""GENERATED by scripts/gen_tokens.py from design/tokens.json. DO NOT EDIT."""

#: The dark surfaces, as the phone's dark scheme draws them.
GROUND = "#141210"
CARD = "#1E1B18"
TEXT = "#F5F1EA"
TEXT_DIM = "#A8A29A"

#: Each hue's ink on the dark ground, and its partner (the deep tone).
HUES: dict[str, tuple[str, str]] = {
    "amber": ("#FFB300", "#D07506"),
    "brass": ("#ECE659", "#CA9E09"),
    "tide": ("#6CD9F1", "#0E86AD"),
    "cobalt": ("#53A3F2", "#417ACC"),
    "iris": ("#A670F3", "#7658CB"),
    "heather": ("#EAB8FF", "#9C68B0"),
    "orchid": ("#F54BB8", "#BF3A90"),
    "coral": ("#FCA0A6", "#D36D86"),
    "ember": ("#F9833E", "#D85A05"),
}

#: tokens.json dither.bayer8, the band's threshold table, row by row.
BAYER8: list[list[int]] = [
    [0, 32, 8, 40, 2, 34, 10, 42],
    [48, 16, 56, 24, 50, 18, 58, 26],
    [12, 44, 4, 36, 14, 46, 6, 38],
    [60, 28, 52, 20, 62, 30, 54, 22],
    [3, 35, 11, 43, 1, 33, 9, 41],
    [51, 19, 59, 27, 49, 17, 57, 25],
    [15, 47, 7, 39, 13, 45, 5, 37],
    [63, 31, 55, 23, 61, 29, 53, 21],
]
