# GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT.
"""The quotes document, server side (`PUT /v1/profile/quotes`, default off).

THE SECOND OPT-IN EXCEPTION (v4). Up to three prompts, verbatim, for the Wrapped cards that quote you. Off until BOTH Settings on the phone
and --quotes on the machine say yes. Masked, identifier filtered twice. Owner only; never in a post, feed, share, push or activity. Off deletes.

`extra="forbid"` at every level and the 160 character cap are this door's half. The other
half is `server/builder/quotes.py quotes_gate`, which re-runs the machine's own mask and
identifier filter on every quote before anything is stored.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]

#: Character caps by size class; the document's `max` on a string field names one of these.
QUOTES_MAX_LENGTHS: dict[str, int] = {
    "quote": 160,
}

#: Legal values for every enum, in contract order. Named for the emitter in
#: scripts/gen_analysis.py, whose validators read these two tables by name.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "quote_card": ["go_to_prompt", "crash_out", "cryptic_prompt"],
}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "QuoteWire": {"card": "quote_card"},
    "QuotesUpload": {},
}


class QuoteWire(BaseModel):
    model_config = ConfigDict(extra="forbid")

    card: str
    text: str = Field(max_length=160)
    client_session_id: Sha256Hex
    sent_at: AwareDatetime
    seconds_in: int
    tool_calls_after: int | None = None
    corrected: bool | None = None

    @field_validator("card")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class QuotesUpload(BaseModel):
    model_config = ConfigDict(extra="forbid")

    quotes_version: int
    generated_at: AwareDatetime
    quotes: list[QuoteWire] = Field(max_length=3)
