# GENERATED by scripts/gen_report.py from spec/report.v1.json — DO NOT EDIT.
"""The builder report, server side.

`extra="forbid"` and the bounds below are the whole of the enforcement. Unlike the
narrative and the session analysis there is no schema on the other end that half-enforced
this already: the document is computed by `analysis/report.py`, so a field it grows
without the spec growing it is caught HERE, at the door, as a 422 rather than as a column
of nulls on somebody's phone.

The server does NOT compute this document and cannot: its blocks rest on subagent sidecar
transcripts, shell command text, prompt text and git history, none of which leave the
machine (privacy/upload-contract.json). It validates and stores.

Inside the five version 2 blocks (wrapped, money, burn, vocab, stack) and the version 3
projects block there is no string field at all. Every value the door accepts there is an
enum from the tables below, a number, a clock or a repository key, so a sentence, a quote,
a path or a repository NAME in one of them is a 422: a key is `Sha256Hex`, 64 lowercase
hex characters, and no name has that shape.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

REPORT_VERSION = 3

#: A repository key: the salted hash every session upload carries as `repo_hash`.
Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]

#: Character caps by size class; the spec's `max` on a string field names one of these.
REPORT_MAX_LENGTHS: dict[str, int] = {
    "label": 80,
    "reason": 200,
}

#: Legal values for every enum, in spec order. Named for the emitter in
#: scripts/gen_analysis.py, which writes validators that read these two tables by name;
#: renaming either here is a NameError at import, not a lint warning.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {
    "trend_direction": ["up", "down", "steady"],
    "agent_type": ["general-purpose", "Explore", "Plan", "fork", "workflow-subagent", "statusline-setup", "output-style-setup", "claude-code-guide", "unknown", "custom"],
    "wrapped_card": ["builder_type", "shipped", "work_style", "longest_session", "agents_at_once", "go_to_prompt", "streak", "change_course", "crash_out", "prompt_length", "deep_sessions", "time_put_in", "cryptic_prompt", "prompts_per_session", "kind_of_work"],
    "wrapped_unit": ["archetype", "lines", "style", "seconds", "sessions", "sends", "days", "share", "score", "words", "hours", "prompts_per_session", "kind"],
    "wrapped_basis": ["archetype_rules", "project_edit_tools_and_credited_shell_writes", "edit_tools_only", "uploaded_agent_lines", "absent", "autonomy_then_prompts_then_steer", "attended_seconds_rank", "sweep_over_first_to_last_event", "normalized_prompt_text_across_sessions", "days_with_a_commit_and_an_attended_session", "interrupts_and_correction_markers", "profanity_caps_punctuation_markers", "words_per_prompt", "attended_sessions_over_an_hour", "active_seconds", "vowelless_runs", "prompts_over_attended_sessions", "commit_subject_labels", "lines_by_file_role", "commit_subject_labels_then_lines_by_file_role"],
    "wrapped_value": ["architect", "velocity_machine", "quality_guardian", "night_owl", "director", "skeptic", "generalist", "hand_off", "dialogue", "steering", "one_shot", "feature", "fix", "refactor", "docs", "test", "chore", "perf", "style", "build", "revert", "source", "config", "migration", "dependency", "unknown"],
    "wrapped_refusal": ["no_sessions", "below_session_floor", "below_attended_floor", "below_prompt_floor", "below_own_words_floor", "no_prompt_text", "no_archetype_metric", "no_line_counts", "no_lines_attributed", "no_presence", "no_events", "no_repeated_prompt", "no_commit_history", "no_crash_out", "no_cryptic_prompt", "neither_kind_basis"],
    "archetype": ["architect", "velocity_machine", "quality_guardian", "night_owl", "director", "skeptic"],
    "archetype_metric": ["planning_ratio", "code_velocity", "test_runs_per_hour", "night_share", "autonomy_score", "steer_rate"],
    "commits_basis": ["git_log_distinct_commits"],
    "kind_refusal": ["no_subjects", "too_few_labelled", "low_label_coverage"],
    "commit_kind": ["feature", "fix", "refactor", "docs", "test", "chore", "perf", "style", "build", "revert"],
    "plain_role": ["test", "source", "config", "docs", "migration", "style", "build", "dependency", "unknown"],
    "money_basis": ["anthropic_api_list_price", "stale_prices"],
    "money_refusal": ["tokens_not_reported", "model_not_in_price_table"],
    "priced_model": ["claude-fable-5-1", "claude-mythos-5-1", "claude-fable-5", "claude-opus-5", "claude-opus-4-8", "claude-opus-4-7", "claude-opus-4-6", "claude-sonnet-5", "claude-sonnet-4-6", "claude-haiku-4-5"],
    "lines_basis": ["project_edit_tools_and_credited_shell_writes", "edit_tools_only", "uploaded_agent_lines", "absent"],
    "burn_cause": ["context_replay", "subagent_fanout", "error_loop", "repeated_call", "file_churn", "compaction", "investigated"],
    "burn_refusal": ["no_token_counts", "below_session_floor", "nothing_inside_segments", "not_segmented"],
    "vocab_term": ["commit", "branch", "merge", "rebase", "diff", "stash", "revert", "cherry_pick", "worktree", "pull_request", "force_push", "git_hook", "test_suite", "unit_test", "fixture", "snapshot_test", "end_to_end_test", "mock", "coverage", "type_check", "linter", "formatter", "ci", "dependency", "lockfile", "package_manager", "build", "bundler", "monorepo", "virtualenv", "env_var", "secret", "module", "api", "endpoint", "schema", "migration", "database", "query", "rls", "orm", "cache", "queue", "webhook", "cron_job", "auth", "jwt", "cors", "rate_limit", "container", "deploy", "server", "port", "process", "log", "stack_trace", "ssh", "shell_script", "makefile", "simulator", "subagent", "mcp", "web_search", "regex", "glob", "compaction", "heredoc", "patch", "symlink", "permissions", "feature_flag", "type_definitions", "monitoring", "routing_engine"],
    "vocab_refusal": ["no_events"],
    "stack_item": ["python", "typescript", "javascript", "swift", "kotlin", "go", "rust", "ruby", "java", "sql", "shell", "dart", "cpp", "csharp", "php", "html", "css", "react", "react_native", "expo", "nextjs", "fastapi", "django", "flask", "express", "tailwind", "vue", "svelte", "reanimated", "swiftui", "sqlalchemy", "react_native_maps", "postgres", "sqlite", "redis", "mongodb", "mysql", "docker", "railway", "vercel", "cloudflare", "aws", "github_actions", "eas", "fly", "prometheus", "grafana", "google_cloud", "pytest", "jest", "vitest", "bun_test", "playwright", "xctest", "cypress", "maestro", "locust", "git", "bun", "npm", "uv", "ruff", "eslint", "prettier", "make", "xcode", "android_sdk", "cocoapods", "alembic", "posthog", "stripe", "sentry", "openai", "anthropic", "supabase", "firebase", "mapbox", "google_maps", "valhalla", "transloc"],
    "stack_refusal": ["no_evidence"],
    "stack_category": ["language", "framework", "database", "infra", "testing", "tooling", "service"],
    "stack_evidence": ["manifest", "language", "command", "path", "tool"],
    "project_stage": ["starting", "active", "winding_down", "dormant"],
    "project_stage_rule": ["quiet_two_weeks", "quiet_a_week", "cadence_halved", "new_this_fortnight", "steady"],
    "momentum_refusal": ["below_session_floor", "nothing_before"],
    "clock_refusal": ["below_active_floor"],
    "quality_refusal": ["below_run_floor", "no_recovery"],
    "language_refusal": ["below_line_floor"],
    "cost_refusal": ["no_price", "unpriced_sessions", "commits_not_from_git", "below_commit_floor"],
    "comparison_metric": ["steer_rate", "autonomy_score", "test_runs_per_hour", "tool_calls_per_prompt", "prompts_per_session", "code_velocity", "usd_per_active_hour", "first_try_rate", "ships_rate", "night_share"],
    "comparison_refusal": ["fewer_than_two_projects", "within_noise", "floors_only"],
    "language": ["Python", "Swift", "TypeScript", "JavaScript", "Ruby", "Go", "Rust", "Java", "Kotlin", "Objective-C", "C header", "C", "C++", "C#", "PHP", "Scala", "Elixir", "Erlang", "Haskell", "Lua", "Dart", "R", "Julia", "Zig", "Shell", "PowerShell", "SQL", "HTML", "CSS", "Vue", "Svelte", "JSON", "YAML", "TOML", "INI", "XML", "Markdown", "reStructuredText", "Text", "Protobuf", "GraphQL", "Terraform", "Dockerfile", "Gradle", "Notebook", "Make", "CMake", "other"],
    "harness": ["claude_code", "cursor_ide", "cursor_agent", "codex", "gemini_cli", "cline", "opencode", "aider"],
}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {
    "ReportTrend": {"direction": "trend_direction"},
    "ReportAgentType": {"name": "agent_type"},
    "ReportAgents": {},
    "ReportDay": {},
    "ReportContributions": {},
    "ReportGreen": {},
    "ReportQuality": {},
    "ReportPrompting": {},
    "ReportLanguage": {},
    "ReportLanguages": {},
    "ReportCoverage": {},
    "ReportArchetypeScore": {"name": "archetype", "metric": "archetype_metric"},
    "ReportKindCount": {"kind": "commit_kind"},
    "ReportRoleLines": {"role": "plain_role"},
    "ReportWrappedExtras": {"metric": "archetype_metric", "commits_basis": "commits_basis", "commit_refusal": "kind_refusal"},
    "ReportWrappedCard": {"id": "wrapped_card", "value_id": "wrapped_value", "unit": "wrapped_unit", "basis": "wrapped_basis", "reason": "wrapped_refusal"},
    "ReportWrapped": {},
    "ReportTokens": {},
    "ReportModelCost": {"model": "priced_model"},
    "ReportMoney": {"basis": "money_basis", "reason": "money_refusal", "lines_basis": "lines_basis"},
    "ReportBurnCause": {"cause": "burn_cause"},
    "ReportBurn": {"reason": "burn_refusal"},
    "ReportTerm": {"id": "vocab_term"},
    "ReportVocab": {"reason": "vocab_refusal"},
    "ReportStackItem": {"id": "stack_item", "category": "stack_category", "evidence": "stack_evidence"},
    "ReportStack": {"reason": "stack_refusal"},
    "ReportProjectMomentum": {"direction": "trend_direction", "reason": "momentum_refusal"},
    "ReportProjectHistory": {"stage": "project_stage", "stage_rule": "project_stage_rule"},
    "ReportProjectClock": {"reason": "clock_refusal"},
    "ReportProjectQuality": {"reason": "quality_refusal"},
    "ReportProjectLanguage": {"language": "language"},
    "ReportProjectLanguages": {"reason": "language_refusal"},
    "ReportProjectDay": {},
    "ReportProjectCommits": {},
    "ReportProjectCostPerCommit": {"reason": "cost_refusal"},
    "ReportProjectHarness": {"harness": "harness"},
    "ReportProjectWindow": {},
    "ReportProject": {},
    "ReportProjectsUnresolved": {},
    "ReportProjectComparison": {"metric": "comparison_metric", "reason": "comparison_refusal"},
    "ReportProjects": {},
    "BuilderReport": {},
}


class ReportTrend(BaseModel):
    model_config = ConfigDict(extra="forbid")

    metric: str = Field(max_length=80)
    label: str = Field(max_length=80)
    before: float
    now: float
    move: float
    direction: str
    good: bool | None = None
    sessions_before: int
    sessions_now: int

    @field_validator("direction")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportAgentType(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    agents: int

    @field_validator("name")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportAgents(BaseModel):
    model_config = ConfigDict(extra="forbid")

    agents: int
    produced: int
    max_concurrent: int
    agent_seconds: float
    wall_seconds: float
    busy_seconds: float
    parallelism: float
    by_type: list[ReportAgentType] = Field(max_length=12)


class ReportDay(BaseModel):
    model_config = ConfigDict(extra="forbid")

    day: str = Field(max_length=80)
    assisted: int
    alone: int


class ReportContributions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    assisted: int
    alone: int
    active_days: int
    longest_streak: int
    current_streak: int
    days: list[ReportDay] = Field(max_length=400)


class ReportGreen(BaseModel):
    model_config = ConfigDict(extra="forbid")

    n: int
    median_seconds: int
    worst_seconds: int
    median_attempts: int


class ReportQuality(BaseModel):
    model_config = ConfigDict(extra="forbid")

    runs: int
    passed: int | None = None
    failed: int | None = None
    first_try_rate: float | None = None
    time_to_green: ReportGreen | None = None
    reason: str | None = Field(default=None, max_length=200)


class ReportPrompting(BaseModel):
    model_config = ConfigDict(extra="forbid")

    attempts: int
    clean: int | None = None
    costly: int | None = None
    clean_share: float | None = None
    reason: str | None = Field(default=None, max_length=200)


class ReportLanguage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(max_length=80)
    lines: int
    files: int
    share: float


class ReportLanguages(BaseModel):
    model_config = ConfigDict(extra="forbid")

    lines: int
    generated_lines_excluded: int
    languages: list[ReportLanguage] | None = Field(default=None, max_length=12)
    reason: str | None = Field(default=None, max_length=200)


class ReportCoverage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    window_days: int
    spans_days: int
    active_days: int
    sessions: int
    first_at: datetime | None = None
    last_at: datetime | None = None


class ReportArchetypeScore(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    metric: str
    value: float | None = None
    threshold: float | None = None
    score: float | None = Field(default=None, ge=0.0, le=1.0)

    @field_validator("name", "metric")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportKindCount(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: str
    commits: int

    @field_validator("kind")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportRoleLines(BaseModel):
    model_config = ConfigDict(extra="forbid")

    role: str
    lines: int

    @field_validator("role")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportWrappedExtras(BaseModel):
    model_config = ConfigDict(extra="forbid")

    confidence: float | None = Field(default=None, ge=0.0, le=1.0)
    metric: str | None = None
    metric_value: float | None = None
    metric_lower_bound: bool | None = None
    closest: ReportArchetypeScore | None = None
    runners_up: list[ReportArchetypeScore] | None = Field(default=None, max_length=2)
    commits: int | None = None
    assisted: int | None = None
    alone: int | None = None
    commits_basis: str | None = None
    autonomy: float | None = Field(default=None, ge=0.0, le=1.0)
    median_prompts: float | None = None
    steer_rate: float | None = None
    active_seconds: int | None = None
    started_at: datetime | None = None
    subagents_peak: int | None = None
    subagents: int | None = None
    sessions: int | None = None
    words: int | None = None
    commit_days: int | None = None
    attended_days: int | None = None
    both_days: int | None = None
    interrupts: int | None = None
    corrective_prompts: int | None = None
    median: float | None = None
    avg_minutes: int | None = None
    longest_minutes: int | None = None
    attended_hours: float | None = None
    attended_overlap_hours: float | None = None
    tool_calls_per_prompt: float | None = None
    kinds: list[ReportKindCount] | None = Field(default=None, max_length=10)
    classified: int | None = None
    coverage: float | None = Field(default=None, ge=0.0, le=1.0)
    role_lines: list[ReportRoleLines] | None = Field(default=None, max_length=9)
    commit_refusal: str | None = None
    lines: int | None = None
    lines_needed: int | None = None

    @field_validator("metric", "commits_basis", "commit_refusal")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportWrappedCard(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    value: float | None = None
    value_id: str | None = None
    unit: str
    basis: str
    n: int
    needed: int | None = None
    reason: str | None = None
    extras: ReportWrappedExtras

    @field_validator("id", "value_id", "unit", "basis", "reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportWrapped(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cards: list[ReportWrappedCard] = Field(max_length=15)
    prompts_with_text: int
    attended_sessions: int


class ReportTokens(BaseModel):
    model_config = ConfigDict(extra="forbid")

    input: int
    output: int
    cache_read: int
    cache_w5m: int
    cache_w1h: int


class ReportModelCost(BaseModel):
    model_config = ConfigDict(extra="forbid")

    model: str
    usd: float
    output_tokens: int
    sessions: int
    sessions_dominated: int
    commits: int
    usd_per_commit: float | None = None

    @field_validator("model")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportMoney(BaseModel):
    model_config = ConfigDict(extra="forbid")

    usd: float | None = None
    basis: str | None = None
    reason: str | None = None
    prices_read_on: datetime
    priced_sessions: int
    unpriced_sessions: int
    usd_per_active_hour: float | None = None
    usd_without_a_commit: float | None = None
    share_without_a_commit: float | None = Field(default=None, ge=0.0, le=1.0)
    tokens: ReportTokens | None = None
    token_sessions: int
    lines_added: int | None = None
    lines_removed: int | None = None
    lines_basis: str
    by_model: list[ReportModelCost] = Field(max_length=10)

    @field_validator("basis", "reason", "lines_basis")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportBurnCause(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cause: str
    tokens: int
    share: float = Field(ge=0.0, le=1.0)
    segments: int

    @field_validator("cause")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportBurn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    share: float | None = Field(default=None, ge=0.0, le=1.0)
    barren_tokens: int | None = None
    tokens: int | None = None
    unreadable_tokens: int | None = None
    sessions: int
    needed: int | None = None
    reason: str | None = None
    causes: list[ReportBurnCause] | None = Field(default=None, max_length=7)

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportTerm(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    count: int
    sessions: int
    first_seen: datetime

    @field_validator("id")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportVocab(BaseModel):
    model_config = ConfigDict(extra="forbid")

    terms: list[ReportTerm] = Field(max_length=80)
    locked: int | None = None
    catalog_size: int
    sessions: int
    shell_calls: int
    shell_calls_cut: int
    reason: str | None = None

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportStackItem(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    category: str
    evidence: str
    sessions: int
    first_seen: datetime | None = None

    @field_validator("id", "category", "evidence")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportStack(BaseModel):
    model_config = ConfigDict(extra="forbid")

    items: list[ReportStackItem] = Field(max_length=120)
    sessions: int
    manifests: int
    shell_calls: int
    shell_calls_cut: int
    reason: str | None = None

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectMomentum(BaseModel):
    model_config = ConfigDict(extra="forbid")

    days: int
    sessions: int
    sessions_before: int
    attended_seconds: int
    attended_seconds_before: int
    direction: str | None = None
    move: float | None = None
    reason: str | None = None
    needed: int | None = None

    @field_validator("direction", "reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectHistory(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sessions: int
    first_at: datetime
    last_at: datetime
    active_days: int
    spans_days: int
    active_seconds: int
    attended_seconds: int
    autonomous_seconds: int
    longest_streak_days: int | None = None
    current_streak_days: int | None = None
    days_since_last: int
    age_days: int
    days_built_recent: int
    days_built_before: int
    stage: str
    stage_rule: str
    momentum: ReportProjectMomentum

    @field_validator("stage", "stage_rule")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectClock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    peak_hour: int | None = Field(default=None, ge=0, le=23)
    reason: str | None = None
    active_minutes: int
    needed_minutes: int | None = None

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectQuality(BaseModel):
    model_config = ConfigDict(extra="forbid")

    runs: int
    passed: int | None = None
    failed: int | None = None
    first_try_rate: float | None = Field(default=None, ge=0.0, le=1.0)
    time_to_green: ReportGreen | None = None
    reason: str | None = None
    needed: int | None = None

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectLanguage(BaseModel):
    model_config = ConfigDict(extra="forbid")

    language: str
    lines: int
    files: int
    share: float = Field(ge=0.0, le=1.0)

    @field_validator("language")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectLanguages(BaseModel):
    model_config = ConfigDict(extra="forbid")

    lines: int
    generated_lines_excluded: int
    languages: list[ReportProjectLanguage] | None = Field(default=None, max_length=9)
    reason: str | None = None
    needed: int | None = None

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectDay(BaseModel):
    model_config = ConfigDict(extra="forbid")

    day: datetime
    assisted: int
    alone: int


class ReportProjectCommits(BaseModel):
    model_config = ConfigDict(extra="forbid")

    assisted: int
    alone: int
    active_days: int
    longest_streak: int
    current_streak: int
    days: list[ReportProjectDay] = Field(max_length=400)


class ReportProjectCostPerCommit(BaseModel):
    model_config = ConfigDict(extra="forbid")

    usd: float | None = None
    commits: int
    unpriced_sessions: int
    reason: str | None = None
    needed: int | None = None

    @field_validator("reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectHarness(BaseModel):
    model_config = ConfigDict(extra="forbid")

    harness: str
    sessions: int
    active_seconds: int

    @field_validator("harness")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjectWindow(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sessions: int
    first_at: datetime
    last_at: datetime
    active_days: int
    active_seconds: int
    attended_seconds: int
    autonomous_seconds: int
    share_of_attended: float | None = Field(default=None, ge=0.0, le=1.0)
    clock: ReportProjectClock
    cards: list[ReportWrappedCard] = Field(max_length=12)
    scores: list[ReportArchetypeScore] = Field(max_length=6)
    quality: ReportProjectQuality
    languages: ReportProjectLanguages
    commits: ReportProjectCommits | None = None
    money: ReportMoney
    usd_per_commit: ReportProjectCostPerCommit
    burn: ReportBurn
    stack: ReportStack
    agents: ReportAgents | None = None
    harnesses: list[ReportProjectHarness] = Field(max_length=8)


class ReportProject(BaseModel):
    model_config = ConfigDict(extra="forbid")

    key: Sha256Hex
    rank: int
    history: ReportProjectHistory
    window: ReportProjectWindow | None = None


class ReportProjectsUnresolved(BaseModel):
    model_config = ConfigDict(extra="forbid")

    sessions: int
    active_seconds: int
    attended_seconds: int
    history_sessions: int


class ReportProjectComparison(BaseModel):
    model_config = ConfigDict(extra="forbid")

    metric: str
    high: Sha256Hex | None = None
    low: Sha256Hex | None = None
    high_value: float | None = None
    low_value: float | None = None
    high_sessions: int | None = None
    low_sessions: int | None = None
    ratio: float | None = None
    gap: float | None = None
    projects: int
    needed: int | None = None
    reason: str | None = None

    @field_validator("metric", "reason")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = ANALYSIS_ENUM_VALUES[ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ReportProjects(BaseModel):
    model_config = ConfigDict(extra="forbid")

    window_days: int
    history_sessions: int
    history_first_at: datetime | None = None
    projects_total: int
    projects: list[ReportProject] = Field(max_length=20)
    unresolved: ReportProjectsUnresolved
    comparisons: list[ReportProjectComparison] = Field(max_length=10)


class BuilderReport(BaseModel):
    model_config = ConfigDict(extra="forbid")

    report_version: int
    generated_at: datetime
    window_days: int
    coverage: ReportCoverage | None = None
    trend_headline: str | None = Field(default=None, max_length=200)
    trends: list[ReportTrend] = Field(max_length=24)
    agents: ReportAgents | None = None
    contributions: ReportContributions | None = None
    quality: ReportQuality | None = None
    prompting: ReportPrompting | None = None
    languages: ReportLanguages | None = None
    wrapped: ReportWrapped | None = None
    money: ReportMoney | None = None
    burn: ReportBurn | None = None
    vocab: ReportVocab | None = None
    stack: ReportStack | None = None
    projects: ReportProjects | None = None
