# GENERATED by scripts/gen_shipkit.py from spec/shipkit.v1.json — DO NOT EDIT.
"""The ship kit at the server's door (docs/ship-kit.md): a kit document, the presign of one kit
file, and the phone's request for a demo.

`extra="forbid"` and the bounds are this door's half. The rest is routes/shipkit.py: a file's
content type to its slot and its size cap, a video to its length, the label to the demo
channel's rule, and a caption to its platform's limit.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{64}$")]
Hex16 = Annotated[str, Field(pattern=r"^[0-9a-f]{16}$")]

SHIPKIT_VERSION = 1

SHIPKIT_MAX_LENGTHS: dict[str, int] = {
    "tweet": 280,
    "post": 3000,
    "subject": 120,
    "label": 80,
    "name": 60,
    "why": 300,
}

SHIPKIT_CAPS: dict[str, int] = {
    "videos": 4,
    "loops": 1,
    "stills": 8,
    "framed_stills": 8,
    "before_after": 4,
    "app_store_each": 8,
    "video_bytes": 41943040,
    "image_bytes": 6291456,
    "gif_bytes": 8388608,
    "video_ms": 31000,
    "pixels": 8192,
}

PLATFORM_LIMITS: dict[str, int] = {
    "x": 280,
    "bluesky": 300,
    "threads": 500,
    "linkedin": 3000,
    "instagram": 2200,
    "tiktok": 2200,
}

SHIPKIT_ENUM_VALUES: dict[str, list[str]] = {
    "platform": ["x", "linkedin", "threads", "instagram", "tiktok", "bluesky"],
    "kit_format": ["vertical", "feed", "landscape", "square"],
    "kit_slot": ["video_vertical", "video_feed", "video_landscape", "video_square", "loop", "still", "framed_still", "before_after", "app_store_iphone", "app_store_ipad"],
    "kit_content_type": ["image/png", "image/jpeg", "image/gif", "video/mp4"],
    "caption_source": ["model", "template"],
    "request_status": ["queued", "claimed", "done", "failed", "cancelled"],
    "request_refusal": ["not_runnable", "capture_failed", "privacy_refused", "kit_failed", "no_checkout", "excluded", "cancelled_on_mac"],
    "kit_refusal": ["device_aspect_mismatch", "blank_segment", "render_failed", "invented_number", "names_a_repository", "over_limit", "no_model", "loop_too_large", "aspect_too_far", "no_ipad_capture", "not_an_ios_app", "no_previous_demo", "no_video", "privacy_not_checked"],
    "queue_skip": ["not_a_repository", "excluded", "nothing_shipped", "not_demoable", "already_filmed", "already_queued"],
    "hue": ["tide", "ember", "iris", "brass", "orchid", "cobalt", "coral", "heather", "amber"],
}

SHIPKIT_ENUM_FIELDS: dict[str, dict[str, str]] = {
    "Caption": {"platform": "platform"},
    "ShareCopy": {},
    "KitCaption": {"platform": "platform", "source": "caption_source"},
    "Refused": {"code": "kit_refusal"},
    "KitPresign": {"slot": "kit_slot", "content_type": "kit_content_type"},
    "KitDocument": {"hue": "hue"},
    "DemoRequestIn": {"hue": "hue"},
    "DemoRequestFinish": {"status": "request_status", "refusal": "request_refusal"},
}


class Caption(BaseModel):
    model_config = ConfigDict(extra="forbid")

    platform: str
    text: str = Field(max_length=3000)
    thread: list[Annotated[str, Field(max_length=280)]] = Field(max_length=5)

    @field_validator("platform")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class ShareCopy(BaseModel):
    model_config = ConfigDict(extra="forbid")

    captions: list[Caption] = Field(max_length=6)


class KitCaption(BaseModel):
    model_config = ConfigDict(extra="forbid")

    platform: str
    text: str = Field(max_length=3000)
    thread: list[Annotated[str, Field(max_length=280)]] = Field(max_length=5)
    source: str

    @field_validator("platform", "source")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class Refused(BaseModel):
    model_config = ConfigDict(extra="forbid")

    what: str = Field(max_length=60)
    code: str

    @field_validator("code")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class KitPresign(BaseModel):
    model_config = ConfigDict(extra="forbid")

    publish_id: Hex16
    slot: str
    content_type: str
    bytes: int = Field(ge=1, le=41943040)
    width: int = Field(ge=1, le=8192)
    height: int = Field(ge=1, le=8192)
    duration_ms: int | None = Field(default=None, ge=1, le=31000)
    position: int = Field(ge=0, le=63)
    label: str | None = Field(default=None, max_length=80)

    @field_validator("slot", "content_type")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class KitDocument(BaseModel):
    model_config = ConfigDict(extra="forbid")

    shipkit_version: int
    publish_id: Hex16
    device: str = Field(max_length=60)
    hue: str
    captions: list[KitCaption] = Field(max_length=6)
    changelog: list[Annotated[str, Field(max_length=120)]] = Field(max_length=30)
    refused: list[Refused] = Field(max_length=20)

    @field_validator("hue")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DemoRequestIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    project_key: Sha256Hex
    hue: str | None = None

    @field_validator("hue")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class DemoRequestFinish(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: str
    refusal: str | None = None

    @field_validator("status", "refusal")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = SHIPKIT_ENUM_VALUES[SHIPKIT_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v
