# GENERATED by scripts/gen_trailer.py from spec/trailer.v1.json — DO NOT EDIT.
"""The trailer at the server's door (docs/trailers.md): a note's answer from the Mac (the new
version, its changes as codes, or a refusal code). The note itself is the owner's words and is
bounded by `TRAILER_MAX_LENGTHS["note"]` in routes/trailer.py.

`extra="forbid"` and the bounds are this door's half; a change's sentence is the phone's to say.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

TRAILER_VERSION = 1

TRAILER_MAX_LENGTHS: dict[str, int] = {
    "title": 60,
    "line": 90,
    "cta": 60,
    "note": 500,
    "value": 90,
    "subject": 120,
}

TRAILER_ENUM_VALUES: dict[str, list[str]] = {
    "scene_kind": ["open", "screens", "figure", "days", "changelog", "stack", "end"],
    "figure": ["commits", "sessions", "hours", "lines_added", "days_built", "streak_days"],
    "mood": ["quiet", "drive", "none"],
    "camera": ["still", "drift", "lean"],
    "transition": ["fluid", "morph", "cut"],
    "arrival": ["rain", "scan", "ripple", "rise", "interlace", "blocks", "spiral", "wipe"],
    "text_source": ["facts", "person", "model"],
    "hue": ["amber", "brass", "tide", "cobalt", "iris", "heather", "orchid", "coral", "ember"],
    "creature": ["bit", "cat", "dog", "fox", "owl", "bee", "whale", "octopus", "crab"],
    "note_status": ["queued", "claimed", "done", "failed", "cancelled"],
    "change_code": ["seconds", "pace", "hue", "title", "line", "cta", "creature", "mood", "camera", "transition", "scene_added", "scene_removed", "scene_moved", "figure", "screens", "first", "reverted", "rerendered"],
    "note_refusal": ["not_understood", "no_model", "invented_number", "names_a_repository", "needs_new_capture", "over_limit", "nothing_to_change", "no_such_version", "render_failed", "no_trailer", "no_node", "no_demo"],
}

TRAILER_ENUM_FIELDS: dict[str, dict[str, str]] = {
    "Cut": {"hue": "hue", "creature": "creature", "mood": "mood", "transition": "transition"},
    "Text": {"source": "text_source"},
    "Scene": {"kind": "scene_kind", "arrival": "arrival", "figure": "figure", "camera": "camera"},
    "Change": {"code": "change_code"},
    "CutEdit": {"refusal": "note_refusal"},
}

#: A refusal's sentence, for the words a push about a note carries.
TRAILER_REFUSALS: dict[str, str] = {
    "not_understood": "that note did not ask for a change the trailer can make; try the length, the pace, the colour, the words or the order",
    "no_model": "only the simple changes work without claude on your Mac: the length, the pace, the colour, the words and the order",
    "invented_number": "the change would have put a number on screen your project never gave, so it was not made",
    "names_a_repository": "the change would have named a private repository on screen, so it was not made",
    "needs_new_capture": "that needs new screens filmed; ask for a new demo and the trailer will be cut from it",
    "over_limit": "those words run past what fits on screen, so they were not changed",
    "nothing_to_change": "the trailer already does that",
    "no_such_version": "there is no version with that number",
    "render_failed": "the new cut could not be rendered, so the last version stays",
    "no_trailer": "this project has no trailer yet; it is cut from the project's demo",
    "no_node": "cutting a trailer needs Node 22.18 or later on your Mac",
    "no_demo": "this project has no demo to cut a trailer from yet",
}

# `Annotated` and `Field` are what a bounded list of strings would need; kept importable.
_ = (Annotated, Field)


class Cut(BaseModel):
    model_config = ConfigDict(extra="forbid")

    version: int = Field(ge=1, le=1000)
    seconds: float
    pace: float
    hue: str
    creature: str
    mood: str
    transition: str
    title: Text
    line: Text | None = None
    cta: Text | None = None
    scenes: list[Scene] = Field(max_length=10)

    @field_validator("hue", "creature", "mood", "transition")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = TRAILER_ENUM_VALUES[TRAILER_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class Text(BaseModel):
    model_config = ConfigDict(extra="forbid")

    text: str = Field(max_length=90)
    source: str

    @field_validator("source")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = TRAILER_ENUM_VALUES[TRAILER_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class Scene(BaseModel):
    model_config = ConfigDict(extra="forbid")

    kind: str
    weight: float
    arrival: str
    figure: str | None = None
    beats: list[int] | None = Field(default=None, max_length=8)
    camera: str | None = None
    caption: Text | None = None

    @field_validator("kind", "arrival", "figure", "camera")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = TRAILER_ENUM_VALUES[TRAILER_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class Change(BaseModel):
    model_config = ConfigDict(extra="forbid")

    code: str
    before: str | None = Field(default=None, max_length=90)
    after: str | None = Field(default=None, max_length=90)

    @field_validator("code")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = TRAILER_ENUM_VALUES[TRAILER_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v


class CutEdit(BaseModel):
    model_config = ConfigDict(extra="forbid")

    cut: Cut | None = None
    changes: list[Change] = Field(max_length=12)
    refusal: str | None = None

    @field_validator("refusal")
    @classmethod
    def _validate_enum(cls, v, info):
        allowed = TRAILER_ENUM_VALUES[TRAILER_ENUM_FIELDS[cls.__name__][info.field_name]]
        if v is not None and v not in allowed:
            raise ValueError(
                '%s=%r is not one of %r' % (info.field_name, v, allowed)
            )
        return v
