# GENERATED by scripts/gen_trailer.py from spec/trailer.v1.json — DO NOT EDIT.
"""The trailer's enums, bounds and sentences, for the Mac (docs/trailers.md).

Nothing imported: capture is standard library only. The server builds its door from the same
spec (server/builder/trailer_spec.py), the phone its types (mobile/src/generated/trailer.ts), and
trailer/ (the renderer) reads spec/trailer.v1.json itself.
"""

from __future__ import annotations

TRAILER_VERSION = 1
FPS = 30
SECONDS: dict[str, float] = {"min": 8, "max": 40, "default": 20}
PACE: dict[str, float] = {"min": 0.7, "max": 1.4}
WEIGHT: dict[str, float] = {"min": 0.3, "max": 4}
SCENES_MAX = 10

#: Legal values for every enum, in spec order.
ENUMS: dict[str, list[str]] = {
    "scene_kind": ["open", "screens", "figure", "days", "changelog", "stack", "end"],
    "figure": ["commits", "sessions", "hours", "lines_added", "days_built", "streak_days"],
    "mood": ["quiet", "drive", "none"],
    "camera": ["still", "drift", "lean"],
    "transition": ["fluid", "morph", "cut"],
    "arrival": ["rain", "scan", "ripple", "rise", "interlace", "blocks", "spiral", "wipe"],
    "text_source": ["facts", "person", "model"],
    "hue": ["amber", "brass", "tide", "cobalt", "iris", "heather", "orchid", "coral", "ember"],
    "creature": ["bit", "cat", "dog", "fox", "owl", "bee", "whale", "octopus", "crab"],
    "note_status": ["queued", "claimed", "done", "failed", "cancelled"],
    "change_code": ["seconds", "pace", "hue", "title", "line", "cta", "creature", "mood", "camera", "transition", "scene_added", "scene_removed", "scene_moved", "figure", "screens", "first", "reverted", "rerendered"],
    "note_refusal": ["not_understood", "no_model", "invented_number", "names_a_repository", "needs_new_capture", "over_limit", "nothing_to_change", "no_such_version", "render_failed", "no_trailer", "no_node", "no_demo"],
}

#: Character caps by size class.
MAX_LENGTHS: dict[str, int] = {
    "title": 60,
    "line": 90,
    "cta": 60,
    "note": 500,
    "value": 90,
    "subject": 120,
}

#: Every refusal code's sentence: the words the Mac, the server and the phone all say.
REFUSALS: dict[str, str] = {
    "not_understood": "that note did not ask for a change the trailer can make; try the length, the pace, the colour, the words or the order",
    "no_model": "only the simple changes work without claude on your Mac: the length, the pace, the colour, the words and the order",
    "invented_number": "the change would have put a number on screen your project never gave, so it was not made",
    "names_a_repository": "the change would have named a private repository on screen, so it was not made",
    "needs_new_capture": "that needs new screens filmed; ask for a new demo and the trailer will be cut from it",
    "over_limit": "those words run past what fits on screen, so they were not changed",
    "nothing_to_change": "the trailer already does that",
    "no_such_version": "there is no version with that number",
    "render_failed": "the new cut could not be rendered, so the last version stays",
    "no_trailer": "this project has no trailer yet; it is cut from the project's demo",
    "no_node": "cutting a trailer needs Node 22.18 or later on your Mac",
    "no_demo": "this project has no demo to cut a trailer from yet",
}

#: Every change code's sentence, {before} and {after} filled with the change's own values.
CHANGES: dict[str, str] = {
    "seconds": "{before} s became {after} s",
    "pace": "the pace went from {before} to {after}",
    "hue": "the colour is {after} now",
    "title": "the title reads “{after}”",
    "line": "the line under it reads “{after}”",
    "cta": "the last card says “{after}”",
    "creature": "the {after} is on it now",
    "mood": "the sound is {after} now",
    "camera": "the camera is {after} now",
    "transition": "scenes change by {after} now",
    "scene_added": "added the {after}",
    "scene_removed": "took out the {before}",
    "scene_moved": "the {after} comes earlier now",
    "figure": "the number is {after} now",
    "screens": "the screens hold {after} beats now",
    "first": "it opens on the {after} now",
    "reverted": "back to version {after}",
    "rerendered": "cut again from the latest demo",
}

#: How a coded value is said inside a change's sentence.
WORDS: dict[str, dict[str, str]] = {
    "scene_kind": {"open": "opening title", "screens": "screens", "figure": "number", "days": "days built", "changelog": "list of changes", "stack": "stack", "end": "end card"},
    "figure": {"commits": "commits", "sessions": "sessions", "hours": "hours with you there", "lines_added": "lines added", "days_built": "days built", "streak_days": "days in a row"},
    "mood": {"quiet": "quiet", "drive": "driving", "none": "off"},
    "camera": {"still": "still", "drift": "drifting", "lean": "leaning in"},
    "transition": {"fluid": "ink", "morph": "the band growing", "cut": "a straight cut"},
}
