# GENERATED by scripts/gen_drops.py from spec/drops.v1.json — DO NOT EDIT.
"""The drop wire's enums and caps, for the runner on the person's own machine.

The same tables `server/builder/drops_spec.py` builds its validators from and
`mobile/src/generated/drops.ts` exports, with nothing imported: `drops/` is standard library
only (see drops/__init__.py), and this is the file that keeps it that way.
"""

from __future__ import annotations

DROPS_VERSION = 1

#: Legal values for every enum, in spec order.
ENUMS: dict[str, list[str]] = {
    "drop_kind": ["skill", "technique", "project", "tool", "recipe", "unknown"],
    "move_kind": ["install", "apply", "scaffold", "evaluate", "card", "keep"],
    "move_target": ["new_project", "existing_repo", "this_machine", "none"],
    "source_kind": ["github", "npm", "pypi", "cargo", "homebrew", "mcp", "plugin_marketplace", "docs_url"],
    "effort": ["minutes", "an_hour", "a_session"],
    "platform": ["instagram", "tiktok", "youtube", "x", "reddit", "threads", "web"],
    "resolver": ["oembed", "yt_dlp", "opengraph", "shared_text"],
    "verify_state": ["verified", "unverified", "unchecked"],
    "found_by": ["caption", "search"],
    "drop_refusal": ["url_unsupported", "no_text", "private_or_gone", "not_about_building", "planner_unavailable", "planner_refused"],
    "move_refusal": ["source_unverified", "evidence_not_found", "no_repo_match"],
    "drop_status": ["waiting", "resolving", "planned", "refused", "archived"],
    "move_status": ["offered", "queued", "running", "done", "failed", "declined"],
}

#: Character caps by size class; every string on the wire names one of these.
MAX_LENGTHS: dict[str, int] = {
    "name": 80,
    "line": 200,
    "quote": 300,
    "ref": 140,
    "url": 500,
    "tag": 24,
    "step": 240,
    "qty": 40,
    "ingredient": 80,
}

DROP_KIND: tuple[str, ...] = tuple(ENUMS["drop_kind"])
MOVE_KIND: tuple[str, ...] = tuple(ENUMS["move_kind"])
MOVE_TARGET: tuple[str, ...] = tuple(ENUMS["move_target"])
SOURCE_KIND: tuple[str, ...] = tuple(ENUMS["source_kind"])
EFFORT: tuple[str, ...] = tuple(ENUMS["effort"])
PLATFORM: tuple[str, ...] = tuple(ENUMS["platform"])
RESOLVER: tuple[str, ...] = tuple(ENUMS["resolver"])
VERIFY_STATE: tuple[str, ...] = tuple(ENUMS["verify_state"])
FOUND_BY: tuple[str, ...] = tuple(ENUMS["found_by"])
DROP_REFUSAL: tuple[str, ...] = tuple(ENUMS["drop_refusal"])
MOVE_REFUSAL: tuple[str, ...] = tuple(ENUMS["move_refusal"])
DROP_STATUS: tuple[str, ...] = tuple(ENUMS["drop_status"])
MOVE_STATUS: tuple[str, ...] = tuple(ENUMS["move_status"])
