// GENERATED by scripts/gen_widget_creatures.py from mobile/src/pixel/animals.ts and
// sprites.ts. Do not edit: re-run the script, which also redraws Assets.xcassets.

enum CreatureArt {
  /// Every creature with images in the widget's Assets.xcassets, in the pack's order, then Bit.
  static let ids: [String] = ["crab", "octopus", "dog", "cat", "owl", "fox", "whale", "bee", "bit", "bit-sleeping"]
  /// Point sizes drawn. The grid lands on whole device pixels only at these.
  static let sizes: [Int] = [16, 32, 48, 64]
  static let prefix = "creature-"
  /// Empty grid columns left and right of each drawing. Every image keeps the full 16 cell
  /// frame so creatures line up with each other; a surface that must sit flush with text or
  /// snug to the camera trims these instead (`CreatureMark(trim:)`).
  static let insets: [String: (leading: Int, trailing: Int)] = ["crab": (0, 0), "octopus": (1, 1), "dog": (2, 2), "cat": (1, 2), "owl": (2, 2), "fox": (2, 2), "whale": (0, 0), "bee": (1, 1), "bit": (4, 4), "bit-sleeping": (4, 0)]
}
