// GENERATED by scripts/gen_tokens.py from design/tokens.json — DO NOT EDIT.
//
// The widget extension's colours: the Lock Screen, the Dynamic Island and the Home Screen widget.
// It also compiles into the main app (via _shared) for the ImageRenderer previews, where the
// widget's asset catalog colours would resolve to clear, so nothing here reads a colorset.
//
// Every value is Color(.sRGB, ...) from the token's sRGB hex. Two traps this avoids: SwiftUI's
// bare Color(red:green:blue:) is DISPLAY P3, and @bacons/apple-targets writes its colorsets as
// display-p3 from sRGB hex; either would make the widget visibly more saturated than the app.
//
// The spectrum (DESIGN-V2-COLOUR-MOTION.md 1): each session is drawn in its crew creature's hue
// (src/live/crew.ts decides which; the phone and the server's push both carry it as
// `creature`). On the dark ground a hue is its ink, as a mark and as a word; on the light widget
// a mark takes the 3:1 light tone and a word the 4.5:1 light text tone. The measurements beside
// each hue are this generator's, against the real grounds, and gen_tokens.py refuses a hue under
// any floor before it writes this file.

import SwiftUI

/// An sRGB colour from its three bytes. Never the bare Color(red:green:blue:), which is P3.
private func srgb(_ r: Double, _ g: Double, _ b: Double) -> Color {
  Color(.sRGB, red: r / 255, green: g / 255, blue: b / 255, opacity: 1)
}

enum BuilderPalette {
  // MARK: dark, the Lock Screen and the Dynamic Island in both appearances
  static let bg = srgb(0x14, 0x12, 0x10)  // #141210
  static let card = srgb(0x1E, 0x1B, 0x18)  // #1E1B18
  static let border = srgb(0x2F, 0x2B, 0x27)  // #2F2B27
  static let text = srgb(0xF5, 0xF1, 0xEA)  // #F5F1EA
  static let textDim = srgb(0xA8, 0xA2, 0x9A)  // #A8A29A
  static let textFaint = srgb(0x6B, 0x65, 0x5D)  // #6B655D
  static let amber = srgb(0xFF, 0xB3, 0x00)  // #FFB300, the brand: Bit's hue and the widget gallery's accent, never a session's
  static let add = srgb(0x7B, 0xC9, 0x6F)  // #7BC96F
  static let del = srgb(0xE5, 0x48, 0x4D)  // #E5484D
  /// Ink on a solid fill of any hue.
  static let onFill = srgb(0x1C, 0x19, 0x17)  // #1C1917

  /// One appearance's worth of tokens. Home Screen widgets render light and dark, so the widget
  /// reads `BuilderPalette.scheme(colorScheme)`; the Lock Screen and island are dark only.
  struct Scheme {
    let isDark: Bool
    let bg: Color
    let card: Color
    let border: Color
    let text: Color
    let textDim: Color
    let textFaint: Color
    /// Amber, the brand: Bit asleep on the idle widget. Never a session's colour.
    let accent: Color
    let add: Color
    let del: Color
    /// graph.levels, 0 (no time) to 5 (8h and over): the amber ramp, never GitHub green.
    let graph: [Color]

    /// A creature's hue in this appearance: `ink` for a mark, `text` for a word.
    func creature(_ id: String) -> Hue { BuilderPalette.creatureHue(id, dark: isDark) }
  }

  static let dark = Scheme(
    isDark: true,
    bg: srgb(0x14, 0x12, 0x10),  // #141210
    card: srgb(0x1E, 0x1B, 0x18),  // #1E1B18
    border: srgb(0x2F, 0x2B, 0x27),  // #2F2B27
    text: srgb(0xF5, 0xF1, 0xEA),  // #F5F1EA
    textDim: srgb(0xA8, 0xA2, 0x9A),  // #A8A29A
    textFaint: srgb(0x6B, 0x65, 0x5D),  // #6B655D
    accent: amber,
    add: srgb(0x7B, 0xC9, 0x6F),  // #7BC96F
    del: srgb(0xE5, 0x48, 0x4D),  // #E5484D
    graph: [
      srgb(0x22, 0x1F, 0x1C),  // #221F1C
      srgb(0x4A, 0x37, 0x14),  // #4A3714
      srgb(0x7A, 0x5A, 0x12),  // #7A5A12
      srgb(0xB3, 0x7E, 0x00),  // #B37E00
      srgb(0xE0, 0xA3, 0x00),  // #E0A300
      srgb(0xFF, 0xB3, 0x00),  // #FFB300
    ]
  )

  static let light = Scheme(
    isDark: false,
    bg: srgb(0xFB, 0xF9, 0xF5),  // #FBF9F5
    card: srgb(0xFF, 0xFF, 0xFF),  // #FFFFFF
    border: srgb(0xE7, 0xE3, 0xDC),  // #E7E3DC
    text: srgb(0x1C, 0x19, 0x17),  // #1C1917
    textDim: srgb(0x6B, 0x65, 0x5D),  // #6B655D
    textFaint: srgb(0xA8, 0xA2, 0x9A),  // #A8A29A
    accent: amber,
    add: srgb(0x2B, 0x7F, 0x3A),  // #2B7F3A
    del: srgb(0xC6, 0x2A, 0x2F),  // #C62A2F
    graph: [
      srgb(0xEF, 0xEB, 0xE4),  // #EFEBE4
      srgb(0xFF, 0xE7, 0xB0),  // #FFE7B0
      srgb(0xFF, 0xD2, 0x75),  // #FFD275
      srgb(0xFF, 0xB3, 0x00),  // #FFB300
      srgb(0xE0, 0x8A, 0x00),  // #E08A00
      srgb(0xB3, 0x6B, 0x00),  // #B36B00
    ]
  )

  static func scheme(_ colorScheme: ColorScheme) -> Scheme {
    colorScheme == .dark ? dark : light
  }

  // MARK: the spectrum

  enum HueName: String, CaseIterable {
    case amber, brass, tide, cobalt, iris, heather, orchid, coral, ember
  }

  /// One of the nine hues resolved for one appearance (`theme.ts` `Hue`).
  ///   ink      a mark: a creature, a ring, a capsule, the needs you dot. The dark ink on dark,
  ///            the 3:1 light mark tone on the light widget.
  ///   text     the hue as a word (13pt semibold and up): the dark ink on dark, the 4.5:1 light
  ///            text tone on light.
  ///   partner  the dither's middle tone; never text, never a creature on its own.
  ///   fill     a solid fill, the dark ink in both appearances, with `onFill` on it.
  struct Hue: Equatable {
    let name: HueName
    let ink: Color
    let text: Color
    let partner: Color
    let fill: Color
    let onFill: Color

    fileprivate init(_ name: HueName, dark: Bool, ink: Color, partner: Color,
                     light: Color, lightText: Color, lightPartner: Color) {
      self.name = name
      self.ink = dark ? ink : light
      self.text = dark ? ink : lightText
      self.partner = dark ? partner : lightPartner
      self.fill = ink
      self.onFill = BuilderPalette.onFill
    }
  }

  static func hue(_ name: HueName, dark: Bool = true) -> Hue {
    switch name {
    case .amber:
      // ink #FFB300: 10.4:1 on bg #141210, 9.5:1 on card, 9.7:1 under onFill.
      // light mark #BC8303: 3.1:1 on #FBF9F5; light text #976902: 4.6:1 on #FBF9F5, 4.8:1 on white.
      return Hue(.amber, dark: dark, ink: srgb(0xFF, 0xB3, 0x00), partner: srgb(0xD0, 0x75, 0x06),
                 light: srgb(0xBC, 0x83, 0x03), lightText: srgb(0x97, 0x69, 0x02), lightPartner: srgb(0xE8, 0xB4, 0x5E))
    case .brass:
      // ink #ECE659: 14.3:1 on bg #141210, 13.1:1 on card, 13.3:1 under onFill.
      // light mark #A68C03: 3.1:1 on #FBF9F5; light text #857000: 4.6:1 on #FBF9F5, 4.9:1 on white.
      return Hue(.brass, dark: dark, ink: srgb(0xEC, 0xE6, 0x59), partner: srgb(0xCA, 0x9E, 0x09),
                 light: srgb(0xA6, 0x8C, 0x03), lightText: srgb(0x85, 0x70, 0x00), lightPartner: srgb(0xD3, 0xBE, 0x66))
    case .tide:
      // ink #6CD9F1: 11.4:1 on bg #141210, 10.5:1 on card, 10.7:1 under onFill.
      // light mark #049BB3: 3.1:1 on #FBF9F5; light text #057C90: 4.7:1 on #FBF9F5, 4.9:1 on white.
      return Hue(.tide, dark: dark, ink: srgb(0x6C, 0xD9, 0xF1), partner: srgb(0x0E, 0x86, 0xAD),
                 light: srgb(0x04, 0x9B, 0xB3), lightText: srgb(0x05, 0x7C, 0x90), lightPartner: srgb(0x85, 0xCA, 0xDB))
    case .cobalt:
      // ink #53A3F2: 7.0:1 on bg #141210, 6.4:1 on card, 6.6:1 under onFill.
      // light mark #4192DF: 3.1:1 on #FBF9F5; light text #1F74BF: 4.6:1 on #FBF9F5, 4.9:1 on white.
      return Hue(.cobalt, dark: dark, ink: srgb(0x53, 0xA3, 0xF2), partner: srgb(0x41, 0x7A, 0xCC),
                 light: srgb(0x41, 0x92, 0xDF), lightText: srgb(0x1F, 0x74, 0xBF), lightPartner: srgb(0x8D, 0xC3, 0xFB))
    case .iris:
      // ink #A670F3: 5.5:1 on bg #141210, 5.1:1 on card, 5.2:1 under onFill.
      // light mark #A670F3: 3.2:1 on #FBF9F5; light text #8C55D6: 4.6:1 on #FBF9F5, 4.8:1 on white.
      return Hue(.iris, dark: dark, ink: srgb(0xA6, 0x70, 0xF3), partner: srgb(0x76, 0x58, 0xCB),
                 light: srgb(0xA6, 0x70, 0xF3), lightText: srgb(0x8C, 0x55, 0xD6), lightPartner: srgb(0xC5, 0xA3, 0xFF))
    case .heather:
      // ink #EAB8FF: 11.4:1 on bg #141210, 10.4:1 on card, 10.7:1 under onFill.
      // light mark #B178C8: 3.1:1 on #FBF9F5; light text #8D5FA0: 4.7:1 on #FBF9F5, 4.9:1 on white.
      return Hue(.heather, dark: dark, ink: srgb(0xEA, 0xB8, 0xFF), partner: srgb(0x9C, 0x68, 0xB0),
                 light: srgb(0xB1, 0x78, 0xC8), lightText: srgb(0x8D, 0x5F, 0xA0), lightPartner: srgb(0xD1, 0xAF, 0xE0))
    case .orchid:
      // ink #F54BB8: 5.9:1 on bg #141210, 5.4:1 on card, 5.5:1 under onFill.
      // light mark #F248B5: 3.1:1 on #FBF9F5; light text #D12198: 4.6:1 on #FBF9F5, 4.8:1 on white.
      return Hue(.orchid, dark: dark, ink: srgb(0xF5, 0x4B, 0xB8), partner: srgb(0xBF, 0x3A, 0x90),
                 light: srgb(0xF2, 0x48, 0xB5), lightText: srgb(0xD1, 0x21, 0x98), lightPartner: srgb(0xFF, 0x98, 0xD3))
    case .coral:
      // ink #FCA0A6: 9.5:1 on bg #141210, 8.7:1 on card, 8.9:1 under onFill.
      // light mark #D66E77: 3.1:1 on #FBF9F5; light text #AB575E: 4.7:1 on #FBF9F5, 4.9:1 on white.
      return Hue(.coral, dark: dark, ink: srgb(0xFC, 0xA0, 0xA6), partner: srgb(0xD3, 0x6D, 0x86),
                 light: srgb(0xD6, 0x6E, 0x77), lightText: srgb(0xAB, 0x57, 0x5E), lightPartner: srgb(0xEB, 0xAA, 0xAD))
    case .ember:
      // ink #F9833E: 7.4:1 on bg #141210, 6.8:1 on card, 6.9:1 under onFill.
      // light mark #E06C23: 3.2:1 on #FBF9F5; light text #B95201: 4.7:1 on #FBF9F5, 4.9:1 on white.
      return Hue(.ember, dark: dark, ink: srgb(0xF9, 0x83, 0x3E), partner: srgb(0xD8, 0x5A, 0x05),
                 light: srgb(0xE0, 0x6C, 0x23), lightText: srgb(0xB9, 0x52, 0x01), lightPartner: srgb(0xFB, 0xA7, 0x7B))
    }
  }

  /// spectrum.creature: the hue each creature wears. Bit, Bit asleep and an id this build does
  /// not know are Bit's amber; no session ever wears it (spectrum.crew.ring has no Bit).
  static func creatureHue(_ creature: String, dark: Bool = true) -> Hue {
    switch creature {
    case "cat": return hue(.orchid, dark: dark)
    case "dog": return hue(.cobalt, dark: dark)
    case "fox": return hue(.ember, dark: dark)
    case "owl": return hue(.heather, dark: dark)
    case "bee": return hue(.brass, dark: dark)
    case "whale": return hue(.tide, dark: dark)
    case "octopus": return hue(.iris, dark: dark)
    case "crab": return hue(.coral, dark: dark)
    default: return hue(.amber, dark: dark)
    }
  }

  /// spectrum.crew.ring, the eight a session's creature is hashed onto (the rule is the phone's,
  /// `src/live/crew.ts`; the widget only draws what it is handed).
  static let crewRing: [String] = ["fox", "whale", "bee", "octopus", "crab", "dog", "cat", "owl"]

  /// spectrum.drop: the hue a shared reel's KIND wears once the Mac has read it (`theme.ts`
  /// `dropHue`). nil for `unknown`, for a drop not read yet and for a kind this build does not
  /// know: those are drawn in the warm greys, so a colour always means something was understood.
  static func dropHue(_ kind: String?, dark: Bool = true) -> Hue? {
    switch kind {
    case "skill": return hue(.iris, dark: dark)
    case "technique": return hue(.tide, dark: dark)
    case "project": return hue(.orchid, dark: dark)
    case "tool": return hue(.brass, dark: dark)
    case "recipe": return hue(.coral, dark: dark)
    default: return nil
    }
  }

  /// spectrum.island: the colour a state springs to in the island (docs/motion.md), on the dark
  /// ground the island always is. A hue's ink, or the data token the state already means.
  enum IslandState: String, CaseIterable {
    case working, thinking, waiting, error, done, reading, sleep
  }

  static func islandInk(_ state: IslandState) -> Color {
    switch state {
    case .working: return hue(.cobalt).ink
    case .thinking: return hue(.iris).ink
    case .waiting: return hue(.amber).ink
    case .error: return srgb(0xE5, 0x48, 0x4D)  // data.del #E5484D
    case .done: return srgb(0x7B, 0xC9, 0x6F)  // data.add #7BC96F
    case .reading: return hue(.tide).ink
    case .sleep: return srgb(0x6B, 0x65, 0x5D)  // surface.textFaint #6B655D
    }
  }
}
