import React, { useCallback, useMemo } from 'react';
import { StyleSheet, Text, useWindowDimensions, View } from 'react-native';

import { Band, BandWords } from '../../src/insights/Band';
import { GrowBar } from '../../src/insights/Bars';
import { BandFigure, figure, GUTTER, Kicker, type, Words } from '../../src/insights/kit';
import { isRefused, REPORT_COMMAND } from '../../src/insights/model';
import { Num } from '../../src/insights/Num';
import { GROUND, SPECTRUM, type Hue, type HueName } from '../../src/insights/palette';
import { Block, Section } from '../../src/insights/reveal';
import { HarnessLogo } from '../../src/pixel/HarnessLogo';
import { StackChapterView } from '../../src/stack/Chapter';
import { StackHero } from '../../src/stack/Hero';
import { phoneTools, stackPage, toolsBand, toolsFromReport, type StackThing, type ToolsBand } from '../../src/stack/model';
import { harnessHue } from '../../src/theme';
import { useAccent } from '../../src/theme/accent';
import { ChapterPage } from '../../src/you/ChapterPage';
import type { ToolsMix } from '../../src/you/chapters';
import { useBuilderProfile, useToolsMix } from '../../src/you/hooks';
import { Arrive, ChapterSkeleton, ErrorChapter, RefusalChapter, SignedOutChapter, StaleLine } from '../../src/you/parts';

/**
 * Your stack: what the work is made of, every thing by its real mark.
 *
 *   01 the hero     a band in your creature's hue: the count of things huge, the creature
 *                   printed beside it, and the most used marks drifting along its foot on dark
 *                   tiles in their brands' colours (react-bits LogoLoop, whose own demo is a row
 *                   of Simple Icons). Under it, the bubbles of what you build with most, each
 *                   one's area its sessions; a tap says its story.
 *   the categories  languages, frameworks, databases, infrastructure, testing, tools, services:
 *                   each its own chapter in its own hue, its marks printed on its band, the things
 *                   a session used as tiles sized by their sessions (react-bits PixelCard, and
 *                   ClickSpark in the brand's colour on a tap), and one quiet sentence for what
 *                   only a manifest names.
 *   the tools       the coding tools your sessions came from, by the owner's own marks
 *                   (`HarnessLogo`), counted over the same sessions as every other count on the
 *                   page (the report's projects carry each project's tools); only a report
 *                   without them falls back to the sessions saved on this phone, and says so.
 *   the small print what the digest cut, and whose logos these are.
 *
 * The logos are Simple Icons', generated by `scripts/gen_stack_logos.py` into
 * `src/stack/stackLogos.ts`: 62 of the catalog's 80 things have a real one, the rest a
 * monogram. Only catalog items reach the phone (a manifest's package names never leave the Mac).
 * The report carries no sessions over time, so no line over time is drawn; how many of your
 * projects used a thing is said on a tap only once the report carries projects.
 */
export default function StackScreen() {
  const { width } = useWindowDimensions();
  const { load, refresh, refreshing } = useBuilderProfile();
  const phone = useToolsMix();
  const accent = useAccent();
  const data = load.kind === 'ready' ? load.data : null;
  const page = useMemo(() => (data ? stackPage(data, accent.name) : null), [data, accent.name]);
  const hero: Hue = useMemo(() => ({ ink: accent.ink, partner: accent.partner, light: accent.light }), [accent.ink, accent.partner, accent.light]);
  const body = page && !isRefused(page.body) ? page.body : null;

  // One source for every count on the page: the report's own sittings, tools included. The
  // phone's sessions only when the report carries no tools, and then said beside the report's.
  const fromReport = useMemo(() => (data ? toolsFromReport(data.report) : null), [data]);
  const tools = useMemo(() => fromReport ?? phoneTools(phone, body ? body.sessions : null), [fromReport, phone, body]);

  const hues = useMemo(() => new Map((body?.chapters ?? []).map((c) => [c.key as string, c.hue])), [body]);
  const hueOf = useCallback((t: StackThing): HueName => hues.get(t.category) ?? 'tide', [hues]);
  const band = useMemo(
    () => toolsBand(tools, [accent.name, ...(body?.chapters.slice(-1).map((c) => c.hue) ?? [])], (key) => harnessHue(key)?.name ?? null, fromReport ? 'report' : 'phone'),
    [tools, accent.name, body, fromReport],
  );
  const chapters = body?.chapters ?? [];

  return (
    <ChapterPage title="Your stack" chapters={chapters.length + 2} ready={page !== null && accent.ready} refreshing={refreshing} onRefresh={load.kind === 'signedOut' ? null : () => void refresh()}>
      {(stage) => (
        <>
          <View style={styles.lead}>
            {load.kind === 'signedOut' ? <SignedOutChapter what="stack" /> : null}
            {load.kind === 'error' ? <ErrorChapter message={load.message} onRetry={() => void refresh()} /> : null}
            {load.kind === 'ready' && load.stale ? <StaleLine stale={load.stale} /> : null}
          </View>

          {load.kind === 'loading' ? <ChapterSkeleton /> : null}

          {page && isRefused(page.body) ? (
            <RefusalChapter hue={hero} index="01" title="What it is made of" refusal={page.body.refusal} command={page.notSent ? REPORT_COMMAND : null} />
          ) : null}

          {body ? (
            <>
              <StackHero body={body} hue={hero} animal={accent.animal} width={width} hueOf={hueOf} />
              {chapters.map((c, i) => (stage >= i + 1 ? <StackChapterView key={c.key} chapter={c} width={width} /> : null))}
              {stage >= chapters.length + 1 && tools && band ? <Tools mix={tools} band={band} index={String(chapters.length + 2).padStart(2, '0')} width={width} /> : null}
              {stage >= chapters.length + 2 ? (
                <Section style={styles.small}>
                  <Block style={styles.smallBlock}>
                    {body.cutNote ? <Words style={type.meta}>{body.cutNote}</Words> : null}
                    <Words style={type.meta}>{body.credits}</Words>
                  </Block>
                </Section>
              ) : null}
            </>
          ) : null}
        </>
      )}
    </ChapterPage>
  );
}

/**
 * The coding tools, each by its real mark (the owner's logos, `HarnessLogo`), its sessions
 * counting up in its hue and its share of them as a bar that grows. A list, because here the list
 * is the content: open rows, no card round any of them.
 */
function Tools({ mix, band, index, width }: { mix: ToolsMix; band: ToolsBand; index: string; width: number }) {
  const inner = width - GUTTER * 2;
  return (
    <Section style={styles.chapter}>
      <Band hue={SPECTRUM[band.hue]} index={index} title="Written with">
        <View style={styles.side}>
          <BandFigure spec={band.total} width={inner * 0.42} max={104} min={52} delay={200} label={`${band.total.final} ${band.caption}`} />
          <View style={styles.sideWords}>
            <BandWords delay={320}>
              <Text maxFontSizeMultiplier={1.3} style={type.bandCaption}>
                {band.caption}
              </Text>
            </BandWords>
          </View>
        </View>
        <BandWords delay={400}>
          <Text maxFontSizeMultiplier={1.3} style={[type.bandNote, styles.note]}>
            {band.note}
          </Text>
        </BandWords>
      </Band>
      <Block key={mix.tools.map((t) => `${t.key}.${t.count}`).join(' ')} style={styles.block}>
        <Kicker>the coding tools, by session</Kicker>
        <View style={styles.tools}>
          {mix.tools.map((t, i) => {
            const ink = harnessHue(t.key)?.ink ?? GROUND.text;
            return (
              <View key={t.key} style={styles.tool} accessible accessibilityLabel={`${t.name}, ${t.sessions.final} ${t.count === 1 ? 'session' : 'sessions'}`}>
                <Arrive delay={60 + i * 90}>
                  <HarnessLogo harness={t.harness} size={48} color={GROUND.text} />
                </Arrive>
                <View style={styles.toolWords}>
                  <View style={styles.toolHead}>
                    <Text maxFontSizeMultiplier={1.4} style={[type.lead, styles.flex]}>
                      {t.name}
                    </Text>
                    <Num spec={t.sessions} textStyle={figure(34, ink)} delay={120 + i * 90} />
                  </View>
                  <GrowBar frac={t.share} color={ink} height={8} delay={160 + i * 90} />
                </View>
              </View>
            );
          })}
        </View>
        <Words style={[type.meta, styles.caption]}>{mix.basis}</Words>
      </Block>
    </Section>
  );
}

const styles = StyleSheet.create({
  lead: { paddingHorizontal: GUTTER, paddingTop: 4, paddingBottom: 18, gap: 10 },
  chapter: { marginTop: 36 },
  side: { flexDirection: 'row', alignItems: 'flex-end', gap: 14 },
  sideWords: { flex: 1, paddingBottom: 12 },
  note: { marginTop: 6 },
  block: { paddingHorizontal: GUTTER, marginTop: 26 },
  caption: { marginTop: 16 },
  tools: { gap: 20 },
  tool: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  toolWords: { flex: 1, gap: 8 },
  toolHead: { flexDirection: 'row', alignItems: 'baseline', gap: 10 },
  flex: { flex: 1 },
  small: { marginTop: 40 },
  smallBlock: { paddingHorizontal: GUTTER, gap: 10 },
});
