#!/usr/bin/env python3
"""Generate the privacy contract into Swift, Python, TypeScript, JSON and prose.

privacy/upload-contract.json is the ONLY hand-edited definition of what may leave the
machine. Everything below is derived from it, committed, and checked by
`make gen && git diff --exit-code` in CI.

v4 adds three kinds of thing, each written through the emitters in gen_analysis.py:
the contract's own objects (`burn`, `title_ids`, `call_tokens`: numbers, bools and enums,
emitted into contract.py beside SessionUpload), the `live` and `live_names` fields (shaped by
spec/live.v1.json, which gen_live.py emits; read here only for the published leaf paths),
and the `quotes` document (its own route, emitted to quotes_spec.py and quotes.ts).
`project_media` (docs/demos.md) is the same shape as `quotes`: a channel with its own route,
emitted to media_spec.py and media.ts, with a section of its own in PRIVACY.md.

The structural guarantee is the SERIALIZER, not the test: BuilderSync's SessionUpload
encodes through the generated `UploadField` CodingKey enum with a hand-written
encode(to:), and there is no synthesized Codable anywhere in that target. A field that
is not in this file is unrepresentable on the wire.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

# The emitters every spec in this repository shares, so the contract's own objects (v4:
# `burn`, `title_ids`, `call_tokens`) and the `quotes` document are written by the same code
# as the analysis, report and live specs, and `int, nullable` means one thing everywhere.
import gen_analysis as ga  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "privacy" / "upload-contract.json"
# The structured fields whose shape lives in a second spec. Their leaf paths are walked
# from there so the published field list stays exact; see spec_leaf_paths().
ANALYSIS_SPEC = ROOT / "spec" / "analysis.v1.json"
LIVE_SPEC = ROOT / "spec" / "live.v1.json"

SWIFT_BANNER = "// GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT."
PY_BANNER = "# GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT."

#: The v4 fields the Mac never sends: `live` and `live_names` come from capture and the
#: server's hook channel, `burn`, `title_ids` and `call_tokens` from the analysis modules
#: capture runs. No Swift type encodes them, so on the Mac they stay unrepresentable in practice; the
#: cases exist so `UploadField` still names every key the wire can carry.
NOT_FROM_THE_MAC = "not encoded by the Mac"

SWIFT_TYPES = {
    "sha256hex": "String",
    "string": "String",
    "int": "Int",
    "bool": "Bool",
    "datetime": "Date",
    "enum": "String",
    "base64": "String",
    "marks": "[StripMarkWire]",
    "toolmap": "[String: Int]",
    "tokens": "TokenBucketsWire",
    "models": "[ModelShareWire]",
    "feedback": "[FeedbackNoteWire]",
    "url": "String",
    # Lives in BuilderModel/Generated/AnalysisSpec.swift (gen_analysis.py), hence the
    # `import BuilderModel` in the generated Swift below.
    "analysis": "SessionAnalysis",
    "live": f"LiveState, {NOT_FROM_THE_MAC}",
    "live_names": f"LiveNames, {NOT_FROM_THE_MAC}",
}
PY_TYPES = {
    "sha256hex": "Sha256Hex",
    "string": "str",
    "int": "int",
    "bool": "bool",
    # `AwareDatetime`, not `datetime`: the plain type accepts "2026-08-15T09:00:00" with no
    # offset, and the first `now(UTC) - naive` downstream (notify.plan) is a TypeError that
    # escapes the upload transaction and turns one bad session into a 500 for the whole
    # batch. The Mac encodes every Date with `.iso8601`, which always carries `Z`.
    "datetime": "AwareDatetime",
    "enum": "str",
    "base64": "str",
    "marks": "list[StripMarkWire]",
    "toolmap": "dict[str, int]",
    "tokens": "TokenBucketsWire",
    "models": "list[ModelShareWire]",
    "feedback": "list[FeedbackNoteWire]",
    "url": "str",
    "analysis": "SessionAnalysis",
    # Generated by scripts/gen_live.py from spec/live.v1.json.
    "live": "LiveState",
    "live_names": "LiveNames",
}
TS_TYPES = {
    "sha256hex": "string",
    "string": "string",
    "int": "number",
    "bool": "boolean",
    "datetime": "string",
    "enum": "string",
    "base64": "string",
    "marks": "StripMarkWire[]",
    "toolmap": "Record<string, number>",
    "tokens": "TokenBucketsWire",
    "models": "ModelShareWire[]",
    "feedback": "FeedbackNoteWire[]",
    "url": "string",
    "analysis": "SessionAnalysis",
    "live": "LiveState",
    "live_names": "LiveNames",
}


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def fields(c: dict) -> list[dict]:
    return c["fields"]


def objects_spec(c: dict) -> dict:
    """The contract's own objects in the shape gen_analysis's emitters read. No string
    field is allowed in them: every v4 session object is numbers, bools and enums, and a
    free string is how prose would reach the wire."""
    s = {"enums": c["enums"], "objects": c["objects"], "max_lengths": {}, "fields": []}
    for owner, fs in s["objects"].items():
        for f in fs:
            assert f["type"] != "string" and f.get("item") != "string", (
                f"{owner}.{f['name']} is a string. The contract's objects carry numbers, "
                "bools and enums only; a sentence is written on the phone from them."
            )
            if f["type"] == "double":
                assert ga.FRACTION_DOC.search(f.get("doc", "")), (
                    f"{owner}.{f['name']} is a double whose doc does not say it is a share: "
                    "every double is emitted with bounds 0 to 1."
                )
    return s


def field_py_type(f: dict) -> str:
    return f["item"] if f["type"] == "object" else PY_TYPES[f["type"]]


def field_ts_type(f: dict) -> str:
    return f["item"] if f["type"] == "object" else TS_TYPES[f["type"]]


def field_swift_type(f: dict) -> str:
    return f"{f['item']}, {NOT_FROM_THE_MAC}" if f["type"] == "object" else SWIFT_TYPES[f["type"]]


def tool_call_keys(c: dict) -> list[str]:
    """The tool map's allowlist, from the contract's own `values` (v4). One definition."""
    return next(f["values"] for f in fields(c) if f["type"] == "toolmap")


# --------------------------------------------------------------------------- swift
def gen_swift(c: dict) -> str:
    fs = fields(c)
    # Each case carries the Swift type the hand-written payload is expected to encode
    # through it, so a reader of this file can see the whole wire shape without opening
    # UploadPayload.swift. `?` marks a field that is omitted — never sent as null — when
    # absent.
    def swift_case(f: dict) -> str:
        t = field_swift_type(f)
        opt = "?" if f.get("nullable") else ""
        # `LiveState?, not encoded by the Mac`: the optional mark belongs to the type.
        if NOT_FROM_THE_MAC in t:
            name, rest = t.split(", ", 1)
            return f'    case {f["name"]}  // {name}{opt}, {rest}'
        return f'    case {f["name"]}  // {t}{opt}'

    cases = "\n".join(swift_case(f) for f in fs)

    def mode_set(mode: str) -> str:
        names = [f'.{f["name"]}' for f in fs if mode in f["modes"]]
        return "[\n        " + ",\n        ".join(names) + ",\n    ]"

    enums = "\n".join(
        f'        "{f["name"]}": {json.dumps(sorted(f["values"]))},'
        for f in fs
        if f["type"] == "enum"
    )

    tool_keys = json.dumps(tool_call_keys(c))

    return f"""{SWIFT_BANNER}

// BuilderModel supplies `SessionAnalysis` (Generated/AnalysisSpec.swift), the value type
// behind the `analysis` key. It is the only wire type the Mac encodes that is not defined
// in this file. The cases marked "not encoded by the Mac" (v4: live, live_names, burn,
// title_ids, call_tokens) are sent by capture and the server's hook channel; no Swift type
// here or in BuilderSync can hold one, so the Mac cannot put them on the wire.
import BuilderModel
import Foundation

/// Every key that may appear on the wire. `SessionUpload` encodes through this and only
/// this, with a hand-written `encode(to:)` and no synthesized `Codable`, so a field that
/// is not a case here is *unrepresentable* — adding a stored property to a model cannot
/// change the payload.
public enum UploadField: String, CodingKey, CaseIterable, Sendable {{
{cases}
}}

/// Per-repo visibility. `excluded` is deliberately not a mode: an excluded repo produces
/// zero uploads, and if ANY event in a session resolves to an excluded repo the entire
/// session is dropped rather than partially uploaded.
public enum PrivacyMode: String, Sendable, CaseIterable {{
    case publicRepo = "public"
    case anonymous

    public var allowedFields: Set<UploadField> {{
        switch self {{
        case .publicRepo: return UploadContract.publicFields
        case .anonymous:  return UploadContract.anonymousFields
        }}
    }}
}}

public enum UploadContract {{
    public static let version = {c["version"]}

    public static let publicFields: Set<UploadField> = {mode_set("public")}

    public static let anonymousFields: Set<UploadField> = {mode_set("anonymous")}

    /// Legal values for every enum-typed field, so a typo becomes a test failure here
    /// rather than a 422 from the server on the user's first sync.
    public static let enumValues: [String: [String]] = [
{enums}
    ]

    /// The only keys `tool_calls` may carry (v4). The server rejects any other key, so a
    /// tool name outside the four must be bucketed to `mcp_other` or `other` first.
    public static let toolCallKeys: [String] = {tool_keys}
}}

// MARK: - Wire value types

public struct StripMarkWire: Codable, Sendable, Equatable {{
    public let ms: Int
    public let k: Int
    public init(ms: Int, k: Int) {{ self.ms = ms; self.k = k }}
}}

/// Five separate buckets. There is no `total` — `cache_read` IS billed, at a reduced
/// rate, and on a cache-heavy agentic workload it dominates the input side, so a single
/// summed field would silently pick a definition.
public struct TokenBucketsWire: Codable, Sendable, Equatable {{
    public let input: Int
    public let output: Int
    public let cacheRead: Int
    public let cacheWrite5m: Int
    public let cacheWrite1h: Int

    enum CodingKeys: String, CodingKey {{
        case input, output
        case cacheRead = "cache_read"
        case cacheWrite5m = "cache_w5m"
        case cacheWrite1h = "cache_w1h"
    }}

    public init(input: Int, output: Int, cacheRead: Int, cacheWrite5m: Int, cacheWrite1h: Int) {{
        self.input = input; self.output = output; self.cacheRead = cacheRead
        self.cacheWrite5m = cacheWrite5m; self.cacheWrite1h = cacheWrite1h
    }}
}}

public struct ModelShareWire: Codable, Sendable, Equatable {{
    public let modelID: String
    public let outputTokenShare: Double

    enum CodingKeys: String, CodingKey {{
        case modelID = "model_id"
        case outputTokenShare = "output_token_share"
    }}

    public init(modelID: String, outputTokenShare: Double) {{
        self.modelID = modelID; self.outputTokenShare = outputTokenShare
    }}
}}

/// One thing this sitting cost that the person would not have chosen.
///
/// An id and two integers. The SENTENCE is written on the client from the id, so the wire
/// carries no wording, and — unlike the note the same module prints on the machine — no
/// failing command and no file name. Both are on the never-list in the contract and both
/// stay there.
public struct FeedbackNoteWire: Codable, Sendable, Equatable {{
    public let id: String
    public let seconds: Int
    public let count: Int

    public init(id: String, seconds: Int, count: Int) {{
        self.id = id; self.seconds = seconds; self.count = count
    }}
}}
"""


# -------------------------------------------------------------------------- python
def note_ids(c: dict) -> list[str]:
    """The feedback note ids, from the contract's own `values`. One definition."""
    return next(f["values"] for f in fields(c) if f["type"] == "feedback")


def gen_py(c: dict) -> str:
    fs = fields(c)
    feedback_ids = json.dumps(note_ids(c))
    lines = []
    for f in fs:
        t = field_py_type(f)
        if f.get("nullable"):
            lines.append(f'    {f["name"]}: {t} | None = None')
        else:
            lines.append(f'    {f["name"]}: {t}')
    body = "\n".join(lines)

    # The contract's own objects (v4), through the emitters every spec shares. Their enum
    # tables get their own names: this module's `ENUM_VALUES` is the top-level fields'.
    os_ = objects_spec(c)
    object_enum_values = "\n".join(
        f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in os_["enums"].items()
    )
    object_enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in ofs if f["type"] == "enum"})
        + ","
        for owner, ofs in os_["objects"].items()
    )
    object_models = "\n\n".join(
        ga.py_model(
            os_,
            name,
            ofs,
            scalars=ga.PY_SCALARS_AWARE,
            enum_table="OBJECT_ENUM_VALUES",
            fields_table="OBJECT_ENUM_FIELDS",
        )
        for name, ofs in os_["objects"].items()
    ).rstrip("\n")
    tool_keys = json.dumps(tool_call_keys(c))

    enum_fields = [f for f in fs if f["type"] == "enum"]
    enum_table = "\n".join(
        '    "{}": {},'.format(f["name"], json.dumps(sorted(f["values"]))) for f in enum_fields
    )
    enum_names = ", ".join('"{}"'.format(f["name"]) for f in enum_fields)
    vtext = (
        f"    @field_validator({enum_names})\n"
        "    @classmethod\n"
        "    def _validate_enum(cls, v, info):\n"
        "        allowed = ENUM_VALUES.get(info.field_name)\n"
        "        if v is not None and allowed is not None and v not in allowed:\n"
        "            raise ValueError(\n"
        "                '%s=%r is not one of %r' % (info.field_name, v, allowed)\n"
        "            )\n"
        "        return v\n"
        "\n"
        '    @field_validator("tool_calls")\n'
        "    @classmethod\n"
        "    def _validate_tool_call_keys(cls, v):\n"
        "        bad = sorted(k for k in v if k not in TOOL_CALL_KEYS)\n"
        "        if bad:\n"
        "            raise ValueError(\n"
        "                'tool_calls has keys %r outside %r' % (bad, TOOL_CALL_KEYS)\n"
        "            )\n"
        "        return v\n"
    )

    pub = json.dumps(sorted(f["name"] for f in fs if "public" in f["modes"]), indent=4)
    anon = json.dumps(sorted(f["name"] for f in fs if "anonymous" in f["modes"]), indent=4)

    return f'''{PY_BANNER}
"""The wire contract, server side. `extra="forbid"` is the belt-and-suspenders half of
the guarantee: even a hostile or stale client cannot push an undeclared field into
Postgres. The client-side half is that undeclared fields are unrepresentable at all."""

from __future__ import annotations

import re
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

# Generated by scripts/gen_analysis.py from spec/analysis.v1.json. `extra="forbid"` at
# every nesting level there, so an undeclared key inside `analysis` is as unstorable as
# an undeclared top-level field here.
from .analysis_spec import SessionAnalysis

# Generated by scripts/gen_live.py from spec/live.v1.json, the shape of `live` and
# `live_names` (v4). Closed at every level, and a file id there is 16 hex or a 422.
from .live_spec import LiveNames, LiveState

CONTRACT_VERSION = {c["version"]}

_SHA256 = re.compile(r"^[0-9a-f]{{64}}$")
Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{{64}}$")]

PUBLIC_FIELDS = {pub}

ANONYMOUS_FIELDS = {anon}

#: Legal values for every enum-typed field, so a client typo is a 422 with a useful
#: message rather than a constraint violation deep in a batch insert.
ENUM_VALUES: dict[str, list[str]] = {{
{enum_table}
}}

#: The only keys `tool_calls` may carry (v4). Any other key is a 422: the contract always
#: said unknown and MCP tool names bucket to mcp_other / other, and this is the door
#: keeping that promise rather than storing whatever name a client sent.
TOOL_CALL_KEYS: list[str] = {tool_keys}

#: Legal values for the enums inside the contract's own objects (v4: `burn`,
#: `title_ids`, `call_tokens`), in contract order. Each copies a Python table and is
#: pinned to it both ways by server/tests/test_contract.py.
OBJECT_ENUM_VALUES: dict[str, list[str]] = {{
{object_enum_values}
}}

#: model name -> field name -> enum name, for the validators of the objects below.
OBJECT_ENUM_FIELDS: dict[str, dict[str, str]] = {{
{object_enum_fields}
}}


class StripMarkWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ms: int
    k: int


class TokenBucketsWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    input: int
    output: int
    cache_read: int
    cache_w5m: int
    cache_w1h: int


class ModelShareWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    model_id: str
    output_token_share: float


#: The three notes analysis/feedback.py can produce. From the contract's own `values`, so
#: a fourth note is a contract change and a fourth renderer on the client, in that order.
FEEDBACK_NOTE_IDS: list[str] = {feedback_ids}


class FeedbackNoteWire(BaseModel):
    model_config = ConfigDict(extra="forbid")
    #: One of FEEDBACK_NOTE_IDS. Checked here rather than only rendered, because an id
    #: the client cannot render is a blank row on the card and no error anywhere.
    id: str
    seconds: int
    count: int

    @field_validator("id")
    @classmethod
    def _known_note(cls, v):
        if v not in FEEDBACK_NOTE_IDS:
            raise ValueError(f"id={{v!r}} is not one of {{FEEDBACK_NOTE_IDS!r}}")
        return v


{object_models}


class SessionUpload(BaseModel):
    model_config = ConfigDict(extra="forbid")

{body}

{vtext}
'''


# ---------------------------------------------------------------------- typescript
def gen_ts(c: dict) -> str:
    fs = fields(c)
    os_ = objects_spec(c)
    unions = "\n".join(
        f"export type {ga.pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in os_["enums"].items()
    )
    enum_table = "\n".join(
        f"  {name}: {json.dumps(values)}," for name, values in os_["enums"].items()
    )
    interfaces = "\n\n".join(ga.ts_interface(os_, name, ofs) for name, ofs in os_["objects"].items())
    tool_keys = json.dumps(tool_call_keys(c))
    lines = []
    for f in fs:
        t = field_ts_type(f)
        # A nullable field is omitted by the Mac when absent, and a server that echoes a
        # stored row may hand it back as null. `?: T | null` is the only annotation under
        # which both are legal reads.
        nullable = bool(f.get("nullable"))
        opt = "?" if nullable else ""
        t = f"{t} | null" if nullable else t
        doc = f'  /** {f["doc"]} */\n' if f.get("doc") else ""
        lines.append(f'{doc}  {f["name"]}{opt}: {t};')
    body = "\n".join(lines)
    pub = json.dumps(sorted(f["name"] for f in fs if "public" in f["modes"]))
    anon = json.dumps(sorted(f["name"] for f in fs if "anonymous" in f["modes"]))
    return f"""{SWIFT_BANNER.replace('Swift', 'TypeScript')}

import type {{ SessionAnalysis }} from './analysis';
import type {{ LiveNames, LiveState }} from './live';

export const CONTRACT_VERSION = {c["version"]};

/** The only keys `tool_calls` may carry (v4); the server rejects any other. */
export const TOOL_CALL_KEYS = {tool_keys} as const;

export interface StripMarkWire {{ ms: number; k: number; }}
export interface TokenBucketsWire {{
  input: number; output: number;
  cache_read: number; cache_w5m: number; cache_w1h: number;
}}
export interface ModelShareWire {{ model_id: string; output_token_share: number; }}
/** An id and two integers. The sentence is written on the phone; see src/session/feedback.ts. */
export interface FeedbackNoteWire {{ id: string; seconds: number; count: number; }}

{unions}

/** Legal values for the enums of the contract's own objects (v4), in contract order. */
export const CONTRACT_ENUMS = {{
{enum_table}
}} as const;

{interfaces}

/** The complete set of fields the phone can ever receive for a session. */
export interface SessionWire {{
{body}
}}

export const PUBLIC_FIELDS = {pub} as const;
export const ANONYMOUS_FIELDS = {anon} as const;
"""


# ------------------------------------------------------------------------ quotes
QUOTES_TOP = "QuotesUpload"


def quotes_spec(c: dict) -> dict:
    """The `quotes` document (v4, the second opt-in exception) as a spec the shared
    emitters read. Its one free string is the quote itself, capped: the check below keeps
    a second string from arriving unbounded."""
    q = c["quotes"]
    s = {"enums": q["enums"], "objects": q["objects"], "max_lengths": q["max_lengths"], "fields": q["fields"]}
    for owner, fs in ga.all_fields(s, QUOTES_TOP):
        for f in fs:
            if f["type"] == "string":
                assert "max" in f, f"quotes {owner}.{f['name']} is a string with no cap"
    return s


def gen_quotes_py(c: dict) -> str:
    s = quotes_spec(c)
    q = c["quotes"]
    models = "\n\n".join(
        [ga.py_model(s, name, fs, scalars=ga.PY_SCALARS_AWARE) for name, fs in s["objects"].items()]
        + [ga.py_model(s, QUOTES_TOP, s["fields"], scalars=ga.PY_SCALARS_AWARE)]
    ).rstrip("\n")
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in ga.all_fields(s, QUOTES_TOP)
    )
    doc = "\n".join(q["doc"])
    return f'''{PY_BANNER}
"""The quotes document, server side (`{q["route"]}`, default {q["default"]}).

{doc}

`extra="forbid"` at every level and the 160 character cap are this door's half. The other
half is `server/builder/quotes.py quotes_gate`, which re-runs the machine's own mask and
identifier filter on every quote before anything is stored.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{{64}}$")]

#: Character caps by size class; the document's `max` on a string field names one of these.
QUOTES_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: Legal values for every enum, in contract order. Named for the emitter in
#: scripts/gen_analysis.py, whose validators read these two tables by name.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}


{models}
'''


def gen_quotes_ts(c: dict) -> str:
    s = quotes_spec(c)
    q = c["quotes"]
    unions = "\n".join(
        f"export type {ga.pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in s["enums"].items()
    )
    interfaces = "\n\n".join(
        [ga.ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.ts_interface(s, QUOTES_TOP, s["fields"])]
    )
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    return f"""{SWIFT_BANNER.replace('Swift', 'TypeScript')}

/** The quotes document: {q["route"]}, default {q["default"]}. Owner only, opt in twice. */
export const QUOTES_ROUTE = {json.dumps(q["route"])};

/** Character caps by size class; string fields below name one of these in their doc. */
export const QUOTES_MAX_LENGTHS = {{
{max_lengths}
}} as const;

{unions}

{interfaces}
"""


# ----------------------------------------------------------------- project media
MEDIA_TOP = "ProjectMediaPresign"


def media_spec(c: dict) -> dict:
    """The `project_media` presign request (docs/demos.md) as a spec the shared emitters
    read. Its one free string is the label, capped here and bounded in characters by
    `label_rule`; the checks below keep a second string from arriving uncapped, and hold the
    tables that restate one another to each other, so the content types a presign may name
    are exactly the ones with a size cap, each of a declared kind."""
    m = c["project_media"]
    s = {"enums": m["enums"], "objects": m["objects"], "max_lengths": m["max_lengths"], "fields": m["fields"]}
    for owner, fs in ga.all_fields(s, MEDIA_TOP):
        for f in fs:
            if f["type"] == "string":
                assert "max" in f, f"project_media {owner}.{f['name']} is a string with no cap"
    assert list(m["content_types"]) == m["enums"]["media_content_type"], (
        "project_media.content_types and enums.media_content_type must list the same types in one order"
    )
    kinds = {v["kind"] for v in m["content_types"].values()}
    assert kinds == set(m["enums"]["media_kind"]), f"a content type of an undeclared kind: {kinds}"
    assert set(m["enums"]["poster_content_type"]) <= {
        t for t, v in m["content_types"].items() if v["kind"] == "image"
    }, "a poster is an image the stills could be"
    return s


def media_read_seconds() -> int:
    """`project_media.READ_URL_SECONDS`, read from the source as `transcript_retention_days`
    reads the ingest route's number, so PRIVACY.md and the presigned GET say one number."""
    import re

    src = (ROOT / "server" / "builder" / "project_media.py").read_text()
    m = re.search(r"^READ_URL_SECONDS = (\d+)", src, re.M)
    if m is None:
        raise SystemExit("gen_contract: READ_URL_SECONDS not found in server/builder/project_media.py")
    return int(m.group(1))


def gen_media_py(c: dict) -> str:
    s = media_spec(c)
    m = c["project_media"]
    models = "\n\n".join(
        [
            ga.py_model(
                s,
                name,
                fs,
                scalars=ga.PY_SCALARS_AWARE,
                enum_table="MEDIA_ENUM_VALUES",
                fields_table="MEDIA_ENUM_FIELDS",
            )
            for name, fs in s["objects"].items()
        ]
        + [
            ga.py_model(
                s,
                MEDIA_TOP,
                s["fields"],
                scalars=ga.PY_SCALARS_AWARE,
                enum_table="MEDIA_ENUM_VALUES",
                fields_table="MEDIA_ENUM_FIELDS",
            )
        ]
    ).rstrip("\n")
    content_types = "\n".join(
        f"    {json.dumps(t)}: {json.dumps(v, sort_keys=True)}," for t, v in m["content_types"].items()
    )
    caps = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in m["caps"].items())
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in ga.all_fields(s, MEDIA_TOP)
    )
    doc = "\n".join(m["doc"])
    return f'''{PY_BANNER}
"""A project demo's presign request, server side (`{m["route"]}`, default {m["default"]}).

{doc}

`extra="forbid"` at every level, the enums and the numeric bounds are this door's half. The
other half is `server/builder/project_media.py presign_refusal`, which holds the content type
to its kind and its size cap, a video to its length and an image to none, and the label to
MEDIA_LABEL_PATTERN and the word length, before anything is stored or signed.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

Hex16 = Annotated[str, Field(pattern=r"^[0-9a-f]{{16}}$")]

MEDIA_ROUTE = {json.dumps(m["route"])}

#: Every content type a presign may name: its kind, and the most bytes one file of it may be.
MEDIA_CONTENT_TYPES: dict[str, dict] = {{
{content_types}
}}

#: Counts per publish, the longest video in ms, the largest side in pixels, the longest word
#: of a label in characters.
MEDIA_CAPS: dict[str, int] = {{
{caps}
}}

#: Character caps by size class; the document's `max` on a string field names one of these.
MEDIA_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: The characters a label may carry, whole: {m["label_rule"]}.
MEDIA_LABEL_PATTERN = {json.dumps(m["label_pattern"])}
MEDIA_LABEL_RULE = {json.dumps(m["label_rule"])}

#: Legal values for every enum, in contract order. Named for this module; the validators
#: below read these two tables by name.
MEDIA_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: Which fields of which model carry which enum, read by the validators below.
MEDIA_ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}


{models}
'''


def gen_media_ts(c: dict) -> str:
    s = media_spec(c)
    m = c["project_media"]
    unions = "\n".join(
        f"export type {ga.pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in s["enums"].items()
    )
    interfaces = "\n\n".join(
        [ga.ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.ts_interface(s, MEDIA_TOP, s["fields"])]
    )
    content_types = "\n".join(
        f"  {json.dumps(t)}: {{ kind: {json.dumps(v['kind'])}, max_bytes: {v['max_bytes']} }},"
        for t, v in m["content_types"].items()
    )
    caps = "\n".join(f"  {k}: {v}," for k, v in m["caps"].items())
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    return f"""{SWIFT_BANNER.replace('Swift', 'TypeScript')}

/** A project demo's presign: {m["route"]}, default {m["default"]}. Owner only, opt in per publish. */
export const MEDIA_ROUTE = {json.dumps(m["route"])};

/** Every content type a presign may name: its kind, and the most bytes one file of it may be. */
export const MEDIA_CONTENT_TYPES = {{
{content_types}
}} as const;

/** Counts per publish, the longest video in ms, the largest side in pixels, the longest word of a label. */
export const MEDIA_CAPS = {{
{caps}
}} as const;

/** Character caps by size class; string fields below name one of these in their doc. */
export const MEDIA_MAX_LENGTHS = {{
{max_lengths}
}} as const;

/** The characters a label may carry, whole: {m["label_rule"]}. */
export const MEDIA_LABEL_PATTERN = {json.dumps(m["label_pattern"])};

{unions}

{interfaces}
"""


# ------------------------------------------------------------------------- prose
def transcript_retention_days() -> int:
    """`routes/ingest.py RETENTION_DAYS`, read from the source (this generator runs on a
    bare Python with no FastAPI), so the page and the route can never say two numbers."""
    import re

    src = (ROOT / "server" / "builder" / "routes" / "ingest.py").read_text()
    m = re.search(r"^RETENTION_DAYS = (\d+)$", src, re.M)
    if m is None:
        raise SystemExit("gen_contract: RETENTION_DAYS not found in server/builder/routes/ingest.py")
    return int(m.group(1))


def _size(n: int) -> str:
    mib = 1024 * 1024
    return f"{n // mib} MiB" if n % mib == 0 else f"{n:,} bytes"


def gen_media_md(c: dict) -> str:
    """PRIVACY.md's section on project demos, every number from the contract or the route."""
    m = c["project_media"]
    caps = m["caps"]
    types = m["content_types"]
    image_types = [t for t, v in types.items() if v["kind"] == "image"]
    video_types = [t for t, v in types.items() if v["kind"] == "video"]
    still = max(types[t]["max_bytes"] for t in image_types)
    video = max(types[t]["max_bytes"] for t in video_types)
    sources = ", ".join(f"`{s}`" for s in m["enums"]["media_source"])
    minutes = media_read_seconds() // 60
    seconds = caps["video_ms"] // 1000
    videos = "one" if caps["videos"] == 1 else str(caps["videos"])
    return f"""## Project demos

A demo is the screenshots and one short video of a project you are building, made on your
Mac by `python -m capture demo` from the running app. It stays in `~/.builder/demos/` on your
Mac, and nothing sends it until you publish it, one project at a time:
`python -m capture demo --publish` prints how many files and how many bytes it will send and
waits for your yes. It refuses a demo whose privacy check has not run, or found the
repository's name or something shaped like a key in a picture, and says which file.

A publish sends at most {caps["images"]} images ({" or ".join(f"`{t}`" for t in image_types)}, each at most {_size(still)})
and at most {videos} video ({" or ".join(f"`{t}`" for t in video_types)}, at most {seconds} seconds and {_size(video)}) with its
still frame. With each file go only its numbers (size, width, height, length and its place
in the set), where it came from ({sources}), a random id for the
publish, and a label of at most {m["max_lengths"]["label"]} characters saying what the screen shows, made of
{m["label_rule"]}. Never the file names, the commit it was taken at, or the project's name.

Only you can see a demo, whatever you share. It is never in a post, a feed, a share, a push
or a Live Activity. Its files are kept in a private store of their own, never the one public
post photos are served from, and nothing there has a public address: the phone reads each
file through a link that stops working after {minutes} minutes (or, on a Builder server you run
on your own Mac, through the server checking your sign in). Each upload link is good only for
as long as that one file's upload needs. Deleting a demo on the phone, or
`python -m capture demo --delete`, deletes its files and their records in one request, along
with anything an interrupted upload left behind. Publishing again replaces the demo that was
there. Deleting your account, or excluding the repository, deletes every demo it had.
"""


def kit_spec() -> dict:
    """spec/shipkit.v1.json, the shapes the contract's `ship_kit` section points at."""
    s = json.loads((ROOT / "spec" / "shipkit.v1.json").read_text())
    return {k: ({kk: vv for kk, vv in v.items() if not kk.startswith("_")} if isinstance(v, dict) else v) for k, v in s.items()}


def gen_kit_md(c: dict) -> str:
    """PRIVACY.md's section on ship kits, every number from the spec it points at."""
    k = c["ship_kit"]
    s = kit_spec()
    caps = s["caps"]
    platforms = ", ".join(s["enums"]["platform"])
    minutes = media_read_seconds() // 60
    return f"""## Ship kits

A ship kit is what your Mac makes beside a demo so you can post it: the demo in four shapes
for the platforms (9:16, 4:5, 16:9, 1:1) with your device drawn around it, a GIF, the stills
framed, the same screen before and after, App Store screenshots for an iOS app, a caption
for each of {platforms}, and the subjects of the commits since your last demo. It is made on
your Mac and stays there. Nothing sends it until you run
`python -m capture demo kit --publish`, which reads every picture for names and keys once
more, lists every file and its size, and waits for your yes.

A publish sends at most {caps["videos"]} videos (MP4, at most {caps["video_ms"] // 1000} seconds and {_size(caps["video_bytes"])} each), one GIF
(at most {_size(caps["gif_bytes"])}) and pictures (PNG or JPEG, at most {_size(caps["image_bytes"])} each), each with only its
numbers (size, width, height, length, its place) and, for a still, the demo's own label.
Then one document: the captions (each within its platform's limit, and every number in it
one your own session record gave), the commit subjects as you wrote them (never a commit
hash; a subject that names a repository or carries something shaped like a key is left
out), the device it was filmed on, the colour it is drawn in, and what could not be made.
Never a file name or the project's name.

Only you can see a kit, whatever you share, and nothing of it is in a post, a feed, a share,
a push or a Live Activity. Its files are kept in the same private store as your demos and
read through links that stop working after {minutes} minutes. Publishing again replaces the kit
that was there; deleting it, excluding the repository or deleting your account deletes every
file and the document. The phone's button that asks your Mac for a demo
(`{k["request_route"]}`) sends the project's key and its colour, nothing else.
"""


def gen_privacy_md(c: dict) -> str:
    fs = fields(c)
    rows = []
    for f in fs:
        modes = "public + anonymous" if len(f["modes"]) == 2 else f'**{f["modes"][0]} repos only**'
        doc = f.get("doc", "")
        kind = f["item"] if f["type"] == "object" else f["type"]
        rows.append(f'| `{f["name"]}` | {kind} | {modes} | {doc} |')
    table = "\n".join(rows)
    q = c["quotes"]
    cap = q["max_lengths"]["quote"]
    most = next(f["max_items"] for f in q["fields"] if f["name"] == "quotes")
    tool_keys = ", ".join(f"`{k}`" for k in tool_call_keys(c))
    retention = transcript_retention_days()
    media = gen_media_md(c)
    kit = gen_kit_md(c)

    return f"""<!-- GENERATED by scripts/gen_contract.py from privacy/upload-contract.json — DO NOT EDIT. -->

# What Builder sends, and what it does not

Builder reads the logs your AI coding tools already write to your own disk. Almost all of
that never moves. This page is generated directly from the file that defines the network
payload, so it cannot drift from the code: if a field is not in this table, the app has no
way to represent it on the wire.

## Never leaves your machine

Your prompts. The model's replies. Its thinking. Anything you or the model typed into a
file. Diffs and patches. File contents. **File paths, and file names.** Directory names.
Commit messages. Commit SHAs. Branch names. Your working directory. Your git remote URL.
The names of repositories you have not marked public. MCP server names. Terminal commands
and their output. Environment variables. URLs fetched. Your hostname. Your IP.

Not redacted versions of these. Not excerpts. Nothing the Mac app or `capture sync` sends
carries them, with three opt-in exceptions, each off until you turn it on and each
described in its own section below: **Session analysis** (prose your own Claude Code writes
about a session), **Quoted prompts** (up to {most} of your prompts, for the Wrapped cards
that quote you) and **File names** (the names of the files a running session touches, on
its session screen). They are the only places a word you typed, or the name of a file, can
travel in a session upload.

One channel is different, and nothing sends by it until you install it: **the raw
transcript channel** (the Claude Code hook, or `python -m capture live`) sends the
transcript itself, everything above included, to your Builder server, which keeps only the
fields in the table below. It has its own section.

And one thing is not a session at all: **a project demo**, the screenshots and short video
of something you are building, which leaves only when you publish it, one project at a time.
It has its own section too.

`tool_calls` counts calls by tool, and its keys can only be {tool_keys}: any other tool,
an MCP server's included, is counted under `mcp_other` or `other`, and the server refuses
a key outside that list.

## What does leave, if you sign in

Every field, in full. `{c["version"]}` is the contract version.

| Field | Type | Sent for | What it is |
|---|---|---|---|
{table}

## Per-repository control

Every repository is **anonymous** by default: its sessions sync as a shape and a set of
counts, with no name attached. You can set a repository to **public**, which adds only
`repo_name`, `title` and `title_source`, or to **excluded**, which sends nothing at all.
If a single session touched an excluded repository, the whole session is dropped rather
than partially uploaded.

Titles come from the title your coding tool **already wrote to your disk**. Builder does
not send your prompts to a model to generate one. There is no such endpoint.

## A running session

While a session runs, `live` says what it is doing, as numbers and ids: the kind of work
(reading, editing, testing), whether it is converging, circling or lost, an ETA or the
reason there is none, and a map of the files it touched in which every file is a 16
character id, salted with a secret that never leaves your machine or your account. No path,
no file name, no command, no prompt. It is deleted when the session finishes. Your Lock
Screen, your widget and every push see only these numbers.

`burn`, `title_ids` and `call_tokens` describe a session after the fact in the same way:
where its tokens went, its title, and what each call to the model sent and got back (token
counts, the calls that found the cache expired, and what each kind of token would cost at
API list prices), as counts and ids from fixed lists. No model name travels in them. The
sentences you read about them are written on your phone.

## Session analysis

The `analysis` field is the first of the three exceptions to the rule above, and it is
opt-in for exactly that reason.

When a session finishes, Builder can ask **your own Claude Code**, on your own machine, to
read a digest of the transcript and write a short account of it: what got built, how you
steered the agent, where the friction was. That is model-written prose. It may name files
and features, because that is what the session was about. It is produced locally (nothing
is sent to a third party to be summarised), and its shape is fixed by
`spec/analysis.v1.json`: every string has a length cap, and a document with an undeclared
key is rejected by the server rather than stored.

It **never includes your raw prompts**. The one place a prompt can appear is
`decision_patterns[].prompt_excerpt`: a short verbatim quote, at most 160 characters,
chosen to show a pattern in how you directed the agent. Nothing else in the document
quotes you.

Private by default. On the server it is readable only by your account, under the same row
level security as everything else, and it leaves your account only when you share that
session. Turn analysis upload off and the field is not sent at all: omitted, not sent as
empty.

## Quoted prompts

The `quotes` document goes to its own address (`{q["route"]}`), never with a session, and
only when BOTH the phone's setting "Quote my prompts on my cards" and the machine's
`--quotes` flag say yes. The flag is never remembered, so a scheduled upload never sends
one. It holds at most {most} of your prompts, verbatim, each at most {cap} characters, for
the Wrapped cards that quote you: your go-to prompt, your biggest crash out and your most
cryptic prompt. Every quote is masked for secrets and filtered for anything shaped like an
identifier twice, once on your machine and again on the server, which refuses it otherwise.

Only you can see them. They are never in a post, a feed, a share, a push or a Live
Activity. Turning the setting off deletes them.

## File names

`live_names` carries the name of each file in a running session's map (a basename such as
`auth.py`, never a directory), keyed by its id. It is off by default: sent only with
`capture sync --live --live-names`, and stored only while File names is on for your
account. Only you can see them, on the session screen; the Lock Screen, the widget, pushes
and shares never receive one. Turning it off deletes the names already stored.

{media}
{kit}
## The raw transcript channel

The Claude Code hook (`curl $BUILDER_URL/v1/ingest/hook.sh`, `docs/hooks-capture.md`) and
`python -m capture live` do not build the payload above on your machine. They send the
**raw transcript**: your prompts, the model's replies and its thinking, every tool call and
its output, file paths and contents, byte for byte, over TLS, to the Builder server you
point them at (`BUILDER_URL`). That server cuts the sessions with the same code `capture
sync` runs on a machine, so the sessions it stores are the table above and nothing more:
the same fields, through the same door. Nothing sends a transcript until you install the
hook or run the command.

The raw bytes are held only until their session is final, or {retention} days for a
session that never finishes. Until then only your account can read them, under the same
row level security as everything else; `DELETE /v1/ingest/transcript/<id>` drops them at
once, and revoking the key closes the channel. If you would rather no server held your
words even that long, use `capture sync`, which sends only the fields.

`python -m capture live` reads each transcript whole before its first post and never sends
one that has run in a repository `BUILDER_CAPTURE_EXCLUDE` names; a sitting that moves into
one while it is watched stops there (the lines already sent before it moved stay sent), and
a transcript you name that has run in one is refused. The hook script has no such list: it
sends every transcript Claude Code hands it. The server refuses a
session in a repository you set to excluded whenever the session says which repository it
is in; a server that is not on your machine cannot resolve your working directory, so a
hook's sessions there say none.

## Check it yourself

Do not take the above on faith. The agent is open source and these commands run locally.

```bash
# 1. Print every byte the agent would send. Sends nothing.
builder sync --dry-run --print-payload | jq

# 2. Diff its actual keys against this page, in both directions.
#    `leaf_paths` expands every structured field (tokens, models, strip_marks, feedback,
#    tool_calls, analysis, live, live_names, burn, title_ids, call_tokens) so a scalar-path
#    walk lines up exactly. tool_calls keys are tool names, so they are normalised to the
#    wildcard the contract publishes. List indices are stripped both mid-path
#    (dimensions.0.score) and trailing (tags.0).
builder sync --dry-run --print-payload \\
  | jq -r '[paths(scalars)] | .[] | join(".")' \\
  | sed 's/^sessions\\.[0-9]*\\.//' \\
  | sed 's/\\.[0-9][0-9]*\\./\\./g' \\
  | sed 's/\\.[0-9][0-9]*$//' \\
  | sed 's/^tool_calls\\..*/tool_calls.<allowlisted tool name>/' \\
  | sort -u > /tmp/actual
curl -s "$BUILDER_BASE_URL/upload-fields.json" | jq -r '.leaf_paths[]' | sort -u > /tmp/declared
# (`documents.quotes.leaf_paths` is the same list for the quotes document, and
# `documents.project_media.leaf_paths` for each file of a published demo.)

# Anything on the left that is not on the right is a field we send and did not declare.
comm -23 /tmp/actual /tmp/declared

# 3. Pick a phrase you typed to your agent today. Go looking for it.
builder sync --dry-run --print-payload | grep -i "that phrase"   # no output, exit 1

# 4. Trust none of the above. Builder does not certificate-pin, on purpose.
mitmproxy -p 8080 &
HTTPS_PROXY=http://127.0.0.1:8080 builder sync
```

## Repository hashing: the honest limit

Repositories are identified by an HMAC of the normalized git origin URL. The key is a
**global constant, identical for every user**: matching the same repository across two
machines requires both to derive the same hash. It ships inside an open-source binary and
is **not secret**.

The hash defeats casual exposure and makes a database dump unreadable. It does **not**
survive a dictionary attack against public repository names. If you need real secrecy, set
the repository to `excluded`: it is never hashed, never uploaded, and never parsed again.
Private set intersection is the correct fix and is not built.

## Permissions

Builder does not require Full Disk Access, Screen Recording, or Accessibility, and does not
ask for them. It reads `~/.claude`, `~/.codex`, `~/.cursor` and Cursor's application support
directory, none of which are protected by those permissions today. If a future macOS release
restricts one of them, Builder will tell you which one and why, and will keep working on the
others.
"""


def spec_leaf_paths(s: dict, owner_fields: list[dict], prefix: str) -> list[str]:
    """Every scalar path a document shaped by spec `s` can produce, under `prefix`.

    Walked from the spec rather than typed out, so a field added to a spec is published
    here on the next `make gen` without anyone remembering to. The path shapes mirror what
    the verification command's jq/sed pipeline produces:

      object   -> prefix.field.child           (build_style.planning)
      list of objects -> prefix.field.child    (dimensions.0.score, index stripped mid-path)
      list of scalars -> prefix.field          (tags.0, trailing index stripped)
      map keyed by enum -> one path per key    (no such field today; kept for the next one)
      scalar   -> prefix.field                 (nullable ones included: null is a scalar)
    """

    def walk(fs: list[dict], at: str) -> list[str]:
        out: list[str] = []
        for f in fs:
            path = f"{at}.{f['name']}" if at else f["name"]
            t = f["type"]
            if t == "object" or (t == "list" and f["item"] in s["objects"]):
                out += walk(s["objects"][f["item"]], path)
            elif t == "map":
                out += [f"{path}.{k}" for k in s["enums"][f["key"]]]
            else:
                out.append(path)
        return out

    return walk(owner_fields, prefix)


def analysis_leaf_paths(prefix: str) -> list[str]:
    """Every scalar path a SessionAnalysis document can produce (spec/analysis.v1.json)."""
    s = json.loads(ANALYSIS_SPEC.read_text())
    return spec_leaf_paths(s, s["fields"], prefix)


def live_leaf_paths(prefix: str, *, names: bool = False) -> list[str]:
    """Every scalar path of `live` (LiveState) or, with `names`, of `live_names`
    (LiveNames), walked from spec/live.v1.json."""
    s = json.loads(LIVE_SPEC.read_text())
    return spec_leaf_paths(s, s["objects"]["LiveNames"] if names else s["fields"], prefix)


def main() -> None:
    c = json.loads(SPEC.read_text())
    print("gen_contract.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderSync/Generated/UploadContract.swift", gen_swift(c))
    write(ROOT / "server/builder/contract.py", gen_py(c))
    write(ROOT / "mobile/src/generated/contract.ts", gen_ts(c))
    write(ROOT / "server/builder/quotes_spec.py", gen_quotes_py(c))
    write(ROOT / "mobile/src/generated/quotes.ts", gen_quotes_ts(c))
    # Published as BOTH the top-level names and the expanded leaf paths.
    #
    # The first version published only top-level names, and the verification command on
    # the privacy page, which walks every scalar path with jq, then reported
    # `tokens.input` and `strip_marks[].ms` as "sent but not declared". They are not: they
    # are the insides of declared structured fields. But a verification command that cries
    # leak on correct output is worse than none, because the first person to run it
    # publicly concludes the claim is false.
    #
    # `tool_calls` expands to whatever tool names a session used, so it is published as a
    # wildcard with its allowlist stated separately (`tool_call_keys`, v4).
    #
    # `analysis` is the same trap one level deeper (60-odd nested scalar paths) and it is
    # walked from its own spec rather than listed here, because a hand-kept list would be
    # exactly the kind that goes stale the first time the analysis spec grows. `live` and
    # `live_names` are walked from spec/live.v1.json and `burn` and `title_ids` from the
    # contract's own objects, for the same reason.
    nested = {
        "tokens": ["input", "output", "cache_read", "cache_w5m", "cache_w1h"],
        "strip_marks": ["ms", "k"],
        "models": ["model_id", "output_token_share"],
        "feedback": ["id", "seconds", "count"],
        "tool_calls": ["<allowlisted tool name>"],
    }
    os_ = objects_spec(c)
    leaves: list[str] = []
    for f in fields(c):
        if f["name"] in nested:
            leaves += [f"{f['name']}.{child}" for child in nested[f["name"]]]
        elif f["type"] == "analysis":
            leaves += analysis_leaf_paths(f["name"])
        elif f["type"] == "live":
            leaves += live_leaf_paths(f["name"])
        elif f["type"] == "live_names":
            leaves += live_leaf_paths(f["name"], names=True)
        elif f["type"] == "object":
            leaves += spec_leaf_paths(os_, os_["objects"][f["item"]], f["name"])
        else:
            leaves.append(f["name"])

    write(ROOT / "server/builder/media_spec.py", gen_media_py(c))
    write(ROOT / "mobile/src/generated/media.ts", gen_media_ts(c))

    qs = quotes_spec(c)
    ms = media_spec(c)
    media = c["project_media"]
    write(
        ROOT / "server/builder/static/upload-fields.json",
        json.dumps(
            {
                "version": c["version"],
                "fields": sorted(f["name"] for f in fields(c)),
                "leaf_paths": sorted(leaves),
                "tool_call_keys": tool_call_keys(c),
                "documents": {
                    "quotes": {
                        "route": c["quotes"]["route"],
                        "default": c["quotes"]["default"],
                        "leaf_paths": sorted(spec_leaf_paths(qs, qs["fields"], "")),
                    },
                    # One presign per file of a published ship kit, then its document.
                    "ship_kit": {
                        "route": c["ship_kit"]["route"],
                        "document_route": c["ship_kit"]["document_route"],
                        "default": c["ship_kit"]["default"],
                        "leaf_paths": sorted(f["name"] for f in kit_spec()["objects"]["KitPresign"]),
                        "document_leaf_paths": sorted(
                            spec_leaf_paths(kit_spec(), kit_spec()["objects"]["KitDocument"], "")
                        ),
                    },
                    # One presign per file; the bytes follow to the URL it returns.
                    "project_media": {
                        "route": media["route"],
                        "default": media["default"],
                        "leaf_paths": sorted(spec_leaf_paths(ms, ms["fields"], "")),
                        "content_types": media["content_types"],
                        "caps": media["caps"],
                        "max_lengths": media["max_lengths"],
                        "label_rule": media["label_rule"],
                    },
                },
                "note": (
                    "`fields` are the top-level keys. `leaf_paths` expands every structured "
                    "one (tokens, models, strip_marks, feedback, tool_calls, analysis, live, "
                    "live_names, burn, title_ids, call_tokens) so a scalar-path walk of a real payload "
                    "matches exactly, with list indices stripped. tool_calls keys are tool "
                    "names from the fixed allowlist `tool_call_keys`; unknown and MCP tools "
                    "bucket to mcp_other / other. analysis, live_names and the quotes document "
                    "are opt-in; analysis is shaped by spec/analysis.v1.json and live and "
                    "live_names by spec/live.v1.json. `documents` lists what is uploaded "
                    "outside a session payload, each with its own route and leaf paths: the "
                    "quotes document, and `project_media`, the presign that goes before each "
                    "file of a published project demo (the file itself is a PNG, JPEG or MP4 "
                    "of the stated size and nothing else)."
                ),
            },
            indent=2,
        )
        + "\n",
    )
    write(ROOT / "PRIVACY.md", gen_privacy_md(c))


if __name__ == "__main__":
    main()
