#!/usr/bin/env python3
"""Generate design tokens into Swift and TypeScript.

COLOUR SPACE IS LOAD-BEARING. SwiftUI's bare Color(red:green:blue:) is Display P3 while
react-native-svg takes sRGB hex, so the Mac card would come out visibly more saturated
than the byte-identical phone card. The Swift emitted here is plain sRGB components;
BuilderUI/StripPalette.swift is the only place that turns them into Color, and it always
uses Color(.sRGB, ...).

The spec is validated before anything is written, so a bad edit to design/tokens.json fails
`make gen` instead of shipping: every colour is #RRGGBB with a light and a dark value, the
space scale stays on the 4pt grid, no type role goes under the 11pt floor, and the Bayer
table is exactly what the shader's arithmetic computes (the phone's test checks the
TypeScript port against the same table, so all three agree or the build is red).

The nine hue `spectrum` (the owner's 2026-09-13 override of the one accent rule) is checked
the same way: every tone clears the contrast floor DESIGN-V2-COLOUR-MOTION.md states for its
use, no identity ink sits in the red or green band data owns or within 0.10 OKLab of another
ink or of a data hue, and every mapping names a hue that exists. The TypeScript carries the
whole block; `theme.ts` resolves it (`hue`, `creatureHue`, `cardHue`, `harnessHue`, ...).
"""

from __future__ import annotations

import json
import math
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "design" / "tokens.json"
BANNER = "// GENERATED by scripts/gen_tokens.py from design/tokens.json — DO NOT EDIT."

COLOUR_GROUPS = ("strip", "mark", "surface", "data")
TYPE_ROLES = ("hero", "display", "title", "headline", "body", "row", "meta", "label", "mono")
HEX = re.compile(r"^#[0-9A-F]{6}$")


def hex_to_rgb(h: str) -> tuple[float, float, float]:
    h = h.lstrip("#")
    return tuple(round(int(h[i : i + 2], 16) / 255.0, 6) for i in (0, 2, 4))  # type: ignore[return-value]


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def clean(node):
    """Drop every `_comment` (any key starting with `_`) at every level."""
    if isinstance(node, dict):
        return {k: clean(v) for k, v in node.items() if not k.startswith("_")}
    if isinstance(node, list):
        return [clean(v) for v in node]
    return node


# ─── the ordered-dither threshold, the same arithmetic as the SkSL ─────────────────────


def _fract(x: float) -> float:
    return x - math.floor(x)


def bayer2(x: float, y: float) -> float:
    x, y = math.floor(x), math.floor(y)
    return _fract(x * 0.5 + y * y * 0.75)


def bayer8(x: float, y: float) -> float:
    """0 .. 63/64. Mirrors `b8` in mobile/src/ui/dithering.ts (DITHER_SKSL) line for line."""
    return bayer2(x * 0.25, y * 0.25) * 0.0625 + bayer2(x * 0.5, y * 0.5) * 0.25 + bayer2(x, y)


# ─── the spectrum's measurements: WCAG 2 contrast and OKLab ────────────────────────────


def _linear(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _rgb(h: str) -> tuple[float, float, float]:
    return tuple(_linear(int(h[i : i + 2], 16) / 255) for i in (1, 3, 5))  # type: ignore[return-value]


def contrast(a: str, b: str) -> float:
    la, lb = (0.2126 * r + 0.7152 * g + 0.0722 * b_ for r, g, b_ in (_rgb(a), _rgb(b)))
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def oklab(h: str) -> tuple[float, float, float]:
    r, g, b = _rgb(h)
    l_ = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m_ = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s_ = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b
    l_, m_, s_ = (math.copysign(abs(x) ** (1 / 3), x) for x in (l_, m_, s_))
    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


def oklch_hue(h: str) -> float:
    _, a, b = oklab(h)
    return math.degrees(math.atan2(b, a)) % 360


# The floors DESIGN-V2-COLOUR-MOTION.md 1.1 states. A hue under one of them is a colour a person
# cannot read, or one that turns brown or reads as data, and it fails `make gen` before it ships.
SPECTRUM_TONES = ("dark", "partner", "light", "lightText", "lightPartner")
INK_ON_GROUND = 4.5  # dark on bg and on card; onAccent ink on the dark as a fill
PARTNER_ON_CARD = 3.0  # the dither's middle tone is a mark
PARTNER_STEP = (1.5, 2.6)  # below its ink: enough depth for three levels, never a second colour
LIGHT_MARK = 3.0
LIGHT_TEXT = 4.5
MIN_OKLAB = 0.10  # between any two inks, and between an ink and add, del or the human teal
DATA_BANDS = ((19.0, 42.0), (120.0, 200.0))  # OKLCH hue: red is del and Claude, green is add and you
TOKEN_REFS = ("data.add", "data.del", "surface.textDim", "surface.text")


def spectrum_card_hues(card: dict, alt: dict, archetype_hue: str) -> list[str]:
    """The fifteen as worn when card one wears `archetype_hue`: the rule `theme.cardHue` runs."""
    out = []
    for cid, h in card.items():
        h = archetype_hue if h == "archetype" else h
        if cid in alt and h == archetype_hue:
            h = alt[cid]
        out.append(h)
    return out


def validate_spectrum(t: dict) -> list[str]:
    problems: list[str] = []
    spec = clean(t.get("spectrum", {}))
    hues = spec.get("hues", {})
    if len(hues) != 9:
        problems.append(f"spectrum.hues has {len(hues)} hues; the spectrum is nine")
    bg, card = t["surface"]["bg"]["dark"], t["surface"]["card"]["dark"]
    lbg, lcard = t["surface"]["bg"]["light"], t["surface"]["card"]["light"]
    on_ink = t["surface"]["text"]["light"]
    for name, v in hues.items():
        for tone in SPECTRUM_TONES:
            if not isinstance(v.get(tone), str) or not HEX.match(v[tone]):
                problems.append(f"spectrum.hues.{name}.{tone} is {v.get(tone)!r}, not #RRGGBB (upper case)")
        if any(not isinstance(v.get(k), str) or not HEX.match(v[k]) for k in SPECTRUM_TONES):
            continue
        ink, partner = v["dark"], v["partner"]
        for ground, label in ((bg, "bg"), (card, "card")):
            if contrast(ink, ground) < INK_ON_GROUND:
                problems.append(f"spectrum.hues.{name}.dark is {contrast(ink, ground):.2f}:1 on {label}, under {INK_ON_GROUND}")
        if contrast(on_ink, ink) < INK_ON_GROUND:
            problems.append(f"spectrum.hues.{name}: ink on the fill is {contrast(on_ink, ink):.2f}:1, under {INK_ON_GROUND}")
        if contrast(partner, card) < PARTNER_ON_CARD:
            problems.append(f"spectrum.hues.{name}.partner is {contrast(partner, card):.2f}:1 on card, under {PARTNER_ON_CARD}")
        step = contrast(ink, partner)
        if not PARTNER_STEP[0] <= step <= PARTNER_STEP[1]:
            problems.append(f"spectrum.hues.{name}.partner is {step:.2f}:1 below its ink, outside {PARTNER_STEP}")
        if contrast(v["light"], lbg) < LIGHT_MARK:
            problems.append(f"spectrum.hues.{name}.light is {contrast(v['light'], lbg):.2f}:1 on the light bg, under {LIGHT_MARK}")
        for ground, label in ((lbg, "the light bg"), (lcard, "the light card")):
            if contrast(v["lightText"], ground) < LIGHT_TEXT:
                problems.append(f"spectrum.hues.{name}.lightText is {contrast(v['lightText'], ground):.2f}:1 on {label}, under {LIGHT_TEXT}")
        h = oklch_hue(ink)
        for lo, hi in DATA_BANDS:
            if lo <= h <= hi:
                problems.append(f"spectrum.hues.{name}.dark sits at OKLCH hue {h:.1f}, inside the band data owns ({lo:g} to {hi:g})")
    inks = {k: v["dark"] for k, v in hues.items() if isinstance(v.get("dark"), str) and HEX.match(v["dark"])}
    names = list(inks)
    data = {"data.add": t["data"]["add"]["dark"], "data.del": t["data"]["del"]["dark"], "strip.human_edit": t["strip"]["human_edit"]["dark"]}
    for i, a in enumerate(names):
        for b in names[i + 1 :]:
            dist = math.dist(oklab(inks[a]), oklab(inks[b]))
            if dist < MIN_OKLAB:
                problems.append(f"spectrum: {a} and {b} are {dist:.3f} apart in OKLab, under {MIN_OKLAB}")
        for label, hexv in data.items():
            dist = math.dist(oklab(inks[a]), oklab(hexv))
            if dist < MIN_OKLAB:
                problems.append(f"spectrum: {a} is {dist:.3f} from {label}, under {MIN_OKLAB}: it would read as data")

    def hue_ref(path: str, value) -> None:
        if value not in hues:
            problems.append(f"spectrum.{path} names {value!r}, which is not one of the nine hues")

    creature = spec.get("creature", {})
    for k, v in creature.items():
        hue_ref(f"creature.{k}", v)
    if creature.get("bit") != "amber":
        problems.append("spectrum.creature.bit must be amber: the mascot is the brand")
    if sorted(creature.values()) != sorted(hues):
        problems.append("spectrum.creature must give each of the nine hues to exactly one creature")
    ring = spec.get("crew", {}).get("ring", [])
    animals = sorted(k for k in creature if k != "bit")
    if sorted(ring) != animals or len(ring) != 8:
        problems.append(f"spectrum.crew.ring must be the eight animals once each (not Bit): {ring}")
    for k, v in spec.get("harness", {}).items():
        hue_ref(f"harness.{k}", v)
        if v == "amber":
            problems.append(f"spectrum.harness.{k} is amber: amber is Builda's, never a harness's")
    for k, v in spec.get("archetype", {}).items():
        hue_ref(f"archetype.{k}", v)
    for k, v in spec.get("dimension", {}).items():
        hue_ref(f"dimension.{k}", v)
    for k, v in spec.get("verdict", {}).items():
        if v not in TOKEN_REFS:
            problems.append(f"spectrum.verdict.{k} is {v!r}; a verdict is a state colour, one of {TOKEN_REFS}")
    cards, alt = spec.get("card", {}), spec.get("cardAlt", {})
    if len(cards) != 15 or list(cards.values()).count("archetype") != 1:
        problems.append("spectrum.card must be the fifteen Wrapped cards, one of them wearing 'archetype'")
    for k, v in cards.items():
        if v != "archetype":
            hue_ref(f"card.{k}", v)
    for k, v in alt.items():
        hue_ref(f"cardAlt.{k}", v)
        if k not in cards:
            problems.append(f"spectrum.cardAlt.{k} is not a card")
    for arch in sorted(set(spec.get("archetype", {}).values())):
        worn = spectrum_card_hues(cards, alt, arch)
        for i in range(len(worn)):
            for j in (i + 1, i + 2):
                if j < len(worn) and worn[i] == worn[j]:
                    problems.append(f"spectrum.card: with card one in {arch}, cards {i + 1} and {j + 1} are both {worn[i]}")
    return problems


# ─── validation ────────────────────────────────────────────────────────────────────────


def validate(t: dict) -> None:
    problems: list[str] = []

    for group in COLOUR_GROUPS:
        for name, pair in clean(t[group]).items():
            for scheme in ("light", "dark"):
                v = pair.get(scheme)
                if not isinstance(v, str) or not HEX.match(v):
                    problems.append(f"{group}.{name}.{scheme} is {v!r}, not #RRGGBB (upper case)")

    for scheme in ("light", "dark"):
        levels = t["graph"]["levels"][scheme]
        if len(levels) != 6 or not all(HEX.match(v) for v in levels):
            problems.append(f"graph.levels.{scheme} must be six #RRGGBB values")

    space = clean(t["space"])
    for name, v in space.items():
        if v % 4 != 0:
            problems.append(f"space.{name} = {v} is off the 4pt grid")
    values = list(space.values())
    if values != sorted(values) or len(set(values)) != len(values):
        problems.append("space must be strictly ascending, one name per step")

    radius = clean(t["radius"])
    scale = [radius[k] for k in ("xs", "sm", "md", "lg", "pill")]
    if scale != sorted(scale):
        problems.append("radius xs < sm < md < lg < pill")
    if radius["md"] - radius["xs"] != radius["sm"]:
        problems.append("radius: concentric rule broken (md - xs must equal sm: 18 - 6 = 12)")

    roles = clean(t["type"])
    if tuple(roles) != TYPE_ROLES:
        problems.append(f"type roles must be exactly {TYPE_ROLES}, in that order")
    for name, role in roles.items():
        if role["size"] < 11:
            problems.append(f"type.{name} is {role['size']}pt; nothing goes under the 11pt floor")
        if role["weight"] not in range(100, 1000, 100):
            problems.append(f"type.{name}.weight {role['weight']} is not 100..900")
        if role["maxScale"] < 1:
            problems.append(f"type.{name}.maxScale must be >= 1 (1 means fixed)")

    problems.extend(validate_spectrum(t))

    table = t["dither"]["bayer8"]
    if sorted(v for row in table for v in row) != list(range(64)):
        problems.append("dither.bayer8 must hold each of 0..63 exactly once")
    for y in range(8):
        for x in range(8):
            want = round(bayer8(x, y) * 64)
            if table[y][x] != want:
                problems.append(
                    f"dither.bayer8[{y}][{x}] = {table[y][x]} but the shader computes {want}; "
                    "the table and the SkSL would dither differently"
                )

    if problems:
        raise SystemExit("design/tokens.json is invalid:\n  " + "\n  ".join(problems))


# ─── Swift ─────────────────────────────────────────────────────────────────────────────


def swift_rgb(name: str, pair: dict) -> str:
    lr, lg, lb = hex_to_rgb(pair["light"])
    dr, dg, db = hex_to_rgb(pair["dark"])
    return (
        f'    public static let {name} = SRGBPair(\n'
        f'        light: SRGB(r: {lr}, g: {lg}, b: {lb}),  // {pair["light"]}\n'
        f'        dark:  SRGB(r: {dr}, g: {dg}, b: {db})   // {pair["dark"]}\n'
        f'    )'
    )


def swift_num(v: float) -> str:
    return repr(float(v))


def gen_swift(t: dict) -> str:
    def group(key: str, mark: str | None = None) -> str:
        entries = clean(t[key])
        body = "\n".join(swift_rgb(name, pair) for name, pair in entries.items())
        return f"    // MARK: {mark or key}\n{body}"

    graph_light = ", ".join(
        "SRGB(r: {}, g: {}, b: {})".format(*hex_to_rgb(h)) for h in t["graph"]["levels"]["light"]
    )
    graph_dark = ", ".join(
        "SRGB(r: {}, g: {}, b: {})".format(*hex_to_rgb(h)) for h in t["graph"]["levels"]["dark"]
    )

    def lets(key: str, indent: str = "        ") -> str:
        return "\n".join(f"{indent}public static let {k} = {swift_num(v)}" for k, v in clean(t[key]).items())

    roles = "\n".join(
        f"        public static let {name} = TypeRoleSpec("
        f"size: {swift_num(r['size'])}, weight: {r['weight']}, tracking: {swift_num(r['tracking'])}, "
        f"line: {swift_num(r['line'])}, maxScale: {swift_num(r['maxScale'])}, "
        f"monospaced: {'true' if r.get('design') == 'monospaced' else 'false'})"
        for name, r in clean(t["type"]).items()
    )

    shadow = clean(t["shadow"])["float"]
    sr, sg, sb = hex_to_rgb(shadow["color"])
    dither = clean(t["dither"])
    bayer_rows = ",\n".join(
        "            " + ", ".join(f"{v:2d}" for v in row) for row in dither["bayer8"]
    )

    card = t["card"]
    return f"""{BANNER}

import Foundation

/// An sRGB colour. NOT Display P3 — see the note in design/tokens.json. The only place
/// these become SwiftUI Colors is BuilderUI/StripPalette.swift, via Color(.sRGB, ...).
public struct SRGB: Sendable, Equatable {{
    public let r: Double, g: Double, b: Double
    public init(r: Double, g: Double, b: Double) {{ self.r = r; self.g = g; self.b = b }}
}}

public struct SRGBPair: Sendable, Equatable {{
    public let light: SRGB, dark: SRGB
    public init(light: SRGB, dark: SRGB) {{ self.light = light; self.dark = dark }}
    public func resolve(dark isDark: Bool) -> SRGB {{ isDark ? dark : light }}
}}

/// One of the nine type roles. System font; `monospaced` means SF Mono. `maxScale` is the
/// Dynamic Type ceiling, 1 meaning fixed size.
public struct TypeRoleSpec: Sendable, Equatable {{
    public let size: Double, weight: Int, tracking: Double, line: Double, maxScale: Double
    public let monospaced: Bool
    public init(size: Double, weight: Int, tracking: Double, line: Double, maxScale: Double, monospaced: Bool) {{
        self.size = size; self.weight = weight; self.tracking = tracking; self.line = line
        self.maxScale = maxScale; self.monospaced = monospaced
    }}
    /// Line height in points.
    public var lineHeight: Double {{ (size * line).rounded() }}
}}

public enum DesignTokens {{

{group("strip")}

{group("mark")}

{group("surface")}

{group("data", "data hues. Never chrome, never a fill behind text. The third, human, is human_edit.")}

    // MARK: graph — coloured by ACTIVE HOURS, absolute buckets (see Tuning.graphHourBuckets)
    public static let graphLight: [SRGB] = [{graph_light}]
    public static let graphDark:  [SRGB] = [{graph_dark}]

    // MARK: layout
    public enum Space {{
{lets("space")}
    }}
    public enum Layout {{
{lets("layout")}
    }}
    public enum Radius {{
{lets("radius")}
    }}

    // MARK: type
    public enum TypeRole {{
{roles}
    }}

    // MARK: elevation. Exactly one shadow, for things that float over content.
    public enum Shadow {{
        public static let x = {swift_num(shadow["x"])}
        public static let y = {swift_num(shadow["y"])}
        /// CSS blur radius. SwiftUI's `.shadow(radius:)` is roughly half of it.
        public static let blur = {swift_num(shadow["blur"])}
        public static let color = SRGB(r: {sr}, g: {sg}, b: {sb})  // {shadow["color"]}
        public static let opacity = {swift_num(shadow["opacity"])}
    }}

    // MARK: dither. A cell is ink when its value (0..1) is > bayer8[y * 8 + x] / 64.
    public enum Dither {{
        public static let cell = {swift_num(dither["cell"])}
        public static let halftoneAngle = {swift_num(dither["halftoneAngle"])}
        public static let halftoneRadius = {swift_num(dither["halftoneRadius"])}
        public static let bayer8: [UInt8] = [
{bayer_rows}
        ]
    }}

    public enum Card {{
        public static let landscape = (w: {card["landscape"]["w"]}.0, h: {card["landscape"]["h"]}.0)
        public static let portrait  = (w: {card["portrait"]["w"]}.0,  h: {card["portrait"]["h"]}.0)
        public static let scale     = {float(card["scale"])}
    }}
}}
"""


# ─── TypeScript ────────────────────────────────────────────────────────────────────────


def css_shadow(s: dict) -> str:
    r, g, b = (int(s["color"][i : i + 2], 16) for i in (1, 3, 5))
    return f"{s['x']} {s['y']}px {s['blur']}px rgba({r},{g},{b},{s['opacity']})"


def gen_ts(t: dict) -> str:
    tokens = clean(t)
    shadow = css_shadow(tokens["shadow"]["float"])
    return f"""{BANNER}

export const tokens = {json.dumps(tokens, indent=2)} as const;

export type Scheme = 'light' | 'dark';

/** All values are sRGB hex, which is what react-native-svg expects. */
export function pick(pair: {{ light: string; dark: string }}, scheme: Scheme): string {{
  return pair[scheme];
}}

/** The one shadow token as a React Native `boxShadow` string, derived from `shadow.float`. */
export const FLOAT_SHADOW = '{shadow}';
"""


def main() -> None:
    t = json.loads(SPEC.read_text())
    validate(t)
    print("gen_tokens.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderModel/Generated/DesignTokens.swift", gen_swift(t))
    write(ROOT / "mobile/src/generated/tokens.ts", gen_ts(t))


if __name__ == "__main__":
    main()
