#!/usr/bin/env python3
"""
The builder's creatures as text grids for the Mac: the notch island's face and the agent rail.

The phone animates the pack from `mobile/src/pixel/animals.ts` and Bit from `sprites.ts`; the
widget gets 1-bit PNGs from `gen_widget_creatures.py`. The Mac draws the SAME cells itself, on
a Canvas, because its face is a state machine (the notch kit's glow, eye shapes, breath and
blink) and a template PNG cannot change the height of its own eyes. So this writes the cells,
not pictures, into BuilderKit:

  Packages/BuilderKit/Sources/BuilderUI/Generated/CreatureGrids.swift

Each creature gets its REST pose (the first frame of its loop) and its BREATH (the second), the
pack's own "idle is breath, blink and one gesture" (animals.ts rule 7): the island alternates
the two on the breathe clock rather than scaling a pixel icon, which the pack forbids ("no scale
breath: those put a pixel icon between device pixels"). Bit's sleeping pose is its LAST frame,
for the same reason the widget takes it: the z trail has fully risen, so it reads as asleep.

Ink and hole follow `gen_widget_creatures.one_bit`, the one rule for turning the pack into one
ink, imported rather than restated. Text only, so unlike the PNG scripts this is deterministic
and runs in `make gen` and its `git diff --exit-code` gate.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import gen_widget_creatures as w  # noqa: E402

ROOT = HERE.parent
OUT = ROOT / "Packages/BuilderKit/Sources/BuilderUI/Generated/CreatureGrids.swift"
FRAMES_TS = w.PIXEL / "frames.ts"


def rows(cells: list[list[bool]]) -> list[str]:
    return ["".join("#" if c else "." for c in row) for row in cells]


def poses() -> dict[str, tuple[list[str], list[str]]]:
    """{id: (rest, breath)} in the pack's order, then Bit and Bit asleep."""
    order = w.literal(w.ANIMALS_TS, "ANIMALS")
    table = w.literal(w.ANIMALS_TS, "ANIMAL_FRAMES")
    out: dict[str, tuple[list[str], list[str]]] = {}

    def resolve(value, where: str, glyphs) -> list[str]:
        # A loop lists its frames by name (`[CAT_REST, CAT_BREATH, ...]`): follow the name.
        if isinstance(value, w.Ident):
            where = f"{where} -> {value.name}"
            value = w.literal(w.ANIMALS_TS, value.name)
        return w.frame(value, where, glyphs)

    for animal in order:
        frames = w.literal(w.ANIMALS_TS, table[animal].name)
        if len(frames) < 2:
            raise w.ParseError(f"animals.ts: {animal} has no breath frame")
        rest = resolve(frames[0], f"animals.ts {animal}[0]", w.ANIMAL_GLYPHS)
        breath = resolve(frames[1], f"animals.ts {animal}[1]", w.ANIMAL_GLYPHS)
        out[animal] = (rows(w.one_bit(rest, False)), rows(w.one_bit(breath, False)))

    sprites = w.literal(w.SPRITES_TS, "SPRITES")
    idle = sprites["idle"]
    rest = w.frame(w.literal(w.SPRITES_TS, idle[0].name), "sprites.ts idle[0]", w.BIT_GLYPHS)
    breath = w.frame(w.literal(w.SPRITES_TS, idle[1].name), "sprites.ts idle[1]", w.BIT_GLYPHS)
    out["bit"] = (rows(w.one_bit(rest, True)), rows(w.one_bit(breath, True)))
    sleeping = sprites["sleeping"]
    asleep = w.frame(w.literal(w.SPRITES_TS, sleeping[-1].name), "sprites.ts sleeping[-1]", w.BIT_GLYPHS)
    out["bit-sleeping"] = (rows(w.one_bit(asleep, True)), rows(w.one_bit(asleep, True)))
    return out


def eyes() -> list[tuple[int, int]]:
    """frames.ts `EYES`, read from its own declaration. The literal reader only knows strings
    and names, and these are numbers, so the block is read on its own: from the declaration to
    the `];` that closes it, every `[x, y]` pair in order."""
    src = FRAMES_TS.read_text()
    m = re.search(r"export const EYES\b[^=]*=\s*\[(.*?)\n\];", src, re.S)
    if not m:
        raise SystemExit("frames.ts: no `export const EYES = [...]`")
    body = re.sub(r"//[^\n]*", "", m.group(1))
    return [(int(x), int(y)) for x, y in re.findall(r"\[\s*(\d+)\s*,\s*(\d+)\s*\]", body)]


def swift(p: dict[str, tuple[list[str], list[str]]], eye_cells: list[tuple[int, int]]) -> str:
    def grid(r: list[str]) -> str:
        return "[\n" + "\n".join(f'            "{row}",' for row in r) + "\n        ]"

    rest = "\n".join(f'        "{k}": {grid(v[0])},' for k, v in p.items())
    breath = "\n".join(f'        "{k}": {grid(v[1])},' for k, v in p.items())
    eyes_s = ", ".join(f"(x: {x}, y: {y})" for x, y in eye_cells)
    ids = ", ".join(f'"{k}"' for k in p)
    return f"""// GENERATED by scripts/gen_mac_creatures.py from mobile/src/pixel/animals.ts, sprites.ts and
// frames.ts. DO NOT EDIT: re-run `make gen`.
//
// `#` is ink and `.` is a hole or empty, by gen_widget_creatures.one_bit's rule. Rows run top to
// bottom, 16 cells each.

public enum CreatureGrids {{
    public static let size = {w.GRID}

    /// Every id drawn here, in the pack's order, then Bit and Bit asleep.
    public static let ids: [String] = [{ids}]

    /// The eight eye cells (x, y), the same in all nine creatures (frames.ts `EYES`). The face
    /// draws its eyes over these, so an eye can flatten, close or smile on any creature.
    public static let eyes: [(x: Int, y: Int)] = [{eyes_s}]

    /// The rest pose: the first frame of each loop, and every still image of the creature.
    public static let rest: [String: [String]] = [
{rest}
    ]

    /// The breath: the second frame of each loop, at most four cells from the rest pose.
    public static let breath: [String: [String]] = [
{breath}
    ]
}}
"""


def main() -> None:
    p = poses()
    e = eyes()
    if len(e) != 8:
        raise SystemExit(f"frames.ts EYES has {len(e)} cells, want 8")
    for k, (rest, _) in p.items():
        if k == "bit-sleeping":
            continue
        for x, y in e:
            if rest[y][x] != ".":
                raise SystemExit(f"{k}: eye cell ({x},{y}) is ink in the rest pose; the face would draw over the body")
    text = swift(p, e)
    print("gen_mac_creatures.py")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    old = OUT.read_text() if OUT.exists() else None
    if old != text:
        OUT.write_text(text)
        print(f"  wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
