#!/usr/bin/env python3
"""mobile/assets/harness/*.svg -> mobile/src/pixel/harnessLogos.ts. Never hand-edit the output.

The owner supplied these marks (2026-09-13: "use these icons for each option"). Each SVG is a
24x24 viewBox; the monochrome ones fill with currentColor, which SvgXml's `color` prop sets, so
they follow the text colour. The -color ones keep their brand colours. Aider has no mark and
keeps its pixel glyph (src/pixel/harness.ts).
"""
from __future__ import annotations

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "mobile/assets/harness"
OUT = ROOT / "mobile/src/pixel/harnessLogos.ts"

# wire harness id -> svg file (stem)
MAP = {
    "claude_code": "claude-color",
    "codex": "codex-color",
    "cursor_ide": "cursor",
    "cursor_agent": "cursor",
    "gemini_cli": "gemini-color",
    "cline": "cline",
    "opencode": "opencode",
}


def clean(svg: str) -> str:
    svg = re.sub(r"<title>.*?</title>", "", svg, flags=re.S)
    svg = re.sub(r'\s(height|width)="1em"', "", svg)
    svg = re.sub(r'\sstyle="[^"]*"', "", svg)
    return re.sub(r"\s+", " ", svg).strip()


def main() -> None:
    entries = {}
    for wire, stem in MAP.items():
        raw = (SRC / f"{stem}.svg").read_text()
        entries[wire] = {"xml": clean(raw), "mono": "currentColor" in raw}
    body = json.dumps(entries, indent=2, sort_keys=True)
    OUT.write_text(
        "// GENERATED by scripts/gen_harness_logos.py from mobile/assets/harness/*.svg.\n"
        "// Never hand-edit. The owner supplied these marks (2026-09-13).\n\n"
        "export type HarnessLogo = { xml: string; mono: boolean };\n\n"
        f"export const HARNESS_LOGOS: Record<string, HarnessLogo> = {body};\n"
    )
    print("wrote", OUT, len(entries), "logos")


if __name__ == "__main__":
    main()
