#!/usr/bin/env python3
"""Generate the phone's copy from the engine's own tables, and the fixtures that pin it.

docs/overnight-integration.md 1.5: the report and the session upload carry no rendered
string. Ids, numbers and refusal codes travel; the phone writes every question, answer,
sentence and refusal. So the words have to reach the phone some other way, and the rule is
the one the specs already follow: ONE definition, generated into every language that needs
it, never retyped. The definitions are Python tables in `analysis/`; this script reads them
and writes three files, all committed and all `git diff --exit-code`'d by `make check-gen`:

  mobile/src/generated/copy.ts         every catalog and template the phone renders from
  spec/fixtures/wrapped/cards.json     every Wrapped card as Python renders it, beside the
                                       wire card the phone gets: every card answered and
                                       every refusal code, from analysis/tests/corpus_fixture
  spec/fixtures/burn/session.json      the session upload's `burn` block beside the plain
                                       English summary `burn.explain` says about the same
                                       session, from analysis/tests/burn_fixture
  spec/fixtures/projects/sentences.json  every sentence `analysis/projects.py` words (the
                                       comparisons, the stage, the week, the refusals) beside
                                       the wire input it was worded from, from
                                       analysis/tests/projects_fixture (docs/projects.md)
  spec/fixtures/projects/block.json    a whole projects block as the report carries it, two
                                       projects and a sitting in no repository, for the
                                       phone's view model tests
  spec/fixtures/digest/reads_only.json  shell commands beside whether each, whole, can only
                                       read (`digest.shell_reads_only`), which the Swift twin
                                       `ShellFileEffect.readsOnly` is held to, from
                                       analysis/tests/reads_only_fixture

The sentences WITH numbers are hand ported on the phone (`mobile/src/copy/*.ts`) and the
two fixtures are what hold each port to Python, as `spec/fixtures/strip_*.json` hold the
strip decoder. No dash in any string a person reads (CLAUDE.md): every string this script
writes goes through `plain.has_dash`, and a dash stops the build here rather than on a
screen.

Run from the repository root (`make gen`); it imports `analysis`, which needs no
dependency outside the standard library.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from analysis import burn, live, plain, pricing, report_blocks, vocab, wrapped  # noqa: E402
from analysis import contributions as co  # noqa: E402
from analysis import profile as pf  # noqa: E402
from analysis import projects as pj  # noqa: E402
from analysis.tests import burn_fixture, corpus_fixture, projects_fixture, reads_only_fixture  # noqa: E402
from capture import harnesses  # noqa: E402

COPY_TS = ROOT / "mobile/src/generated/copy.ts"
CARDS_JSON = ROOT / "spec/fixtures/wrapped/cards.json"
BURN_JSON = ROOT / "spec/fixtures/burn/session.json"
PROJECTS_JSON = ROOT / "spec/fixtures/projects/sentences.json"
PROJECT_BLOCK_JSON = ROOT / "spec/fixtures/projects/block.json"
READS_ONLY_JSON = ROOT / "spec/fixtures/digest/reads_only.json"

#: No dash in the banner either: the phone's catalog test runs `hasDash` over this whole file.
BANNER = "// GENERATED by scripts/gen_copy.py from the tables in analysis/. DO NOT EDIT."


def write(path: pathlib.Path, text: str) -> None:
    """Write only when the bytes change, so a second `make gen` writes nothing."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def strings(obj):
    if isinstance(obj, str):
        yield obj
    elif isinstance(obj, dict):
        for v in obj.values():
            yield from strings(v)
    elif isinstance(obj, (list, tuple)):
        for v in obj:
            yield from strings(v)


def no_dash(where: str, obj) -> None:
    for s in strings(obj):
        if plain.has_dash(s):
            raise SystemExit(f"gen_copy.py: {where} has a dash, which no person may read: {s!r}")


# ---------------------------------------------------------------------------- copy.ts
def tables() -> list[tuple[str, str, object]]:
    """(name, doc, value) for every table the phone renders from, in the order written.
    The names are the ones `mobile/src/copy/catalog.ts` already uses, so it can re-export
    this file without a single importer changing."""
    return [
        # ------------------------------------------------------------- analysis/wrapped.py
        ("QUESTIONS", "`wrapped.QUESTIONS`: the brief's questions, minus Paxel's dashes.", wrapped.QUESTIONS),
        ("ARCHETYPE_DISPLAY", "`wrapped.ARCHETYPE_DISPLAY`: the six archetypes and the generalist.", wrapped.ARCHETYPE_DISPLAY),
        ("WORK_STYLE_DISPLAY", "`wrapped.WORK_STYLE_DISPLAY`, in the order the rules run.", wrapped.WORK_STYLE_DISPLAY),
        ("KINDS", "`wrapped.KINDS`: the commit kinds, in the order ties break.", list(wrapped.KINDS)),
        ("KIND_NOUN", "`wrapped._KIND_NOUN`: each kind's noun, one and many.", {k: list(v) for k, v in wrapped._KIND_NOUN.items()}),
        ("ROLE_DISPLAY", "`wrapped.ROLE_DISPLAY`: the kind of work card's answer on its file role fallback.", wrapped.ROLE_DISPLAY),
        ("ROLE_WORD", "`wrapped.ROLE_WORD`: the word before \"files\" in that card's sentence.", wrapped.ROLE_WORD),
        ("LOCAL_CARDS", "`wrapped.LOCAL_CARDS`: every number on these is a reading of what somebody typed.", [c for c in wrapped.CARD_IDS if c in wrapped.LOCAL_CARDS]),
        ("QUOTE_CARDS", "`wrapped.QUOTE_CARDS`: the cards that can quote a prompt (contract v4 `quotes`).", list(wrapped.QUOTE_CARDS)),
        ("WITH_YOU", "`wrapped.WITH_YOU`: the one phrase every card says attended time in.", wrapped.WITH_YOU),
        ("LOOKBACK_MINUTES", "`round(contributions.LOOKBACK_SEC / 60)`: a commit this long before a session still counts as assisted.", round(co.LOOKBACK_SEC / 60)),
        ("SHORT_PROMPT_WORDS", "`profile.SHORT_PROMPT_WORDS`: a median prompt under this is terse.", pf.SHORT_PROMPT_WORDS),
        ("PROMPT_BRIEF_WORDS", "`wrapped.PROMPT_BRIEF_WORDS`: a median prompt at or past this is a written brief.", wrapped.PROMPT_BRIEF_WORDS),
        ("REFUSALS", "`wrapped.REFUSALS`: every reason a card is refused, as its code and the ONE template it is worded from (`profile.fill`: `{n}` and `{needed}` are the card's own, `{name:noun}` agrees the noun, a mapping picks `zero`, `one` or `other` by `n`).", wrapped.REFUSALS),
        ("KIND_REFUSALS", "`wrapped.KIND_REFUSALS`: the commit labels' half of `neither_kind_basis`, keyed by `extras.commit_refusal`.", wrapped.KIND_REFUSALS),
        ("REFUSAL_CONSTANTS", "`wrapped.REFUSAL_CONSTANTS`: numbers a refusal names that no card carries.", wrapped.REFUSAL_CONSTANTS),
        # ------------------------------------------------------------- analysis/profile.py
        ("BARREN_REFUSALS", "`profile.BARREN_REFUSALS`: why the corpus burn share is refused, by `burn.reason` (`{n}` sessions with counts, `{needed}` the floor).", pf.BARREN_REFUSALS),
        ("SPEND_REFUSALS", "`profile.SPEND_REFUSALS`: why the dollars are refused, by `money.reason` (`{unpriced_sessions}`).", pf.SPEND_REFUSALS),
        # ------------------------------------------------------------- analysis/vocab.py
        ("TERMS", "`vocab.CATALOG`, in catalog order: each glossary term's word and one line definition.", {t.id: {"word": t.word, "definition": t.definition} for t in vocab.CATALOG}),
        ("STACK_NAMES", "`vocab.STACK`, in catalog order: each stack item's name.", {s.id: s.name for s in vocab.STACK}),
        ("VOCAB_REFUSALS", "The glossary's refusal, by `vocab.reason` (`report_blocks.VOCAB_REFUSALS`, inverted).", {v: k for k, v in report_blocks.VOCAB_REFUSALS.items()}),
        ("STACK_REFUSALS", "The stack's refusal, by `stack.reason` (`report_blocks.STACK_REFUSALS`, inverted).", {v: k for k, v in report_blocks.STACK_REFUSALS.items()}),
        # ------------------------------------------------------------- analysis/burn.py
        ("CAUSE_SENTENCES", "`burn._CAUSE_SENTENCES`: the phrase each cause adds to \"The most expensive stretch cost {cost} tokens, {share} of it {phrase}, and {verdict}.\"", burn._CAUSE_SENTENCES),
        ("CAUSE_SENTENCES_ONE", "`burn._CAUSE_SENTENCES_ONE`: where the count is exactly one.", burn._CAUSE_SENTENCES_ONE),
        ("REPEAT_SENTENCES", "`burn._REPEAT_SENTENCES`: `repeated_call` by what repeated (`burn.repeat` on the wire).", burn._REPEAT_SENTENCES),
        ("UNREADABLE_VERDICT", "`burn.UNREADABLE_VERDICT`: a stretch whose work the transcript cannot see.", burn.UNREADABLE_VERDICT),
        ("CONTEXT_REPLAY_MIN_SHARE", "`burn.CONTEXT_REPLAY_MIN_SHARE`: the cache share that earns its own sentence.", burn.CONTEXT_REPLAY_MIN_SHARE),
        ("SAY_SHARE_AT", "`burn.SAY_SHARE_AT`: any other share worth a sentence.", burn.SAY_SHARE_AT),
        ("USAGE_READERS", "`burn.USAGE_READERS`: the harnesses whose token counts burn reads; any other is \"not shown for this tool yet\".", sorted(burn.USAGE_READERS)),
        ("HARNESS_ANALYSIS_NAME", "`capture.harnesses._ANALYSIS_NAME`: a session's `harness` as the upload spells it, to the engine's name for it, where the two differ. `USAGE_READERS` is in the engine's names, so a session's harness is mapped before it is asked.", dict(sorted(harnesses._ANALYSIS_NAME.items()))),
        ("MIN_SEGMENTS_FOR_SPIKES", "`burn.MIN_SEGMENTS_FOR_SPIKES`: stretches a median needs before any is called a spike.", burn.MIN_SEGMENTS_FOR_SPIKES),
        # ------------------------------------------------------------- analysis/pricing.py
        ("FAMILIES", "`pricing.FAMILIES`, keyed by the price table key (`priced_model`): the name a person says.", {k: pricing.family(k) for k in pricing.PRICES}),
        ("PRICES_READ_ON", "`pricing.PRICES_READ_ON`: the day the price table was read.", pricing.PRICES_READ_ON.isoformat()),
        ("PRICE_STALE_DAYS", "`pricing.PRICE_STALE_DAYS`: past this the phone says the prices may have moved.", pricing.PRICE_STALE_DAYS),
        # ------------------------------------------------------------- analysis/live.py
        ("DECISION_SENTENCES", "`live.DECISION_SENTENCES`: the hard to undo things, said without a name.", live.DECISION_SENTENCES),
        # ------------------------------------------------------------- analysis/plain.py
        ("ROLES", "`plain.ROLES`: every file role, in the order ties break.", list(plain.ROLES)),
        ("ROLE_NOUN", "`plain.ROLE_NOUN`: each role as (one, \"{n} many\", the whole collection).", {k: list(v) for k, v in plain.ROLE_NOUN.items()}),
        # ------------------------------------------------------------- analysis/projects.py
        ("PROJECT_CARDS", "`projects.PROJECT_CARDS`: the Wrapped cards a project carries, in deck order.", list(pj.PROJECT_CARDS)),
        ("PROJECT_STAGE_DISPLAY", "`projects.STAGE_DISPLAY`: a project's stage in two words.", pj.STAGE_DISPLAY),
        ("PROJECT_STAGE_SENTENCES", "`projects.STAGE_SENTENCES`: by `stage_rule` (`{n}` the days the rule read, `{prior}`, `{cadence_days}`).", pj.STAGE_SENTENCES),
        ("PROJECT_LAST_SESSION", "`projects.LAST_SESSION`: by `days_since_last`.", pj.LAST_SESSION),
        ("PROJECT_MOMENTUM", "`projects.MOMENTUM_SENTENCES`: by `direction`, or by `reason` on a refusal (`{move}` a share said by `shareWords`).", pj.MOMENTUM_SENTENCES),
        ("PROJECT_COMPARISONS", "`projects.COMPARISONS`: each metric's title, how its values are said, how it is compared and its sentences (`{high}`, `{low}` the projects, `{times}` by `timesWords`).", pj.COMPARISONS),
        ("PROJECT_COMPARISON_REFUSALS", "`projects.COMPARISON_REFUSALS`: by a comparison's `reason`.", pj.COMPARISON_REFUSALS),
        ("PROJECT_REFUSALS", "`projects.PROJECT_REFUSALS`: why a project's number is null, by code (`{n}` and `{needed}` from the block).", pj.PROJECT_REFUSALS),
        ("PROJECT_CONSTANTS", "`projects.PROJECT_CONSTANTS`: numbers a project screen names that no block carries.", pj.PROJECT_CONSTANTS),
    ]


def ts_value(v, indent: int = 0) -> str:
    """A JSON literal is a TypeScript literal; objects and lists one entry a line."""
    pad = "  " * (indent + 1)
    if isinstance(v, dict):
        if not v:
            return "{}"
        body = ",\n".join(f"{pad}{json.dumps(k)}: {ts_value(x, indent + 1)}" for k, x in v.items())
        return "{\n" + body + ",\n" + "  " * indent + "}"
    if isinstance(v, list) and any(isinstance(x, (dict, list)) for x in v):
        body = ",\n".join(f"{pad}{ts_value(x, indent + 1)}" for x in v)
        return "[\n" + body + ",\n" + "  " * indent + "]"
    return json.dumps(v, ensure_ascii=False)


def gen_ts() -> str:
    parts = [
        BANNER,
        "/**",
        " * Every catalog and template the phone renders from, read out of the engine's own",
        " * tables (docs/overnight-integration.md 1.5). The report and the session upload carry",
        " * ids, numbers and refusal codes; these are the words. Never retype one: change the",
        " * Python table and run `make gen`. `spec/fixtures/wrapped/cards.json` and",
        " * `spec/fixtures/burn/session.json` pin the phone's sentences to Python's.",
        " */",
        "",
    ]
    names = []
    for name, doc, value in tables():
        no_dash(name, value)
        names.append(name)
        parts.append(f"/** {doc} */")
        parts.append(f"export const {name} = {ts_value(value)} as const;")
        parts.append("")
    parts.append("/** Every table above, as one object (`COPY.REFUSALS`, `COPY.TERMS`, ...). */")
    parts.append("export const COPY = {")
    parts.extend(f"  {n}," for n in names)
    parts.append("} as const;")
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------- the cards
def card_entries() -> list[dict]:
    """Every card of every `corpus_fixture.scenarios()` corpus, as the phone gets it (the
    report's `ReportWrappedCard`) beside what Python says about it. A LOCAL card answered
    carries the quote the phone would have (`wrapped.quotes_upload`) and the offset its
    clock is said in; without a quote the phone shows the card as local and says nothing,
    so its display and sentence are null here too. Repeats are dropped."""
    out: list[dict] = []
    seen: set[str] = set()
    for sc in corpus_fixture.scenarios():
        result = wrapped.wrapped(sc.facts, sc.sessions, **sc.kw)
        quotes = {
            q["card"]: q
            for q in wrapped.quotes_upload(result, generated_at=corpus_fixture.T0)["quotes"]
        }
        tz_of = {s.session_id: s.tz_offset_minutes for s in sc.sessions}
        for c in result["cards"]:
            wire_card = report_blocks.wrapped_card(wrapped.wire({"cards": [c], "sample": {}})["cards"][0])
            local = c["id"] in wrapped.LOCAL_CARDS
            quote = quotes.get(c["id"]) if local and c["reason"] is None else None
            answered = c["reason"] is None
            shown = answered and (not local or quote is not None)
            entry = {
                "scenario": sc.name,
                "card": wire_card,
                "quote": quote,
                "tz_offset_minutes": tz_of[result["quotes"][c["id"]]["session_id"]] if quote else None,
                "question": c["question"],
                "display": c["display"] if shown else None,
                "sentence": c["sentence"] if shown else None,
                "refusal": c["reason"],
                "local": local,
            }
            no_dash(f"cards.json {sc.name} {c['id']}", {k: entry[k] for k in ("question", "display", "sentence", "refusal")})
            key = json.dumps({k: v for k, v in entry.items() if k != "scenario"}, sort_keys=True)
            if key not in seen:
                seen.add(key)
                out.append(entry)
    return out


# ---------------------------------------------------------------------------- burn
def burn_entries() -> list[dict]:
    """Each `burn_fixture.scenarios()` session: its harness, the upload's `burn` block, and
    the sentences `burn.explain` says about the same report."""
    out = []
    for s in burn_fixture.scenarios():
        rep = s.report()
        entry = {
            "name": s.name,
            "harness": s.harness,
            "burn": burn.session_wire(rep),
            "sentences": burn.explain(rep),
        }
        no_dash(f"session.json {s.name}", entry["sentences"])
        out.append(entry)
    return out


def project_entries() -> list[dict]:
    """Every `projects_fixture` case beside the words Python says about it."""
    out = projects_fixture.entries()
    for e in out:
        no_dash(f"sentences.json {e['kind']} {e['name']}", {k: e[k] for k in ("sentence", "display", "last") if k in e})
    return out


def dump(obj) -> str:
    return json.dumps(obj, indent=1, ensure_ascii=False) + "\n"


def main() -> None:
    print("gen_copy.py")
    write(COPY_TS, gen_ts())
    write(CARDS_JSON, dump(card_entries()))
    write(BURN_JSON, dump(burn_entries()))
    write(PROJECTS_JSON, dump(project_entries()))
    write(PROJECT_BLOCK_JSON, dump(projects_fixture.block()))
    write(READS_ONLY_JSON, dump(reads_only_fixture.entries()))


if __name__ == "__main__":
    main()
