#!/usr/bin/env python3
"""Generate the drop wire into Pydantic, TypeScript and a JSON Schema.

spec/drops.v1.json is the ONLY definition of a drop (docs/drops.md). Every emitter is
borrowed from scripts/gen_analysis.py, as gen_report.py and gen_live.py borrow them, so no
two specs in this repository can describe a `string, max 80` two different ways.

FOUR OUTPUTS, and no Swift. A model writes half of this document, so there IS a schema to
hand a constrained decoder (`drops/schema.json`, given to `claude -p --json-schema`). The
server validates the other half at the door. The fourth is `drops/tables.py`: the same enums
with no Pydantic import, because the runner that resolves a drop is standard library only like
`capture`, and a module it imports that needs a dependency is a runner that will not start on a
machine that has the transcripts. Nothing here is computed by BuilderKit: a drop arrives from
the phone and is resolved by the Python runner, so the Swift engine never holds one and a fifth
output would be a type nobody constructs.

STAMPED FIELDS ARE LEFT OUT OF THE SCHEMA. `Move.verification` is written by drops/verify.py
after it fetches the source URL. Handing the model a field called `verified` is handing it a
fact about the network to invent, and it will: the schema it receives does not contain one.
Every stamped field must be nullable, which `check` enforces, so a plan that has not been
verified yet still satisfies the Pydantic models the server uses.

THE ROOT OF THE SCHEMA IS NOT THE ROOT OF THE SPEC. `DropResolution` (the spec's top) is what
the Mac uploads: measured facts plus the plan. `DropPlan` is what the model writes, and it is
an object, so the schema is rooted there and the rest travel as `$defs`.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gen_analysis as ga  # noqa: E402

ROOT = ga.ROOT
SPEC = ROOT / "spec" / "drops.v1.json"
TOP = "DropResolution"
#: The object the model writes, and the root of the schema it is handed.
PLAN = "DropPlan"

BANNER_TS = "// GENERATED by scripts/gen_drops.py from spec/drops.v1.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by scripts/gen_drops.py from spec/drops.v1.json — DO NOT EDIT."


def enums(s: dict) -> dict[str, list[str]]:
    """The enum table without the spec's own commentary. A `_comment` key inside `enums`
    would otherwise be emitted as an enum named `_comment` in three languages."""
    return {k: v for k, v in s["enums"].items() if not k.startswith("_")}


def all_fields(s: dict) -> list[tuple[str, list[dict]]]:
    return [(name, fs) for name, fs in s["objects"].items()] + [(TOP, s["fields"])]


def load() -> dict:
    s = json.loads(SPEC.read_text())
    names = [f["name"] for f in s["fields"]]
    assert names[0] == "drops_version", (
        "drops_version must be the first field: a stored resolution that cannot say which "
        "rules produced it cannot be compared with the next one."
    )
    assert PLAN in s["objects"], f"{PLAN} must be an object: it is the root of the schema."
    check(s)
    return s


def check(s: dict) -> None:
    """Refuse a spec whose output would compile and still be wrong.

    Same shape as gen_report.check, plus the two rules this spec adds: a stamped field must
    be nullable (or an unstamped plan fails the server's own models), and every string must
    name a cap (a free string is how a stranger's caption reaches a column with no bound).
    """
    table = enums(s)
    for owner, fs in all_fields(s):
        seen: set[str] = set()
        for f in fs:
            where = f"{owner}.{f['name']}"
            assert f["name"] not in seen, f"{where} is declared twice"
            seen.add(f["name"])
            t = f["type"]
            if t == "enum":
                assert f["values"] in table, f"{where} names an enum the spec lacks"
            elif t in ("object", "list"):
                item = f["item"]
                assert item in s["objects"] or item in ga.PY_SCALARS, (
                    f"{where} names an item the spec lacks: {item!r}"
                )
                if t == "list" and item == "string":
                    assert "max" in f, f"{where} is a list of unbounded strings"
            else:
                assert t in ga.PY_SCALARS, f"{where} has a type this generator cannot emit: {t!r}"
            if t == "string":
                assert "max" in f and f["max"] in s["max_lengths"], (
                    f"{where} is a string with no cap in max_lengths. Every string here "
                    "carries text this machine did not write."
                )
            if f.get("stamped"):
                assert f.get("nullable"), (
                    f"{where} is stamped by the runner and must be nullable: the model's "
                    "document is validated before anything stamps it."
                )
            if t == "double":
                assert ga.FRACTION_DOC.search(f.get("doc", "")), (
                    f"{where} is a double whose doc does not say it is a fraction."
                )
    for name, values in table.items():
        assert len(values) == len(set(values)), f"enum {name} repeats a value"
    kinds = table["drop_kind"]
    assert "unknown" in kinds, "drop_kind must keep `unknown`: a refusal needs somewhere to land."


# ------------------------------------------------------------------------ python
def gen_py(s: dict) -> str:
    models = "\n\n".join(ga.py_model(s, name, fs, scalars=ga.PY_SCALARS_AWARE) for name, fs in all_fields(s))
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in enums(s).items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in all_fields(s)
    )
    return f'''{BANNER_PY}
"""A drop's resolution, server side.

`extra="forbid"` and the bounds are the enforcement half of drops/schema.json: the
constrained decoder that wrote the plan honours the enums and the required fields, but
string lengths, the stamped block and the refusal rule are checked HERE, on the way into
Postgres, or nowhere.

Datetimes are `AwareDatetime` for the reason scripts/gen_contract.py gives: the plain type
accepts an offsetless stamp, and the first `now(UTC) - naive` downstream is a TypeError that
turns one bad upload into a 500 for the whole batch.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator, model_validator

DROPS_VERSION = {s["version"]}

#: Character caps by size class; the spec's `max` on a string field names one of these.
DROPS_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: Legal values for every enum, in spec order. The routes import `DROP_STATUS` and
#: `MOVE_STATUS` from here rather than restating the row states beside the wire's.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: model name -> field name -> enum name, for the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}

DROP_STATUS: list[str] = ANALYSIS_ENUM_VALUES["drop_status"]
MOVE_STATUS: list[str] = ANALYSIS_ENUM_VALUES["move_status"]


{models}

    @model_validator(mode="after")
    def _plan_or_refusal(self):
        """One of the two, never neither and never both.

        Neither is a resolution that says nothing happened and does not say why, which is
        the shape a card cannot render and a person cannot act on. Both is a plan the phone
        would draw under a refusal, and there is no rule for which of them wins.
        """
        if (self.plan is None) == (self.refusal is None):
            raise ValueError(
                "a resolution carries a plan or a refusal: "
                f"plan={{'set' if self.plan is not None else 'null'}}, "
                f"refusal={{self.refusal!r}}"
            )
        if self.plan is not None and self.planned_at is None:
            raise ValueError("a plan without planned_at cannot be told from the next one")
        return self
'''


# ------------------------------------------------------------------------ typescript
def gen_ts(s: dict) -> str:
    table = enums(s)
    unions = "\n".join(
        f"export type {ga.pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in table.items()
    )
    enum_table = "\n".join(f"  {name}: {json.dumps(values)}," for name, values in table.items())
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    interfaces = "\n\n".join(
        [ga.ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.ts_interface(s, TOP, s["fields"])]
    )
    return f"""{BANNER_TS}

export const DROPS_VERSION = {s["version"]};

/** Character caps by size class; string fields below name one of these in their doc. */
export const DROPS_MAX_LENGTHS = {{
{max_lengths}
}} as const;

{unions}

/** Legal values for every enum, in spec order, so a screen can iterate a catalog (every
 * refusal code, every move kind) and a test can check the copy covers each one. */
export const DROPS_ENUMS = {{
{enum_table}
}} as const;

{interfaces}
"""


# ------------------------------------------------------------------- json schema
def json_object(s: dict, fs: list[dict]) -> dict:
    """gen_analysis.json_object, minus the stamped fields. A stamped field is not the
    model's to write, so it is not in the document the model is asked for."""
    live = [f for f in fs if not f.get("stamped")]
    return {
        "type": "object",
        "properties": {f["name"]: ga.json_prop(s, f) for f in live},
        "required": [f["name"] for f in live if not f.get("nullable")],
        "additionalProperties": False,
    }


def reachable(s: dict, root: str) -> list[str]:
    """The objects the schema actually needs, so `$defs` cannot carry DropSource — a block
    of MEASURED facts that would read, to a model handed the schema, as fields to fill in."""
    out: list[str] = []
    stack = [root]
    while stack:
        name = stack.pop()
        for f in s["objects"][name]:
            if f["type"] in ("object", "list") and f["item"] in s["objects"] and not f.get("stamped"):
                if f["item"] not in out:
                    out.append(f["item"])
                    stack.append(f["item"])
    return out


def gen_schema(s: dict) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": (
            "GENERATED by scripts/gen_drops.py from spec/drops.v1.json — DO NOT EDIT. "
            "Handed to `claude -p --json-schema` by drops/plan.py."
        ),
        "title": PLAN,
        "description": (
            "A reading of one thing somebody shared into Builda, and the moves that could be "
            "made on it. Every move carries a VERBATIM span of the source text as its evidence; "
            "a move whose evidence is not found in the text is discarded before anybody sees it. "
            "Name nothing that is not in the text: no package that was not mentioned, no "
            "repository, no URL. When the text does not support a kind, answer `unknown` with a "
            "refusal code, which is a correct answer and not a failure."
        ),
        **json_object(s, s["objects"][PLAN]),
        "$defs": {name: json_object(s, s["objects"][name]) for name in reachable(s, PLAN)},
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def gen_tables(s: dict) -> str:
    """The enums, with no Pydantic import.

    `drops/` is standard library only for capture's reason: it runs on the machine that has
    the links, which is a machine nobody installed a dependency on. Importing the Pydantic
    models to read one enum would make `python -m drops` fail to start where it matters most.
    """
    table = enums(s)
    body = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in table.items())
    consts = "\n".join(
        f"{name.upper()}: tuple[str, ...] = tuple(ENUMS[{json.dumps(name)}])" for name in table
    )
    caps = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    return f'''{BANNER_PY}
"""The drop wire's enums and caps, for the runner on the person's own machine.

The same tables `server/builder/drops_spec.py` builds its validators from and
`mobile/src/generated/drops.ts` exports, with nothing imported: `drops/` is standard library
only (see drops/__init__.py), and this is the file that keeps it that way.
"""

from __future__ import annotations

DROPS_VERSION = {s["version"]}

#: Legal values for every enum, in spec order.
ENUMS: dict[str, list[str]] = {{
{body}
}}

#: Character caps by size class; every string on the wire names one of these.
MAX_LENGTHS: dict[str, int] = {{
{caps}
}}

{consts}
'''


def main() -> None:
    s = load()
    print("gen_drops.py")
    ga.write(ROOT / "server/builder/drops_spec.py", gen_py(s))
    ga.write(ROOT / "drops/tables.py", gen_tables(s))
    ga.write(ROOT / "mobile/src/generated/drops.ts", gen_ts(s))
    ga.write(ROOT / "drops/schema.json", gen_schema(s))


if __name__ == "__main__":
    main()
