#!/usr/bin/env python3
"""Generate the trailer's tables, the edit schema, the server's door and the phone's types.

spec/trailer.v1.json is the only definition of a trailer (docs/trailers.md). The emitters are
gen_analysis.py's, as gen_shipkit.py borrows them. Four outputs:

    capture/trailer/tables.py         the enums, bounds, refusal and change sentences, with nothing
                                      imported: capture is standard library only
    capture/trailer/edit_schema.json  the document `claude -p --json-schema` is asked for when a note
                                      needs a model: CutEdit and what it reaches, nothing else
    server/builder/trailer_spec.py    Pydantic, `extra="forbid"`: a cut, a change, a note and the Mac's answer
    mobile/src/generated/trailer.ts   the same shapes, and every sentence the phone says about a note

`check` refuses a spec whose output would compile and still be wrong: a string with no cap, a code
with no sentence (the phone would print the code), a change sentence naming a placeholder other than
{before} and {after}, a scene or figure with no words, arrival orders that are not the app's eight in the
app's order (mobile/src/motion/pixelMotion.ts `PIXEL_MOTIONS`, read as text), a hue or creature
design/tokens.json lacks, and a dash in any sentence the phone will show.
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gen_analysis as ga  # noqa: E402

ROOT = ga.ROOT
SPEC = ROOT / "spec" / "trailer.v1.json"
TOKENS = ROOT / "design" / "tokens.json"
PIXEL_MOTION = ROOT / "mobile" / "src" / "motion" / "pixelMotion.ts"
ROOT_OBJECT = "CutEdit"
#: The four dashes the app refuses in copy (analysis/plain.py `has_dash`): em, en, the horizontal bar
#: and the minus sign.
DASHES = ("—", "–", "―", "−")
WORDED = ("scene_kind", "figure", "mood", "camera", "transition")

BANNER_TS = "// GENERATED by scripts/gen_trailer.py from spec/trailer.v1.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by scripts/gen_trailer.py from spec/trailer.v1.json — DO NOT EDIT."


def strip(d: dict) -> dict:
    return {k: v for k, v in d.items() if not k.startswith("_")}


def load() -> dict:
    s = json.loads(SPEC.read_text())
    s["enums"] = strip(s["enums"])
    s["refusals"] = strip(s["refusals"])
    s["changes"] = strip(s["changes"])
    s["words"] = strip(s["words"])
    check(s)
    return s


def pixel_motions() -> list[str]:
    text = PIXEL_MOTION.read_text()
    m = re.search(r"export const PIXEL_MOTIONS = \[(.*?)\] as const;", text, re.S)
    assert m, "mobile/src/motion/pixelMotion.ts no longer declares PIXEL_MOTIONS as this reads it"
    return re.findall(r"^\s*'([a-z]+)',", m.group(1), re.M)


def check(s: dict) -> None:
    e = s["enums"]
    for owner, fs in s["objects"].items():
        seen: set[str] = set()
        for f in fs:
            where = f"{owner}.{f['name']}"
            assert f["name"] not in seen, f"{where} is declared twice"
            seen.add(f["name"])
            t = f["type"]
            if t == "enum":
                assert f["values"] in e, f"{where} names an enum the spec lacks"
            elif t in ("object", "list"):
                assert f["item"] in s["objects"] or f["item"] in ga.PY_SCALARS, f"{where}: item {f['item']!r}"
                if t == "list":
                    assert "max_items" in f, f"{where} is a list with no cap"
                    if f["item"] == "string":
                        assert "max" in f, f"{where} is a list of unbounded strings"
            else:
                assert t in ga.PY_SCALARS, f"{where}: type {t!r}"
            if t == "string":
                assert f.get("max") in s["max_lengths"], f"{where} is a string with no cap"
    for name, values in e.items():
        assert len(values) == len(set(values)), f"enum {name} repeats a value"
    missing = [c for c in e["note_refusal"] if c not in s["refusals"]]
    assert not missing, f"refusal codes with no sentence: {missing}"
    extra = [c for c in s["refusals"] if c not in e["note_refusal"]]
    assert not extra, f"sentences for refusal codes the enum lacks: {extra}"
    missing = [c for c in e["change_code"] if c not in s["changes"]]
    assert not missing, f"change codes with no sentence: {missing}"
    extra = [c for c in s["changes"] if c not in e["change_code"]]
    assert not extra, f"sentences for change codes the enum lacks: {extra}"
    for code, sentence in s["changes"].items():
        holes = set(re.findall(r"\{(\w+)\}", sentence))
        assert holes <= {"before", "after"}, f"change {code} names {sorted(holes - {'before', 'after'})}"
    for name in WORDED:
        assert set(s["words"][name]) == set(e[name]), f"words.{name} must say every {name} and nothing else"
    motions = pixel_motions()
    assert e["arrival"] == motions, f"arrival {e['arrival']} must be pixelMotion.ts's {motions}, in order"
    tokens = json.loads(TOKENS.read_text())
    assert e["hue"] == list(tokens["spectrum"]["hues"]), "hue must be design/tokens.json's hues, in order"
    creatures = [k for k in tokens["spectrum"]["creature"] if not k.startswith("_")]
    assert e["creature"] == creatures, f"creature must be design/tokens.json's {creatures}, in order"
    said = list(s["refusals"].values()) + list(s["changes"].values())
    said += [w for group in s["words"].values() for w in group.values()]
    for text in said:
        assert not any(d in text for d in DASHES), f"a dash in {text!r}"
    lo, hi = s["seconds"]["min"], s["seconds"]["max"]
    assert lo <= s["seconds"]["default"] <= hi, "the default length sits inside its bounds"
    assert s["pace"]["min"] < 1 < s["pace"]["max"], "pace 1 (the app's own springs) is always allowed"


# ------------------------------------------------------------------------ outputs


def py_dict(d: dict, indent: str = "    ") -> str:
    return "\n".join(f"{indent}{json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}," for k, v in d.items())


def gen_tables(s: dict) -> str:
    return f'''{BANNER_PY}
"""The trailer's enums, bounds and sentences, for the Mac (docs/trailers.md).

Nothing imported: capture is standard library only. The server builds its door from the same
spec (server/builder/trailer_spec.py), the phone its types (mobile/src/generated/trailer.ts), and
trailer/ (the renderer) reads spec/trailer.v1.json itself.
"""

from __future__ import annotations

TRAILER_VERSION = {s["version"]}
FPS = {s["fps"]}
SECONDS: dict[str, float] = {json.dumps(s["seconds"])}
PACE: dict[str, float] = {json.dumps(s["pace"])}
WEIGHT: dict[str, float] = {json.dumps(s["weight"])}
SCENES_MAX = {s["scenes_max"]}

#: Legal values for every enum, in spec order.
ENUMS: dict[str, list[str]] = {{
{py_dict(s["enums"])}
}}

#: Character caps by size class.
MAX_LENGTHS: dict[str, int] = {{
{py_dict(s["max_lengths"])}
}}

#: Every refusal code's sentence: the words the Mac, the server and the phone all say.
REFUSALS: dict[str, str] = {{
{py_dict(s["refusals"])}
}}

#: Every change code's sentence, {{before}} and {{after}} filled with the change's own values.
CHANGES: dict[str, str] = {{
{py_dict(s["changes"])}
}}

#: How a coded value is said inside a change's sentence.
WORDS: dict[str, dict[str, str]] = {{
{py_dict(s["words"])}
}}
'''


def reachable(s: dict, root: str) -> list[str]:
    out: list[str] = []
    stack = [root]
    while stack:
        for f in s["objects"][stack.pop()]:
            if f["type"] in ("object", "list") and f["item"] in s["objects"] and f["item"] not in out:
                out.append(f["item"])
                stack.append(f["item"])
    return out


def gen_schema(s: dict) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": (
            "GENERATED by scripts/gen_trailer.py from spec/trailer.v1.json — DO NOT EDIT. "
            "Handed to `claude -p --json-schema` by capture/trailer/direct.py."
        ),
        "title": ROOT_OBJECT,
        "description": (
            "A change to a project's trailer, asked for in the owner's own words. Return the whole cut "
            "with only what the note asked for changed, and one change per difference. Every number on "
            "screen must be one the project gave, written the same way; words the owner typed may be "
            "used as they typed them. When the note needs something a cut cannot do (new screens, a "
            "different app), set refusal and no cut. Plain words, no dashes."
        ),
        **ga.json_object(s, s["objects"][ROOT_OBJECT]),
        "$defs": {name: ga.json_object(s, s["objects"][name]) for name in reachable(s, ROOT_OBJECT)},
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def gen_py(s: dict) -> str:
    models = "\n\n".join(
        ga.py_model(s, name, fs, scalars=ga.PY_SCALARS_AWARE, enum_table="TRAILER_ENUM_VALUES", fields_table="TRAILER_ENUM_FIELDS")
        for name, fs in s["objects"].items()
    )
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: " + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"}) + ","
        for owner, fs in s["objects"].items()
    )
    return f'''{BANNER_PY}
"""The trailer at the server's door (docs/trailers.md): the phone's note (`NoteIn`, the owner's
words, bounded by `TRAILER_MAX_LENGTHS["note"]`) and the Mac's answer to it (`NoteFinish`: the new
version, its changes as codes, or a refusal code). routes/trailer.py is the rest of the door: a
done note has a version and no refusal, a failed one a refusal and no version.

`extra="forbid"` and the bounds are this door's half; a change's sentence is the phone's to say.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

TRAILER_VERSION = {s["version"]}

TRAILER_MAX_LENGTHS: dict[str, int] = {{
{py_dict(s["max_lengths"])}
}}

TRAILER_ENUM_VALUES: dict[str, list[str]] = {{
{py_dict(s["enums"])}
}}

TRAILER_ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}

#: A refusal's sentence, for the words a push about a note carries.
TRAILER_REFUSALS: dict[str, str] = {{
{py_dict(s["refusals"])}
}}

# `Annotated` and `Field` are what a bounded list of strings would need; kept importable.
_ = (Annotated, Field)


{models}'''


def gen_ts(s: dict) -> str:
    e = s["enums"]
    unions = "\n".join(f"export type {ga.pascal(n)} = " + " | ".join(json.dumps(v) for v in vs) + ";" for n, vs in e.items())
    enum_table = "\n".join(f"  {n}: {json.dumps(vs)}," for n, vs in e.items())
    interfaces = "\n\n".join(ga.ts_interface(s, name, fs) for name, fs in s["objects"].items())

    def ts_dict(d: dict) -> str:
        return "\n".join(f"  {k}: {json.dumps(v, ensure_ascii=False)}," for k, v in d.items())

    words = "\n".join(f"  {k}: {{\n" + "\n".join(f"    {kk}: {json.dumps(vv)}," for kk, vv in v.items()) + "\n  }," for k, v in s["words"].items())
    return f"""{BANNER_TS}

export const TRAILER_VERSION = {s["version"]};
export const TRAILER_FPS = {s["fps"]};
export const TRAILER_SECONDS = {json.dumps(s["seconds"])} as const;
export const TRAILER_PACE = {json.dumps(s["pace"])} as const;
export const TRAILER_MAX_LENGTHS = {json.dumps(s["max_lengths"])} as const;

{unions}

/** Legal values for every enum, in spec order. */
export const TRAILER_ENUMS = {{
{enum_table}
}} as const;

/** Every refusal code's sentence, the same words the Mac prints. */
export const TRAILER_REFUSALS: Readonly<Record<NoteRefusal, string>> = {{
{ts_dict(s["refusals"])}
}};

/** Every change code's sentence; {{before}} and {{after}} are the change's own values, said by `TRAILER_WORDS`. */
export const TRAILER_CHANGES: Readonly<Record<ChangeCode, string>> = {{
{ts_dict(s["changes"])}
}};

/** How a coded value is said inside a change's sentence. */
export const TRAILER_WORDS = {{
{words}
}} as const;

{interfaces}
"""


def main() -> None:
    s = load()
    (ROOT / "capture" / "trailer").mkdir(exist_ok=True)
    ga.write(ROOT / "capture" / "trailer" / "tables.py", gen_tables(s))
    ga.write(ROOT / "capture" / "trailer" / "edit_schema.json", gen_schema(s))
    ga.write(ROOT / "server" / "builder" / "trailer_spec.py", gen_py(s))
    ga.write(ROOT / "mobile" / "src" / "generated" / "trailer.ts", gen_ts(s))


if __name__ == "__main__":
    main()
