#!/usr/bin/env python3
"""Generate the live wire into Pydantic and TypeScript.

spec/live.v1.json is the ONLY definition of what a running session's `live` block and the
opt in `live_names` block look like on the wire (privacy/upload-contract.json v4 names both).
Every emitter is borrowed from scripts/gen_analysis.py, as gen_report.py borrows them, so no
two specs in this repository can describe `int, nullable` two different ways.

TWO OUTPUTS, for the reasons gen_report.py gives: no model writes this document (every field
is a number `analysis/live.py` computed), so there is no JSON Schema to hand a constrained
decoder; and the Mac never sends it (capture and the server's hook channel do), so there is
no Swift.

Two things differ from the other specs, both at the door:

  * `hex16`, a salted file id, is its own scalar with its own pattern. A `str` would take
    `/Users/me/secret.py` as an id without a word, and the whole privacy claim of the map
    rests on an id being unable to be a path.

  * Datetimes are `AwareDatetime`, as in the contract: `computed_at` anchors the ETA and
    ages `since_s`, and a naive one is a TypeError the first time the server subtracts it
    from `now(UTC)`.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gen_analysis as ga  # noqa: E402

ROOT = ga.ROOT
SPEC = ROOT / "spec" / "live.v1.json"
TOP = "LiveState"

BANNER_TS = "// GENERATED by scripts/gen_live.py from spec/live.v1.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by scripts/gen_live.py from spec/live.v1.json — DO NOT EDIT."


def load() -> dict:
    s = json.loads(SPEC.read_text())
    names = [f["name"] for f in s["fields"]]
    assert names[0] == "live_version", (
        "live_version must be the first field: a stored live row that cannot say which "
        "rules produced it cannot be compared with the next one."
    )
    ga.assert_fraction_docs(s, TOP)
    for owner, fs in ga.all_fields(s, TOP):
        for f in fs:
            # A free string is how prose reaches the wire. The spec has exactly one, the
            # basename inside the opt in LiveNames, and it is bounded.
            if f["type"] == "string" or (f["type"] == "list" and f.get("item") == "string"):
                assert (owner, f["name"]) == ("LiveName", "name") and "max" in f, (
                    f"{owner}.{f['name']} is a free string on the live wire. Everything here "
                    "is an enum, a number, a clock or a salted id; the one exception is the "
                    "opt in basename (LiveName.name), and it carries a cap."
                )
    return s


def models(s: dict) -> str:
    return "\n\n".join(
        [
            ga.py_model(s, name, fs, scalars=ga.PY_SCALARS_AWARE)
            for name, fs in s["objects"].items()
        ]
        + [ga.py_model(s, TOP, s["fields"], scalars=ga.PY_SCALARS_AWARE)]
    ).rstrip("\n")


def gen_py(s: dict) -> str:
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: "
        + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"})
        + ","
        for owner, fs in ga.all_fields(s, TOP)
    )
    return f'''{BANNER_PY}
"""A running session's live state, server side.

`extra="forbid"` at every level and the patterns below are the whole of the enforcement:
the document is computed by `analysis/live.py` (on the server for the hook channel, on the
machine for `capture sync --live`), and a key it grows without the spec growing it is a
422 here rather than a field nobody declared sitting in `session_live.body`.

`Hex16` is why a path cannot pass as a file id, and `LiveName.name` is the only free string
in the document (a basename, capped at 120, sent only with File names on).
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

LIVE_VERSION = {s["version"]}

Hex16 = Annotated[str, Field(pattern=r"{ga.HEX16_PATTERN}")]

#: Character caps by size class; the spec's `max` on a string field names one of these.
LIVE_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

#: Legal values for every enum, in spec order. Named for the emitter in
#: scripts/gen_analysis.py, whose validators read these two tables by name.
ANALYSIS_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

#: Which fields of which model carry which enum, read by the validators below.
ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}


{models(s)}
'''


def gen_ts(s: dict) -> str:
    unions = "\n".join(
        f"export type {ga.pascal(name)} = " + " | ".join(json.dumps(v) for v in values) + ";"
        for name, values in s["enums"].items()
    )
    enum_table = "\n".join(f"  {name}: {json.dumps(values)}," for name, values in s["enums"].items())
    max_lengths = "\n".join(f"  {k}: {v}," for k, v in s["max_lengths"].items())
    interfaces = "\n\n".join(
        [ga.ts_interface(s, name, fs) for name, fs in s["objects"].items()]
        + [ga.ts_interface(s, TOP, s["fields"])]
    )
    return f"""{BANNER_TS}

export const LIVE_VERSION = {s["version"]};

/** Character caps by size class; string fields below name one of these in their doc. */
export const LIVE_MAX_LENGTHS = {{
{max_lengths}
}} as const;

{unions}

/** Legal values for every enum, in spec order: the order analysis/live.py declares them. */
export const LIVE_ENUMS = {{
{enum_table}
}} as const;

{interfaces}
"""


def main() -> None:
    s = load()
    print("gen_live.py")
    ga.write(ROOT / "server/builder/live_spec.py", gen_py(s))
    ga.write(ROOT / "mobile/src/generated/live.ts", gen_ts(s))


if __name__ == "__main__":
    main()
