#!/usr/bin/env python3
"""Generate the ship kit's tables, the caption schema, the server's door and the phone's types.

spec/shipkit.v1.json is the only definition of a ship kit (docs/ship-kit.md). The emitters are
gen_analysis.py's, as gen_drops.py borrows them, so no two specs in this repository describe a
`string, max 80` two different ways. Four outputs:

    capture/shipkit/tables.py        the enums, caps, platform limits and refusal sentences, with
                                     nothing imported: capture is standard library only
    capture/shipkit/copy_schema.json the document `claude -p --json-schema` is asked for: ShareCopy
                                     and what it reaches, nothing else
    server/builder/shipkit_spec.py   Pydantic, `extra="forbid"`: the kit document, the presign of one
                                     kit file, and the phone's request for a demo
    mobile/src/generated/shipkit.ts  the same shapes and every refusal's sentence for the phone

`check` refuses a spec whose output would compile and still be wrong: a string with no cap (text
from a model or a commit reaching a column unbounded), a refusal code with no sentence (the phone
would print the code), a format id that is not a format of spec/devices.v1.json, a platform with
no limit or no format, and a hue that design/tokens.json does not have.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import gen_analysis as ga  # noqa: E402

ROOT = ga.ROOT
SPEC = ROOT / "spec" / "shipkit.v1.json"
DEVICES = ROOT / "spec" / "devices.v1.json"
TOKENS = ROOT / "design" / "tokens.json"
ROOT_OBJECT = "ShareCopy"
REFUSAL_ENUMS = ("request_refusal", "kit_refusal", "queue_skip")

BANNER_TS = "// GENERATED by scripts/gen_shipkit.py from spec/shipkit.v1.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by scripts/gen_shipkit.py from spec/shipkit.v1.json — DO NOT EDIT."


def strip(d: dict) -> dict:
    return {k: v for k, v in d.items() if not k.startswith("_")}


def load() -> dict:
    s = json.loads(SPEC.read_text())
    s["enums"] = strip(s["enums"])
    s["platform_limits"] = strip(s["platform_limits"])
    s["platform_format"] = strip(s["platform_format"])
    s["caps"] = strip(s["caps"])
    check(s)
    return s


def check(s: dict) -> None:
    e = s["enums"]
    for owner, fs in s["objects"].items():
        seen: set[str] = set()
        for f in fs:
            where = f"{owner}.{f['name']}"
            assert f["name"] not in seen, f"{where} is declared twice"
            seen.add(f["name"])
            t = f["type"]
            if t == "enum":
                assert f["values"] in e, f"{where} names an enum the spec lacks"
            elif t in ("object", "list"):
                assert f["item"] in s["objects"] or f["item"] in ga.PY_SCALARS, f"{where}: item {f['item']!r}"
                if t == "list" and f["item"] == "string":
                    assert "max" in f, f"{where} is a list of unbounded strings"
            else:
                assert t in ga.PY_SCALARS, f"{where}: type {t!r}"
            if t == "string":
                assert f.get("max") in s["max_lengths"], f"{where} is a string with no cap"
    for name, values in e.items():
        assert len(values) == len(set(values)), f"enum {name} repeats a value"
    for name in REFUSAL_ENUMS:
        missing = [c for c in e[name] if c not in s["refusals"]]
        assert not missing, f"{name} codes with no sentence: {missing}"
    extra = [c for c in s["refusals"] if c != "_comment" and not any(c in e[n] for n in REFUSAL_ENUMS)]
    assert not extra, f"sentences for codes no enum has: {extra}"
    assert set(s["platform_limits"]) == set(e["platform"]), "every platform has a limit, and only platforms"
    assert set(s["platform_format"]) == set(e["platform"]), "every platform has a format, and only platforms"
    devices = json.loads(DEVICES.read_text())
    formats = [f["id"] for f in devices["formats"]]
    assert e["kit_format"] == formats, f"kit_format {e['kit_format']} must be spec/devices.v1.json's formats {formats}, in order"
    assert set(s["platform_format"].values()) <= set(formats)
    assert [f"video_{f}" for f in formats] == e["kit_slot"][: len(formats)], "one video slot per format, first, in order"
    hues = set(json.loads(TOKENS.read_text())["spectrum"]["hues"])
    assert set(e["hue"]) <= hues, f"hues design/tokens.json lacks: {sorted(set(e['hue']) - hues)}"
    assert s["caps"]["gif_bytes"] == devices["loop"]["max_bytes"], "the GIF cap is the device table's loop.max_bytes"


# ------------------------------------------------------------------------ outputs


def gen_tables(s: dict) -> str:
    body = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    caps = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    limits = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["platform_limits"].items())
    pformat = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["platform_format"].items())
    kcaps = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["caps"].items())
    refusals = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["refusals"].items() if not k.startswith("_"))
    return f'''{BANNER_PY}
"""The ship kit's enums, caps and refusal sentences, for the Mac (docs/ship-kit.md).

Nothing imported: capture is standard library only. The server builds its door from the same
spec (server/builder/shipkit_spec.py) and the phone its types (mobile/src/generated/shipkit.ts).
"""

from __future__ import annotations

SHIPKIT_VERSION = {s["version"]}
THREAD_MAX = {s["thread_max"]}

#: Legal values for every enum, in spec order.
ENUMS: dict[str, list[str]] = {{
{body}
}}

#: Character caps by size class.
MAX_LENGTHS: dict[str, int] = {{
{caps}
}}

#: Characters a caption may run to, per platform (the spec says where each number is from).
PLATFORM_LIMITS: dict[str, int] = {{
{limits}
}}

#: The format each platform's post shows best.
PLATFORM_FORMAT: dict[str, str] = {{
{pformat}
}}

#: What one published kit may hold.
CAPS: dict[str, int] = {{
{kcaps}
}}

#: Every refusal code's sentence: the words the Mac, the server and the phone all say.
REFUSALS: dict[str, str] = {{
{refusals}
}}
'''


def reachable(s: dict, root: str) -> list[str]:
    out: list[str] = []
    stack = [root]
    while stack:
        for f in s["objects"][stack.pop()]:
            if f["type"] in ("object", "list") and f["item"] in s["objects"] and f["item"] not in out:
                out.append(f["item"])
                stack.append(f["item"])
    return out


def gen_schema(s: dict) -> str:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": (
            "GENERATED by scripts/gen_shipkit.py from spec/shipkit.v1.json — DO NOT EDIT. "
            "Handed to `claude -p --json-schema` by capture/shipkit/copy.py."
        ),
        "title": ROOT_OBJECT,
        "description": (
            "The posts a builder could put beside a demo of what they built, one per platform. "
            "Every sentence describes work that is in the input. A number the input does not "
            "contain, written the same way, gets the whole caption thrown away; so does a claim "
            "the input does not make. Plain words, first person, no dashes."
        ),
        **ga.json_object(s, s["objects"][ROOT_OBJECT]),
        "$defs": {name: ga.json_object(s, s["objects"][name]) for name in reachable(s, ROOT_OBJECT)},
    }
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def gen_py(s: dict) -> str:
    models = "\n\n".join(
        ga.py_model(s, name, fs, scalars=ga.PY_SCALARS_AWARE, enum_table="SHIPKIT_ENUM_VALUES", fields_table="SHIPKIT_ENUM_FIELDS")
        for name, fs in s["objects"].items()
    )
    max_lengths = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["max_lengths"].items())
    enum_values = "\n".join(f"    {json.dumps(k)}: {json.dumps(v)}," for k, v in s["enums"].items())
    enum_fields = "\n".join(
        f"    {json.dumps(owner)}: " + json.dumps({f["name"]: f["values"] for f in fs if f["type"] == "enum"}) + ","
        for owner, fs in s["objects"].items()
    )
    caps = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["caps"].items())
    limits = "\n".join(f"    {json.dumps(k)}: {v}," for k, v in s["platform_limits"].items())
    # A failed request's sentence, for the words its Live Activity carries (demo_push, docs/demo-island.md):
    # the same `refusals` text the phone's kit screen and the Mac print, not a third wording.
    request_sentences = "\n".join(
        f"    {json.dumps(k)}: {json.dumps(s['refusals'][k])}," for k in s["enums"]["request_refusal"]
    )
    return f'''{BANNER_PY}
"""The ship kit at the server's door (docs/ship-kit.md): a kit document, the presign of one kit
file, and the phone's request for a demo.

`extra="forbid"` and the bounds are this door's half. The rest is routes/shipkit.py: a file's
content type to its slot and its size cap, a video to its length, the label to the demo
channel's rule, and a caption to its platform's limit.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator

Sha256Hex = Annotated[str, Field(pattern=r"^[0-9a-f]{{64}}$")]
Hex16 = Annotated[str, Field(pattern=r"^[0-9a-f]{{16}}$")]

SHIPKIT_VERSION = {s["version"]}

SHIPKIT_MAX_LENGTHS: dict[str, int] = {{
{max_lengths}
}}

SHIPKIT_CAPS: dict[str, int] = {{
{caps}
}}

PLATFORM_LIMITS: dict[str, int] = {{
{limits}
}}

SHIPKIT_ENUM_VALUES: dict[str, list[str]] = {{
{enum_values}
}}

SHIPKIT_ENUM_FIELDS: dict[str, dict[str, str]] = {{
{enum_fields}
}}

#: A failed request's code to its sentence (spec `refusals`), for the demo island's failure words.
REQUEST_REFUSAL_SENTENCES: dict[str, str] = {{
{request_sentences}
}}


{models}'''


def gen_ts(s: dict) -> str:
    e = s["enums"]
    unions = "\n".join(f"export type {ga.pascal(n)} = " + " | ".join(json.dumps(v) for v in vs) + ";" for n, vs in e.items())
    enum_table = "\n".join(f"  {n}: {json.dumps(vs)}," for n, vs in e.items())
    interfaces = "\n\n".join(ga.ts_interface(s, name, fs) for name, fs in s["objects"].items())
    limits = "\n".join(f"  {k}: {v}," for k, v in s["platform_limits"].items())
    pformat = "\n".join(f"  {k}: {json.dumps(v)}," for k, v in s["platform_format"].items())
    refusals = "\n".join(f"  {k}: {json.dumps(v)}," for k, v in s["refusals"].items() if not k.startswith("_"))
    return f"""{BANNER_TS}

export const SHIPKIT_VERSION = {s["version"]};

{unions}

/** Legal values for every enum, in spec order. */
export const SHIPKIT_ENUMS = {{
{enum_table}
}} as const;

/** Characters a caption may run to, per platform. */
export const PLATFORM_LIMITS: Readonly<Record<Platform, number>> = {{
{limits}
}};

/** The format each platform's post shows best: what Share selects first for it. */
export const PLATFORM_FORMAT: Readonly<Record<Platform, KitFormat>> = {{
{pformat}
}};

/** Every refusal code's sentence, the same words the Mac prints. */
export const SHIPKIT_REFUSALS: Readonly<Record<RequestRefusal | KitRefusal | QueueSkip, string>> = {{
{refusals}
}};

{interfaces}
"""


def main() -> None:
    s = load()
    ga.write(ROOT / "capture" / "shipkit" / "tables.py", gen_tables(s))
    ga.write(ROOT / "capture" / "shipkit" / "copy_schema.json", gen_schema(s))
    ga.write(ROOT / "server" / "builder" / "shipkit_spec.py", gen_py(s))
    ga.write(ROOT / "mobile" / "src" / "generated" / "shipkit.ts", gen_ts(s))


if __name__ == "__main__":
    main()
