#!/usr/bin/env python3
"""Generate design tokens into Swift and TypeScript.

COLOUR SPACE IS LOAD-BEARING. SwiftUI's bare Color(red:green:blue:) is Display P3 while
react-native-svg takes sRGB hex, so the Mac card would come out visibly more saturated
than the byte-identical phone card. The Swift emitted here is plain sRGB components;
BuilderUI/StripPalette.swift is the only place that turns them into Color, and it always
uses Color(.sRGB, ...).

The spec is validated before anything is written, so a bad edit to design/tokens.json fails
`make gen` instead of shipping: every colour is #RRGGBB with a light and a dark value, the
space scale stays on the 4pt grid, no type role goes under the 11pt floor, and the Bayer
table is exactly what the shader's arithmetic computes (the phone's test checks the
TypeScript port against the same table, so all three agree or the build is red).
"""

from __future__ import annotations

import json
import math
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "design" / "tokens.json"
BANNER = "// GENERATED by scripts/gen_tokens.py from design/tokens.json — DO NOT EDIT."

COLOUR_GROUPS = ("strip", "mark", "surface", "data")
TYPE_ROLES = ("hero", "display", "title", "headline", "body", "row", "meta", "label", "mono")
HEX = re.compile(r"^#[0-9A-F]{6}$")


def hex_to_rgb(h: str) -> tuple[float, float, float]:
    h = h.lstrip("#")
    return tuple(round(int(h[i : i + 2], 16) / 255.0, 6) for i in (0, 2, 4))  # type: ignore[return-value]


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


def clean(node):
    """Drop every `_comment` (any key starting with `_`) at every level."""
    if isinstance(node, dict):
        return {k: clean(v) for k, v in node.items() if not k.startswith("_")}
    if isinstance(node, list):
        return [clean(v) for v in node]
    return node


# ─── the ordered-dither threshold, the same arithmetic as the SkSL ─────────────────────


def _fract(x: float) -> float:
    return x - math.floor(x)


def bayer2(x: float, y: float) -> float:
    x, y = math.floor(x), math.floor(y)
    return _fract(x * 0.5 + y * y * 0.75)


def bayer8(x: float, y: float) -> float:
    """0 .. 63/64. Mirrors `b8` in mobile/src/ui/dithering.ts (DITHER_SKSL) line for line."""
    return bayer2(x * 0.25, y * 0.25) * 0.0625 + bayer2(x * 0.5, y * 0.5) * 0.25 + bayer2(x, y)


# ─── validation ────────────────────────────────────────────────────────────────────────


def validate(t: dict) -> None:
    problems: list[str] = []

    for group in COLOUR_GROUPS:
        for name, pair in clean(t[group]).items():
            for scheme in ("light", "dark"):
                v = pair.get(scheme)
                if not isinstance(v, str) or not HEX.match(v):
                    problems.append(f"{group}.{name}.{scheme} is {v!r}, not #RRGGBB (upper case)")

    for scheme in ("light", "dark"):
        levels = t["graph"]["levels"][scheme]
        if len(levels) != 6 or not all(HEX.match(v) for v in levels):
            problems.append(f"graph.levels.{scheme} must be six #RRGGBB values")

    space = clean(t["space"])
    for name, v in space.items():
        if v % 4 != 0:
            problems.append(f"space.{name} = {v} is off the 4pt grid")
    values = list(space.values())
    if values != sorted(values) or len(set(values)) != len(values):
        problems.append("space must be strictly ascending, one name per step")

    radius = clean(t["radius"])
    scale = [radius[k] for k in ("xs", "sm", "md", "lg", "pill")]
    if scale != sorted(scale):
        problems.append("radius xs < sm < md < lg < pill")
    if radius["md"] - radius["xs"] != radius["sm"]:
        problems.append("radius: concentric rule broken (md - xs must equal sm: 18 - 6 = 12)")

    roles = clean(t["type"])
    if tuple(roles) != TYPE_ROLES:
        problems.append(f"type roles must be exactly {TYPE_ROLES}, in that order")
    for name, role in roles.items():
        if role["size"] < 11:
            problems.append(f"type.{name} is {role['size']}pt; nothing goes under the 11pt floor")
        if role["weight"] not in range(100, 1000, 100):
            problems.append(f"type.{name}.weight {role['weight']} is not 100..900")
        if role["maxScale"] < 1:
            problems.append(f"type.{name}.maxScale must be >= 1 (1 means fixed)")

    table = t["dither"]["bayer8"]
    if sorted(v for row in table for v in row) != list(range(64)):
        problems.append("dither.bayer8 must hold each of 0..63 exactly once")
    for y in range(8):
        for x in range(8):
            want = round(bayer8(x, y) * 64)
            if table[y][x] != want:
                problems.append(
                    f"dither.bayer8[{y}][{x}] = {table[y][x]} but the shader computes {want}; "
                    "the table and the SkSL would dither differently"
                )

    if problems:
        raise SystemExit("design/tokens.json is invalid:\n  " + "\n  ".join(problems))


# ─── Swift ─────────────────────────────────────────────────────────────────────────────


def swift_rgb(name: str, pair: dict) -> str:
    lr, lg, lb = hex_to_rgb(pair["light"])
    dr, dg, db = hex_to_rgb(pair["dark"])
    return (
        f'    public static let {name} = SRGBPair(\n'
        f'        light: SRGB(r: {lr}, g: {lg}, b: {lb}),  // {pair["light"]}\n'
        f'        dark:  SRGB(r: {dr}, g: {dg}, b: {db})   // {pair["dark"]}\n'
        f'    )'
    )


def swift_num(v: float) -> str:
    return repr(float(v))


def gen_swift(t: dict) -> str:
    def group(key: str, mark: str | None = None) -> str:
        entries = clean(t[key])
        body = "\n".join(swift_rgb(name, pair) for name, pair in entries.items())
        return f"    // MARK: {mark or key}\n{body}"

    graph_light = ", ".join(
        "SRGB(r: {}, g: {}, b: {})".format(*hex_to_rgb(h)) for h in t["graph"]["levels"]["light"]
    )
    graph_dark = ", ".join(
        "SRGB(r: {}, g: {}, b: {})".format(*hex_to_rgb(h)) for h in t["graph"]["levels"]["dark"]
    )

    def lets(key: str, indent: str = "        ") -> str:
        return "\n".join(f"{indent}public static let {k} = {swift_num(v)}" for k, v in clean(t[key]).items())

    roles = "\n".join(
        f"        public static let {name} = TypeRoleSpec("
        f"size: {swift_num(r['size'])}, weight: {r['weight']}, tracking: {swift_num(r['tracking'])}, "
        f"line: {swift_num(r['line'])}, maxScale: {swift_num(r['maxScale'])}, "
        f"monospaced: {'true' if r.get('design') == 'monospaced' else 'false'})"
        for name, r in clean(t["type"]).items()
    )

    shadow = clean(t["shadow"])["float"]
    sr, sg, sb = hex_to_rgb(shadow["color"])
    dither = clean(t["dither"])
    bayer_rows = ",\n".join(
        "            " + ", ".join(f"{v:2d}" for v in row) for row in dither["bayer8"]
    )

    card = t["card"]
    return f"""{BANNER}

import Foundation

/// An sRGB colour. NOT Display P3 — see the note in design/tokens.json. The only place
/// these become SwiftUI Colors is BuilderUI/StripPalette.swift, via Color(.sRGB, ...).
public struct SRGB: Sendable, Equatable {{
    public let r: Double, g: Double, b: Double
    public init(r: Double, g: Double, b: Double) {{ self.r = r; self.g = g; self.b = b }}
}}

public struct SRGBPair: Sendable, Equatable {{
    public let light: SRGB, dark: SRGB
    public init(light: SRGB, dark: SRGB) {{ self.light = light; self.dark = dark }}
    public func resolve(dark isDark: Bool) -> SRGB {{ isDark ? dark : light }}
}}

/// One of the nine type roles. System font; `monospaced` means SF Mono. `maxScale` is the
/// Dynamic Type ceiling, 1 meaning fixed size.
public struct TypeRoleSpec: Sendable, Equatable {{
    public let size: Double, weight: Int, tracking: Double, line: Double, maxScale: Double
    public let monospaced: Bool
    public init(size: Double, weight: Int, tracking: Double, line: Double, maxScale: Double, monospaced: Bool) {{
        self.size = size; self.weight = weight; self.tracking = tracking; self.line = line
        self.maxScale = maxScale; self.monospaced = monospaced
    }}
    /// Line height in points.
    public var lineHeight: Double {{ (size * line).rounded() }}
}}

public enum DesignTokens {{

{group("strip")}

{group("mark")}

{group("surface")}

{group("data", "data hues. Never chrome, never a fill behind text. The third, human, is human_edit.")}

    // MARK: graph — coloured by ACTIVE HOURS, absolute buckets (see Tuning.graphHourBuckets)
    public static let graphLight: [SRGB] = [{graph_light}]
    public static let graphDark:  [SRGB] = [{graph_dark}]

    // MARK: layout
    public enum Space {{
{lets("space")}
    }}
    public enum Layout {{
{lets("layout")}
    }}
    public enum Radius {{
{lets("radius")}
    }}

    // MARK: type
    public enum TypeRole {{
{roles}
    }}

    // MARK: elevation. Exactly one shadow, for things that float over content.
    public enum Shadow {{
        public static let x = {swift_num(shadow["x"])}
        public static let y = {swift_num(shadow["y"])}
        /// CSS blur radius. SwiftUI's `.shadow(radius:)` is roughly half of it.
        public static let blur = {swift_num(shadow["blur"])}
        public static let color = SRGB(r: {sr}, g: {sg}, b: {sb})  // {shadow["color"]}
        public static let opacity = {swift_num(shadow["opacity"])}
    }}

    // MARK: dither. A cell is ink when its value (0..1) is > bayer8[y * 8 + x] / 64.
    public enum Dither {{
        public static let cell = {swift_num(dither["cell"])}
        public static let halftoneAngle = {swift_num(dither["halftoneAngle"])}
        public static let halftoneRadius = {swift_num(dither["halftoneRadius"])}
        public static let bayer8: [UInt8] = [
{bayer_rows}
        ]
    }}

    public enum Card {{
        public static let landscape = (w: {card["landscape"]["w"]}.0, h: {card["landscape"]["h"]}.0)
        public static let portrait  = (w: {card["portrait"]["w"]}.0,  h: {card["portrait"]["h"]}.0)
        public static let scale     = {float(card["scale"])}
    }}
}}
"""


# ─── TypeScript ────────────────────────────────────────────────────────────────────────


def css_shadow(s: dict) -> str:
    r, g, b = (int(s["color"][i : i + 2], 16) for i in (1, 3, 5))
    return f"{s['x']} {s['y']}px {s['blur']}px rgba({r},{g},{b},{s['opacity']})"


def gen_ts(t: dict) -> str:
    tokens = clean(t)
    shadow = css_shadow(tokens["shadow"]["float"])
    return f"""{BANNER}

export const tokens = {json.dumps(tokens, indent=2)} as const;

export type Scheme = 'light' | 'dark';

/** All values are sRGB hex, which is what react-native-svg expects. */
export function pick(pair: {{ light: string; dark: string }}, scheme: Scheme): string {{
  return pair[scheme];
}}

/** The one shadow token as a React Native `boxShadow` string, derived from `shadow.float`. */
export const FLOAT_SHADOW = '{shadow}';
"""


def main() -> None:
    t = json.loads(SPEC.read_text())
    validate(t)
    print("gen_tokens.py")
    write(ROOT / "Packages/BuilderKit/Sources/BuilderModel/Generated/DesignTokens.swift", gen_swift(t))
    write(ROOT / "mobile/src/generated/tokens.ts", gen_ts(t))


if __name__ == "__main__":
    main()
