#!/usr/bin/env python3
"""Generate the device table into Python and TypeScript, and hold it to what iOS measured.

spec/devices.v1.json is THE ONLY place a frame size lives (docs/ship-kit.md): every screen a demo
is filmed on, every canvas it is composed into, the GIF loop and the App Store slots. Two outputs:

    capture/demo/devices_table.py   standard library only, like the rest of capture: the Mac
                                    picks a device, checks every capture against it and composes
                                    from it (capture/demo/devices.py holds the lookups)
    mobile/src/generated/devices.ts the phone's gallery shape, the kit's format tabs

No Swift: nothing in BuilderKit draws a demo, and a type nobody constructs is a type nobody keeps
right. The server reads the formats through spec/shipkit.v1.json's generator, which imports this
one's loader, so the sizes a kit may upload are these sizes.

`check` refuses a table whose output would compile and still be wrong: pixels that are not points
times scale (the elongated phone, typed by hand), a corner radius wider than half the screen, a
safe area taller than it, a simulator type claimed by two rows (the capture would not know which
row it filmed), an odd format side (H.264 refuses it), and a default or App Store slot naming a
row that does not exist.

`--verify` holds every row to docs/research/device-measurements.json, which
scripts/measure_devices.py writes from iOS itself on this Mac's simulators, and to the device
types installed now (`xcrun simctl list devicetypes`), and says which rows it could not verify.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec" / "devices.v1.json"
MEASURED = ROOT / "docs" / "research" / "device-measurements.json"
PY_OUT = ROOT / "capture" / "demo" / "devices_table.py"
TS_OUT = ROOT / "mobile" / "src" / "generated" / "devices.ts"

BANNER_PY = "# GENERATED by scripts/gen_devices.py from spec/devices.v1.json — DO NOT EDIT."
BANNER_TS = "// GENERATED by scripts/gen_devices.py from spec/devices.v1.json — DO NOT EDIT."

FAMILIES = ("iphone", "ipad", "mac")
DEVICE_KEYS = {
    "id", "name", "family", "models", "points", "scale", "pixels", "corner_radius", "safe_area",
    "dynamic_island", "simulator_types", "app_store", "source",
}  # fmt: skip


def clean(node):
    if isinstance(node, dict):
        return {k: clean(v) for k, v in node.items() if not k.startswith("_")}
    if isinstance(node, list):
        return [clean(v) for v in node]
    return node


def load() -> dict:
    s = clean(json.loads(SPEC.read_text()))
    check(s)
    return s


def check(s: dict) -> None:
    ids = [d["id"] for d in s["devices"]]
    assert len(ids) == len(set(ids)), f"a device id twice: {ids}"
    claimed: dict[str, str] = {}
    for d in s["devices"]:
        assert set(d) == DEVICE_KEYS, f"{d['id']}: keys {sorted(set(d) ^ DEVICE_KEYS)} differ from the table's"
        assert d["family"] in FAMILIES, f"{d['id']}: family {d['family']!r}"
        (pw, ph), sc, (xw, xh) = d["points"], d["scale"], d["pixels"]
        assert (round(pw * sc), round(ph * sc)) == (xw, xh), (
            f"{d['id']}: {pw}x{ph} points at {sc}x is {round(pw * sc)}x{round(ph * sc)} pixels, and the row says "
            f"{xw}x{xh}. A pixel size typed apart from its points is how a phone comes out elongated."
        )
        assert pw < ph or d["family"] == "mac", f"{d['id']}: a phone or tablet row is portrait"
        assert 0 <= d["corner_radius"] < min(pw, ph) / 2, f"{d['id']}: corner radius {d['corner_radius']}"
        sa = d["safe_area"]
        assert set(sa) == {"top", "bottom"} and 0 <= sa["top"] + sa["bottom"] < ph / 2, f"{d['id']}: safe area {sa}"
        assert isinstance(d["dynamic_island"], bool)
        for t in d["simulator_types"]:
            assert t.startswith("com.apple.CoreSimulator.SimDeviceType."), f"{d['id']}: {t}"
            assert t not in claimed, f"{t} is claimed by {claimed[t]} and {d['id']}: a capture on it would not know its row"
            claimed[t] = d["id"]
        if d["family"] == "mac":
            assert not d["simulator_types"] and not d["dynamic_island"], f"{d['id']}: a Mac window has no simulator or island"
        assert d["source"] == "measured" or not d["simulator_types"], (
            f"{d['id']}: a row a simulator can measure says `measured`, and is held to it by --verify"
        )
    for key in ("default_phone", "default_web_phone", "default_web_desktop"):
        assert s[key] in ids, f"{key} {s[key]!r} is not a row"
    by = {d["id"]: d for d in s["devices"]}
    assert by[s["default_phone"]]["family"] == "iphone" and by[s["default_web_phone"]]["family"] == "iphone"
    assert by[s["default_web_desktop"]]["family"] == "mac"
    assert 0 < s["match_tolerance"] < 0.02, "the match tolerance is a rounding allowance, not a range of phones"
    fids = [f["id"] for f in s["formats"]]
    assert len(fids) == len(set(fids))
    for f in s["formats"]:
        w, h = f["size"]
        assert w % 2 == 0 and h % 2 == 0, f"format {f['id']}: H.264 needs even sides"
    assert s["terminal"]["format"] in fids, f"terminal format {s['terminal']['format']!r} is not a format"
    lw, lh = s["loop"]["size"]
    assert lw % 2 == 0 and lh % 2 == 0 and 1 <= s["loop"]["fps"] <= 30
    slots = [a["id"] for a in s["app_store"]]
    for a in s["app_store"]:
        assert a["device"] in by, f"app store slot {a['id']} names {a['device']}"
        assert by[a["device"]]["app_store"] == a["id"], f"{a['device']} does not name slot {a['id']} back"
    for d in s["devices"]:
        assert d["app_store"] is None or d["app_store"] in slots, f"{d['id']}: app_store {d['app_store']!r}"
    # Every pair of rows must be told apart by the tolerance, or a capture could match two; the
    # one exception is a pixel size two rows share EXACTLY (spec `_same_screen`).
    tol = s["match_tolerance"]
    phones = [d for d in s["devices"] if d["family"] != "mac"]
    for i, a in enumerate(phones):
        for b in phones[i + 1 :]:
            if a["pixels"] == b["pixels"]:
                continue  # one screen size, two rows (spec `_same_screen`)
            close = all(abs(a["pixels"][k] - b["pixels"][k]) <= tol * a["pixels"][k] for k in (0, 1))
            assert not close, f"{a['id']} and {b['id']} are within {tol:.1%} of each other: a capture would match both"


# ------------------------------------------------------------------------------ emit


def _py(v) -> str:
    """A Python literal. `repr`, not JSON with its words swapped: a replace of "true" would also
    rewrite a model name or a note that happens to contain the word."""
    return repr(v)


def gen_py(s: dict) -> str:
    rows = "\n".join(f"    {_py(d)}," for d in s["devices"])
    formats = "\n".join(f"    {_py(f)}," for f in s["formats"])
    slots = "\n".join(f"    {_py(a)}," for a in s["app_store"])
    return f'''{BANNER_PY}
"""Every screen a demo is filmed on and every canvas it is composed into (docs/ship-kit.md).

Rows are dicts, not classes, so this module imports nothing: capture is standard library only.
The lookups and the size check are capture/demo/devices.py.
"""

from __future__ import annotations

VERSION = {s["version"]}

#: How far a captured width or height may be from its row's pixels, as a share of the row's.
MATCH_TOLERANCE = {s["match_tolerance"]}

DEFAULT_PHONE = {_py(s["default_phone"])}
DEFAULT_WEB_PHONE = {_py(s["default_web_phone"])}
DEFAULT_WEB_DESKTOP = {_py(s["default_web_desktop"])}

#: id, name, family (iphone, ipad, mac), models, points [w, h], scale, pixels [w, h], corner_radius
#: (points), safe_area {{top, bottom}} (points, portrait), dynamic_island, simulator_types,
#: app_store (a slot id or None), source ("measured", or why it could not be).
DEVICES: list[dict] = [
{rows}
]

#: The canvases a capture is composed into: id, label, size [w, h] in pixels, what it is for.
FORMATS: list[dict] = [
{formats}
]

#: The GIF loop: size [w, h], frames a second, the most bytes it may be.
LOOP: dict = {_py(s["loop"])}

#: App Store screenshot slots, each exported at its device row's pixels.
APP_STORE: list[dict] = [
{slots}
]

#: A CLI's or a library's canvas: one of FORMATS, and the corner its card is drawn with (pixels).
TERMINAL: dict = {_py(s["terminal"])}
'''


def _ts(v) -> str:
    return json.dumps(v, ensure_ascii=False)


def gen_ts(s: dict) -> str:
    rows = "\n".join(f"  {_ts(d)}," for d in s["devices"])
    formats = "\n".join(f"  {_ts(f)}," for f in s["formats"])
    slots = "\n".join(f"  {_ts(a)}," for a in s["app_store"])
    fam = " | ".join(_ts(f) for f in FAMILIES)
    return f"""{BANNER_TS}

/** Every screen a demo is filmed on and every canvas it is composed into (docs/ship-kit.md). */
export const DEVICES_VERSION = {s["version"]};

/** How far a captured width or height may be from its row's pixels, as a share of the row's. */
export const MATCH_TOLERANCE = {s["match_tolerance"]};

export const DEFAULT_PHONE = {_ts(s["default_phone"])};
export const DEFAULT_WEB_DESKTOP = {_ts(s["default_web_desktop"])};

export type DeviceFamily = {fam};

export interface DeviceRow {{
  id: string;
  name: string;
  family: DeviceFamily;
  models: readonly string[];
  /** [width, height] in points, portrait for a phone or tablet. */
  points: readonly [number, number];
  scale: number;
  /** [width, height] in pixels: points times scale, checked by the generator. */
  pixels: readonly [number, number];
  /** The screen's own corner radius in points, as iOS reports it (UIScreen._displayCornerRadius). */
  corner_radius: number;
  /** Portrait safe area in points: the status bar or island above, the home indicator below. */
  safe_area: {{ readonly top: number; readonly bottom: number }};
  dynamic_island: boolean;
  simulator_types: readonly string[];
  app_store: string | null;
  source: string;
}}

export interface FormatRow {{
  id: string;
  /** "9:16" */
  label: string;
  /** [width, height] in pixels. */
  size: readonly [number, number];
  for: string;
}}

export const DEVICES: readonly DeviceRow[] = [
{rows}
];

export const FORMATS: readonly FormatRow[] = [
{formats}
];

export const LOOP = {_ts(s["loop"])} as const;

export const APP_STORE: readonly {{ id: string; label: string; device: string }}[] = [
{slots}
];

export const TERMINAL = {_ts(s["terminal"])} as const;
"""


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)
    print(f"  wrote {path.relative_to(ROOT)}")


# ----------------------------------------------------------------------------- verify


def installed_types() -> set[str] | None:
    import subprocess

    try:
        r = subprocess.run(["xcrun", "simctl", "list", "devicetypes", "-j"], capture_output=True, text=True, timeout=60, check=False)
        return {t["identifier"] for t in json.loads(r.stdout)["devicetypes"]}
    except (OSError, ValueError, KeyError, subprocess.SubprocessError):
        return None


def verify(s: dict) -> list[str]:
    """Every way the table differs from what iOS measured. Prints what it could not verify."""
    measured = json.loads(MEASURED.read_text())["devices"] if MEASURED.exists() else {}
    here = installed_types()
    problems: list[str] = []
    for d in s["devices"]:
        if not d["simulator_types"]:
            print(f"  {d['id']:<18} not verifiable in a simulator: {d['source']}")
            continue
        seen = 0
        for t in d["simulator_types"]:
            short = t.rsplit(".", 1)[-1]
            if here is not None and t not in here:
                print(f"  {d['id']:<18} {short}: not installed on this Mac, not verified")
            m = measured.get(t)
            if not m or not m.get("installed"):
                print(f"  {d['id']:<18} {short}: never measured")
                continue
            seen += 1
            ios, prof = m["ios"], m["profile"]
            want = {
                "points": list(d["points"]),
                "scale": d["scale"],
                "pixels": list(d["pixels"]),
                "corner_radius": d["corner_radius"],
                "safe_top": d["safe_area"]["top"],
                "safe_bottom": d["safe_area"]["bottom"],
            }
            got = {
                "points": [round(x) for x in ios["points"]],
                "scale": ios["scale"],
                "pixels": [round(x) for x in ios["native_pixels"]],
                "corner_radius": round(ios["corner_radius"], 2),
                "safe_top": ios["safe_top"],
                "safe_bottom": ios["safe_bottom"],
            }
            if prof["pixels"] != list(d["pixels"]):
                problems.append(f"{d['id']} {short}: profile.plist says {prof['pixels']}, the row {d['pixels']}")
            for k, v in want.items():
                if isinstance(v, float) or isinstance(got[k], float):
                    ok = abs(float(v) - float(got[k])) < 0.01 if not isinstance(v, list) else v == got[k]
                else:
                    ok = v == got[k]
                if not ok:
                    problems.append(f"{d['id']} {short}: {k} is {got[k]} on iOS and {v} in the table")
        if seen:
            print(f"  {d['id']:<18} verified on {seen} of {len(d['simulator_types'])} simulator types")
    return problems


def main() -> None:
    s = load()
    if "--verify" in sys.argv:
        problems = verify(s)
        for p in problems:
            print(f"MISMATCH {p}")
        sys.exit(1 if problems else 0)
    write(PY_OUT, gen_py(s))
    write(TS_OUT, gen_ts(s))


if __name__ == "__main__":
    main()
